### ISSUE TITLE
Configuring Tables

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-recipes#113]
Currently only the 1st option is what is done in books.

There seem to be several ways for where to put the numbers for tables in a book:

---

| Tables        | Are           | Cool  |
| ------------- |---------------| ------|
| foo           | bar           | baz   |
| foo           | bar           | baz   |

<small><strong>4.3 Table Title</strong> Table Caption</small>

---

# 4.3 Table Title

| Tables        | Are           | Cool  |
| ------------- |---------------| ------|
| foo           | bar           | baz   |
| foo           | bar           | baz   |

<small>Table Caption</small>

---

# Table Title

| Tables        | Are           | Cool  |
| ------------- |---------------| ------|
| foo           | bar           | baz   |
| foo           | bar           | baz   |

<small><strong>4.3</strong> Table Caption</small>

---

# Unnumbered Table Title 

| Tables        | Are           | Cool  |
| ------------- |---------------| ------|
| foo           | bar           | baz   |
| foo           | bar           | baz   |

<small>Table Caption</small>

---

| Tables        | Are           | Cool  |
| ------------- |---------------| ------|
| foo           | bar           | baz   |
| foo           | bar           | baz   |

<small><strong>Unnumbered Table Title</strong> Table Caption</small>

---

The proposal is to configure 2 things:

- Choose where the title goes 
  - above table
  - inside caption
- Choose where the numbering goes
  - on the caption 
  - on the title (with a fallback to the caption if there is no title)
  - none (`.unnumbered`)

This config option (except for the unnumbering) is done per-book.

**Comment by helenemccarron** [comment]
Started here: https://github.com/Connexions/cnx-recipes/pull/418

**Comment by openstaxalina** [comment]
To discuss Monday: I am concerned about a global change when we have already released business book designs.  Is this needed for Assignable Webview (matching numbering and collation), or can we defer to BakedPDF styling, which will have a more comprehensive approach w/ UX input?

**Comment by lwtchu** [comment]
Reference https://github.com/Connexions/oer.exports/issues/3399 

We decided this approach so that "fake titles" for tables so a fake title and a regular table title wouldn't be an "either or" option for the books. Example: In _Astronomy_, it was forced for all tables to have a fake title. Using the class will make it easier to consistently style them.

**Comment by helenemccarron** [comment]
Phase one: support top titled tables (addressed in PR #418 )
@Stackblocks, to test please look at the table with the class `top-titled` to verify the text in the first header row of the table has been moved to a div above the table. See before and after screenshots below.

Before:
![2018-07-11_11-02-05](https://user-images.githubusercontent.com/8514591/42585118-639bca90-84fa-11e8-9cc6-455c2edd72d0.png)

After:
![2018-07-11_10-59-09](https://user-images.githubusercontent.com/8514591/42585127-6c92cb12-84fa-11e8-9673-885bcc25ed76.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/42601542-93935f66-852b-11e8-9e4f-4ca395c79e37.png)
