### ISSUE TITLE
TOC - End of chapter collations

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#12]
It needs to be present for navigation purposes on webview but isn't currently displayed in PDF. We need to determine what is needed for PDF display. The possibilities are to simply hide in the pdf via css or to display it to match webview.

**Comment by philschatz** [comment]
Have any decisions been made on this?

**Comment by helenemccarron** [comment]
David and Anthony decided to leave them visible but unnumbered
