### ISSUE TITLE
AP bio notes do not appear to be titled properly

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#163]
`ap-science-practices` for example does not have a title generated.

**Comment by helenemccarron** [comment]
@tomjw64's work on refactor the note mixin should fix this.

**Comment by tomjw64** [comment]
Addressed in PR #229

**Comment by tomjw64** [comment]
![example](https://cloud.githubusercontent.com/assets/1285308/26657323/c789bcd6-4628-11e7-80a3-447086e04de8.png)

Example of the said note type

**Comment by tomjw64** [comment]
Found in TEA biology sample
