### ISSUE TITLE
Introductory Statistics => Note inside TI-83... feature causing title to appear in wrong place.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#182]
# Scenario

“Using the TI-83…” feature containing a nested note is displaying the feature title above the nested note and below the start of the content.

# Reproducibility Details

* **Impact area**: Content
*  **User**: n/a
*  **URL / Location**: https://dev00.cnx.org/contents/MBiUQmmY@18.13:L3GARsYT@5/47-Poisson-Distribution
* **How many times were you able to reproduce the issue?** Static

*  **Steps to reproduce**:

n/a

* **Images or screenshots Included:** Yes  (_attach below_)

![image](https://cloud.githubusercontent.com/assets/12678235/25588575/7c615150-2e6e-11e7-8967-ba0855f96df3.png)

# Environment:

* **Instance**: Dev00
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

**Comment by tomjw64** [comment]
This issue likely appears because of a class="note" occurring within another class="note"

**Comment by tomjw64** [comment]
Addressed in PR #229

**Comment by Stackblocks** [comment]
Appears resolved after re-bake with bio-fixes ruleset.
![image](https://user-images.githubusercontent.com/12678235/26839697-6d4b3076-4aa9-11e7-8e73-64e1ab525bb9.png)
