### ISSUE TITLE
Multiple Books => Chapter Introductions missing "Chapter Outline."

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#185]
# Scenario

Chapter introductions do not include the “Chapter Outline” element.

# Reproducibility Details

* **Impact area**: Content
*  **User**: Name of user that encountered error.
*  **URL / Location**: https://dev00.cnx.org/contents/Ax2o07Ul@9.43:HR_VN3f7@3/11-Introduction-to-Science-and
* **How many times were you able to reproduce the issue?** Most / All Chapters

*  **Steps to reproduce**:

1. Open the book’s [webview version](https://dev00.cnx.org/contents/Ax2o07Ul@9.43:pFeekPiU@14/Preface-to-College-Physics)
2. Expand a chapter in the TOC, and click on the introductory section.
3. Observe the lack of “Chapter Outline."

* **Images or screenshots Included:** Yes  (_attach below_)

![image](https://cloud.githubusercontent.com/assets/12678235/25711802/6f64724a-30b5-11e7-8ce6-01daa17efd39.png)

![image](https://cloud.githubusercontent.com/assets/12678235/25711814/756c4762-30b5-11e7-967e-154b7ed9a2f2.png)

# Environment:

* **Instance**: Dev00
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

**Comment by kerwinso** [comment]
Also found in [College Biology](https://dev00.cnx.org/contents/GFy_h8cu@10.61:djajv-uA@2/Introduction):


![image](https://cloud.githubusercontent.com/assets/11298165/26316386/bd171042-3ed9-11e7-8a9e-601b11274c26.png)

**Comment by kerwinso** [comment]
And [AP Physics](https://dev.cnx.org/contents/jQSmhtXo@14.5:VRr0q8ns@14.5/Glossary):

![image](https://cloud.githubusercontent.com/assets/11298165/26790438/50ddcbb8-49d9-11e7-8225-12f575aa9557.png)

**Comment by kerwinso** [comment]
List of affected books, each will be checked off when it passes QA:
- [ ] College Physics
- [ ]  College Biology

@Stackblocks Any more? feel free to edit this list

**Comment by helenemccarron** [comment]
This is a two fold issue. The chapter outline wasn't implemented in biology. It was fixed in @264. Another PR will be created to fix it in Physics, which needs the learning objectives added.

**Comment by helenemccarron** [comment]
Addressed in PR #269. Please note that the Chapter Outline doesn't contain numbering (the code for that is in the University Physics branch). This applies only to Physics at the moment.

**Comment by kerwinso** [comment]
Verified in all affected books on dev.cnx.org on `LO-in-CO` branch. See [this comment](https://github.com/Connexions/cnx-recipes/issues/185#issuecomment-306221128) for more details.

**Comment by kerwinso** [comment]
This bug has come back and now seems to affect all books, may be related to #282.

**Comment by nyxer95** [comment]
Per @reedstrm, this requires cnxml to html transform. After code is deployed, requires re-baking.  If persists, would be recipe fix that could be treated as a bug.

**Comment by nyxer95** [comment]
Per @reedstrm -- All regressions between dev and QA probably got fixed with deploy on Monday and additional code changes that we deployed an hour ago.

**Comment by kerwinso** [comment]
Fixed again on qa.cnx.org.
