### ISSUE TITLE
College Physics => Discrepancies between PDF and updated WebView indices

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#188]
# Scenario

The index in the updated WebView version of College Physics both has extra entries and is missing entries when compared to the production PDF.

# Reproducibility Details

* **Impact area**: Content
*  **User**: n/a
*  **URL / Location**: https://dev00.cnx.org/contents/Ax2o07Ul@9.43:oupgxknN@9.43/Index
* **How many times were you able to reproduce the issue?** n/a

*  **Steps to reproduce**:

1. Open the [book](https://dev00.cnx.org/contents/Ax2o07Ul@9.43:oupgxknN@9.43/Index)
2. Open the Index

* **Images or screenshots Included:** Yes  (_attach below_)
![image](https://cloud.githubusercontent.com/assets/12678235/25867242/97e1aafa-34be-11e7-9fc3-9aa318799608.png)

# Environment:

* **Instance**: Dev00
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

**Comment by tomjw64** [comment]
This issue appears to be two-part.
1) The reason for the extra entries in the Symbols section for the baked book are that there is leading whitespace in those terms, and so they are sorted by " ", putting them into symbols section. This is not something that we can bake out at this time, but is something a content change could fix.
2) The entries that are missing from the index in the baked book, but exist in the PDF seem to all be pulled there from the glossary sections of each chapter, which we do not currently use to pull terms from in baked books. This can be fixed via baking, however, there may be an argument against having both "Accuracy" and "accuracy", both "aberrations" and "aberration", etc, as essentially duplicates in the index.

I will write an additional note as to which books may need the white-space content fix.

**Comment by tomjw64** [comment]
- College Physics
  - change in angular velocity
    - Section 10.2
    - searchable nearby: "is the change in time. The units of angular acceleration are"
  - decay equation
    - Section 31.5
    - searchable nearby: "generally this information must be looked up in a table of isotopes, such as in"
  - drift velocity
    - Section 20.2
    - searchable nearby: "The electron paths thus appear nearly random, like the motion of atoms in a gas"

**Comment by oscryan** [comment]
I took spaces out of these three term tags and republished the modules on production.

**Comment by tomjw64** [comment]
Note for our team: We need to collate glossary terms into the index.

**Comment by kerwinso** [comment]
Same issue found in AP Physics: https://dev.cnx.org/contents/jQSmhtXo@14.5:Xm0hU3Qa@14.5/Index

**Comment by Stackblocks** [comment]
Removing the leading white space fixed the issue. ✅
