### ISSUE TITLE
TEA BOOKS => Links to answer key need to be removed.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#194]
In the EoC problems the number-links to answer keys are still present, even though the answer keys are gone. They need to be removed.

**Comment by helenemccarron** [comment]
Per Alana: we will use a common rule to remove all even answers in titles that need to be modified. Other books will not be modified. 
It is acceptable that the answers suppressed by the ruleset do not match the PDF (e.g. 1, 3, 5 could become 2, 4, 6) but the same number of answers should be preserved. @Stackblocks @kerwinso

**Comment by helenemccarron** [comment]
Couldn't reproduce. Can you please confirm it's no longer a problem?

**Comment by kerwinso** [comment]
Reassigning to @Stackblocks.

**Comment by Stackblocks** [comment]
After rebake on dev.cnx.org with current ruleset, does not appear to be an issue.
