### ISSUE TITLE
College Biology => Art Connection feature says "Art Connection" twice

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#201]
In Webview, the Art Connection feature has a title "Art Connection", and also a subtitle "Art Connection." Note: in the PDF, none of the Art Connection features I saw seem to have subtitles.

Webview URL: https://dev00.cnx.org/contents/GFy_h8cu@10.61:vogY0C26@17/21-Atoms-Isotopes-Ions-and-Mol

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26317327/b6755de0-3edc-11e7-97f6-a25c827a733f.png)

**Comment by tomjw64** [comment]
Addressed in PR #229

**Comment by kerwinso** [comment]
Verified fix on https://dev.cnx.org/contents/GFy_h8cu@10.61:vogY0C26@17/21-Atoms-Isotopes-Ions-and-Mol:

![image](https://cloud.githubusercontent.com/assets/11298165/26792685/d95d6f96-49e0-11e7-96c0-36c3b5ac4ba3.png)
