### ISSUE TITLE
College Biology => Evolution Connection feature says "Evolution Connection" twice

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#203]
Similar to #201. In Webview, the Evolution Connection feature has a title "Evolution Connection", and also a subtitle "Evolution Connection", in addition to the actual subtitle. 

Webview URL: 
https://dev00.cnx.org/contents/GFy_h8cu@10.61:gNLp76vu@13/12-Themes-and-Concepts-of-Biol

Webview on the left, PDF on the right:
 ![image](https://cloud.githubusercontent.com/assets/11298165/26319633/662fbd68-3ee5-11e7-8617-d48823ce61ef.png)

**Comment by kerwinso** [comment]
In [46.1](https://dev00.cnx.org/contents/GFy_h8cu@10.61:XzG37RPg@5/461-Ecology-of-Ecosystems), the duplicate subtitle says `Evolution Conenction` (misspelled). Rawrf??

![image](https://cloud.githubusercontent.com/assets/11298165/26599978/fd65297e-453f-11e7-994b-0e6c13790072.png)

**Comment by tomjw64** [comment]
Addressed in PR #229

**Comment by kerwinso** [comment]
Verified fixes:

https://dev.cnx.org/contents/GFy_h8cu@10.61:gNLp76vu@13/12-Themes-and-Concepts-of-Biol
![image](https://cloud.githubusercontent.com/assets/11298165/26796661/e5a80a68-49ef-11e7-8799-a1b409990e5f.png)

https://dev.cnx.org/contents/GFy_h8cu@10.61:XzG37RPg@5/461-Ecology-of-Ecosystems
![image](https://cloud.githubusercontent.com/assets/11298165/26796630/c4dd115c-49ef-11e7-9f0c-7e5f697810c1.png)
