### ISSUE TITLE
College Biology => Career Connection feature says "Career Connection" twice

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#204]
Similar to #201. In Webview, the Career Connection feature has a title "Career Connection Note", and also a subtitle "Career Connection", in addition to the actual subtitle. 

Webview URL: 
https://dev00.cnx.org/contents/GFy_h8cu@10.61:gNLp76vu@13/12-Themes-and-Concepts-of-Biol

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26320512/a3e51416-3ee8-11e7-8481-237c887fee9c.png)

**Comment by kerwinso** [comment]
In section 7.1 (https://dev00.cnx.org/contents/GFy_h8cu@10.61:dfq-SF-8@8/71-Energy-in-Living-Systems), the subtitle actually says "Career Connections" (note the plural as opposed to other instances of the singular). How very odd. 

![image](https://cloud.githubusercontent.com/assets/11298165/26459627/b66a9af6-413c-11e7-99d0-9c601ce97303.png)

**Comment by tomjw64** [comment]
Addressed in PR #229

**Comment by kerwinso** [comment]
Verified fixes:
https://dev00.cnx.org/contents/GFy_h8cu@10.61:gNLp76vu@13/12-Themes-and-Concepts-of-Biol
![image](https://cloud.githubusercontent.com/assets/11298165/26792870/6dbdf714-49e1-11e7-9f43-e895ff675110.png)

https://dev00.cnx.org/contents/GFy_h8cu@10.61:dfq-SF-8@8/71-Energy-in-Living-Systems
![image](https://cloud.githubusercontent.com/assets/11298165/26792862/69300944-49e1-11e7-8a06-aff47f5b627a.png)
