### ISSUE TITLE
Multiple books => Suppress "Summary" content at top of EOC modules (composite pages)

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#205]
In the webview for all books with updated rulesets, a toggle section called 'Summary' appears at the top of every end-of-chapter (EOC) module, e.g. Key Terms, Chapter Summary, Review Questions, etc.

This section should be suppressed in all EOC modules for every book. It appears to contain metadata that applies to the entire collection.

Here's an example screenshot from College Biology:
https://dev00.cnx.org/contents/GFy_h8cu@10.61:RXKQK90D@10.61/Art-Connection-Questions

![image](https://cloud.githubusercontent.com/assets/11298165/26322418/9bc3e91c-3ef0-11e7-85bc-eb2ab77d770c.png)

**Comment by kerwinso** [comment]
List of affected books, each will be checked off when it passes QA:
- [ ]  Principles of Econ
- [ ]  Statistics
- [ ]  College Biology
- [ ]  AP Physics

@Stackblocks Any more?

**Comment by openstaxalina** [comment]
Agree this should be suppressed. I do not know of a precedent or pedagogical reason to include the book-level metadata at the top of these modules.

**Comment by reedstrm** [comment]
This is a straight-up bug in the publishing path for composite-pages. They'll be gone once I step on it.

**Comment by openstaxalina** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10219885-249104445_1-s1-v1.png?transparent=1&palette=1&width=246) squish!

**Comment by reedstrm** [comment]
Actually, the bug I thought was in cnx-epub is not there. I do however see code in the recipe for biology (for example) that explicitly copies the book metadata into each composite page.  I think I have to pass this to @helenemccarron and her crew.

**Comment by kerwinso** [comment]
The summary toggle for baked books has been hidden with this PR, thereby resolving this issue: https://github.com/Connexions/webview/issues/1574. 

![image](https://user-images.githubusercontent.com/11298165/28332713-5e8766b2-6bbb-11e7-8feb-dfb0dbf2f744.png)

(Note: for NON-baked books, i.e. non-Openstax books on CNX, the Summary toggle is still there. This is the desired behavior.)
