### ISSUE TITLE
Economics => "Note:" is showing up in the title of Note-type features.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#206]
# Scenario

“Note:” is getting prepended to the title of note-type features in the Webview.

# Reproducibility Details

* **Impact area**: Content
*  **User**: n/a
*  **URL / Location**: https://dev00.cnx.org/contents/aWGdK2jw@11.332:UfIHC0qu@6/Introduction-to-Demand-and-Sup
* **How many times were you able to reproduce the issue?** n/a

*  **Steps to reproduce**:

n/a

* **Images or screenshots Included:** Yes  (_attach below_)
![image](https://cloud.githubusercontent.com/assets/12678235/26324005/a3f885e2-3ef6-11e7-94fd-c9e4ba3489ca.png)
![image](https://cloud.githubusercontent.com/assets/12678235/26324047/cd6b2538-3ef6-11e7-8f1d-4376006d7a69.png)

# Environment:

* **Instance**: Dev00
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: Medium
* **Frequency of occurrence**: Common

**Comment by caderitter** [comment]
![screen shot 2017-05-22 at 4 25 26 pm](https://cloud.githubusercontent.com/assets/16979809/26329122/53b0855c-3f0b-11e7-9f81-59cc380b3f97.png)

**Comment by kerwinso** [comment]
@Stackblocks Not ready for testing just yet, waiting on code approval for https://github.com/Connexions/webview/issues/1559

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/27871615-c95ef16c-616b-11e7-8326-94b440a4fad2.png)
