### ISSUE TITLE
College Biology => Figure links in Art Connection Questions broken

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#207]
1. Go to https://dev00.cnx.org/contents/GFy_h8cu@10.61:RXKQK90D@10.61/Art-Connection-Questions
1. Click on any of the Figure links

Notice you are taken to the module that contains the figure, NOT the specific figure (like on CNX.org).

URL: https://dev00.cnx.org/contents/GFy_h8cu@10.61:RXKQK90D@10.61/Art-Connection-Questions

![image](https://cloud.githubusercontent.com/assets/11298165/26327151/e1ce5236-3f03-11e7-90a9-9d09fd254fe8.png)

**Comment by kerwinso** [comment]
Sometimes I can reproduce this, sometimes not. I thought it might be caused by having the Contents pane on the left open, but, that doesn't seem to be the deciding factor. 

If you can't reproduce this bug, please comment accordingly and we'll de-prioritize it.

**Comment by caderitter** [comment]
Seems to be working for me! I did notice that pressing the back button has some weird behavior.

**Comment by kerwinso** [comment]
Talked to @edwoodward about the weird back button behavior. It's a known issue and he will have a CNX intern try to look at it this summer.

**Comment by kerwinso** [comment]
I'm finding similar behavior in the Answer Key (clicking the Figure link goes to the top of the corresponding page, not the figure itself): 
https://dev00.cnx.org/contents/GFy_h8cu@10.61:otIsPXu6@10.61/Answer-Key

I'm on Chrome 58.0 incognito, El Capitan.

@caderitter @helenemccarron Are you able to reproduce?

**Comment by kerwinso** [comment]
This may be due to the URL hash bug that @edwoodward is currently working on with a CNX intern: https://trello.com/c/HTRKJnP1/131-bug-cannot-link-to-id-in-webview

**Comment by helenemccarron** [comment]
@kerwinso yes, those are links within `composite-page`, this is the same issue as #213. The link doesn't take the user to the anchor, only to the top of the page.

**Comment by kerwinso** [comment]
See See https://github.com/Connexions/webview/issues/1450 (reported by Helene)

**Comment by kerwinso** [comment]
Addressed in https://github.com/Connexions/webview/pull/1551.

**Comment by kerwinso** [comment]
Looked at on https://qa.cnx.org/contents/GFy_h8cu@10.115:otIsPXu6/Answer-Key. The behavior is still erratic -- sometimes it works, sometimes it doesn't. See [this comment](https://github.com/Connexions/cnx-recipes/issues/215#issuecomment-313214276) for more info.

**Comment by kerwinso** [comment]
Technically this works now, but there is still the "in book link reloads page twice" bug that needs to be addressed: https://trello.com/c/ihhMXAOO/68-bug-in-book-links-break-browser-history

**Comment by kerwinso** [comment]
Verified in https://qa.cnx.org/contents/GFy_h8cu@10.115:gMYUyGsT@10.115/Art-Connection-Questions.
Fixed by https://github.com/Connexions/webview/pull/1577. The page does not reload twice but takes you right to the figure you clicked.
