### ISSUE TITLE
College Biology => Video in Link to Learning extends past feature box borders

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#208]
In chapter 2.1, the Link to Learning feature on orbitals is displaying an inline video that is too wide for the feature box. On cnx.org it looks fine (I can't compare it to the PDF because the PDF doesn't have embedded videos.)

Text to search: `the spatial arrangement of the p and s orbitals`

NOTE: This only occurs if the Contents pane on the left is open and the Chrome browser zoom is set to greater than 100%. 

dev URL: 
https://dev.cnx.org/contents/GFy_h8cu@10.61:vogY0C26@17/21-Atoms-Isotopes-Ions-and-Mol

CNX (prod) URL: 
https://cnx.org/contents/GFy_h8cu@10.99:vogY0C26@18/Atoms-Isotopes-Ions-and-Molecu

Screenshot (dev00 on the left, prod on the right):
![image](https://cloud.githubusercontent.com/assets/11298165/26329369/918d1a24-3f0c-11e7-8622-dc49a1429eca.png)

**Comment by kerwinso** [comment]
Probably not high priority since it's a bit of an edge case. Browser zoom needs to be > 100% to reproduce.

**Comment by tomjw64** [comment]
I took a look at all the videos. Each one seems to have height: 371.4 and width: 660, so the content is consistent. This is probably best as a styling fix on WebView, since CSS can handle different screen sizes and that's not what easybake is for, really.

**Comment by philschatz** [comment]
I don't recall the HTML format precisely, but I think it would be nice if the HTML (ie the `<iframe>`) did not have absolute pixel height/width because those values cannot be changed via CSS. But adding an attribute that describes the aspect ratio _would_ be useful. Something like https://getbootstrap.com/components/#responsive-embed .

**Comment by tomjw64** [comment]
@philschatz The width and height values appear to changed as expected with CSS (see image), on the other hand, the original HTML attributes don't go away when you do change it (if thats what you meant).
![mediaCSS](https://cloud.githubusercontent.com/assets/1285308/26684342/4ac205ee-46ac-11e7-876b-8290f41165d3.png)

**Comment by philschatz** [comment]
oh, maybe I was wrong about CSS not being able to override the HTML attributes. Just to be sure, could you write `iframe { width: 50px; height: 50px; } in the CSS panel? (& remove the `style=` attribute)

**Comment by tomjw64** [comment]
I get the same result. Once the CSS is there, it seems as though the attribute does nothing. If both the attributes and CSS are not there, it takes a natural size of 300x150.

**Comment by zroehr** [comment]
@kerwinso this is finally in master and ready for testing

**Comment by kerwinso** [comment]
Verified fix on https://qa.cnx.org/contents/GFy_h8cu@10.115:vogY0C26@20/22-Atoms-Isotopes-Ions-and-Mol (Chrome at 110% zoom, 60% browser width):

![image](https://user-images.githubusercontent.com/11298165/27880717-8e37ad8e-618b-11e7-8145-cf9636185a35.png)
