### ISSUE TITLE
College Biology => Answer Key: solutions are on their own lines

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#211]
In webview, the answers in the Answer Key are on new lines. In the PDF, they are not.

Do we want to update webview to match the PDF Answer Key? (This was not specifically documented in Testy McTestface.)

Webview URL: https://dev.cnx.org/contents/GFy_h8cu@10.61:otIsPXu6@10.61/Answer-Key

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26362477/ae1e5490-3fa3-11e7-8383-d1ecf651c9cc.png)

**Comment by tomjw64** [comment]
In the current form, the solutions can be made to be one the same line (via display: inline; see image below) or different lines based on what the webview styling determines.
![untitled](https://cloud.githubusercontent.com/assets/1285308/26376325/be5d8712-3fd1-11e7-8e2f-bce8578b3cd6.png)

**Comment by kerwinso** [comment]
Need input from @nyxer95 / Editorial

**Comment by nyxer95** [comment]
@kerwinso - I think that the answer key looks better in the PDF so I would prefer that it looks like the PDF. However, if answers have to be different lines that is OK.

**Comment by kerwinso** [comment]
Verified fix on https://dev.cnx.org/contents/GFy_h8cu@10.61:otIsPXu6@10.61/Answer-Key:
 
![image](https://user-images.githubusercontent.com/11298165/27043337-677412fc-4f5f-11e7-9c53-89efa1680866.png)
