### ISSUE TITLE
College Biology => Answer Key in webview displays every answer

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#212]
In webview, every single answer is displayed in the Answer Key. 
In the PDF, only every _other_ answer is displayed, per this change: https://github.com/Connexions/oer.exports/issues/1542. 
(Note that this change affects other books as well, i.e. Psychology, Concepts, US History, Sociology, and A&P).

Do we want to update webview to match the PDF Answer Key? (This was not specifically documented in Testy McTestface.)

Webview URL: https://dev00.cnx.org/contents/GFy_h8cu@10.61:otIsPXu6@10.61/Answer-Key

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26363695/64c7c07a-3fa7-11e7-821b-f6e3375c7141.png)

**Comment by helenemccarron** [comment]
Per Alana: we will use a common rule to remove all even answers in titles that need to be modified. Other books will not be modified.
It is acceptable that the answers suppressed by the ruleset do not match the PDF (e.g. 1, 3, 5 could become 2, 4, 6) but the same number of answers should be preserved. @Stackblocks @kerwinso

**Comment by helenemccarron** [comment]
The fix has been merged already, please use tip of master for testing

**Comment by tomjw64** [comment]
The merged change was in this PR: https://github.com/Connexions/cnx-recipes/pull/238

**Comment by kerwinso** [comment]
Verified fix on `master` at https://dev.cnx.org/contents/GFy_h8cu@10.62:otIsPXu6@10.62/Answer-Key. 

Note that in webview, only the odd-numbered answers display, whereas in the PDF there's a mix of "selected every other" answers (some odd numbered, some even). Per the comment above, this is acceptable, since the total number of answers is the same in webview as in the PDF.

![image](https://user-images.githubusercontent.com/11298165/27197005-4dff7c88-51d2-11e7-9220-9b876f8d587a.png)
