### ISSUE TITLE
College Biology => EOC exercise hyperlinks do not go to their solution

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#213]
1. Go to the Critical Thinking Questions for Chp. 9:  https://dev00.cnx.org/contents/GFy_h8cu@10.61:uLbc9LGo@10.61/Critical-Thinking-Questions

1. Click on any exercise number (e.g., `17`).

This takes you to the top of the Answer Key. However, I would expect that it would take me to the solution for exercise 17. Not sure if this is a bug or an enhancement request.

![image](https://cloud.githubusercontent.com/assets/11298165/26364356/b1688782-3fa9-11e7-8b8d-a700165e932a.png)

**Comment by kerwinso** [comment]
This may be due to the URL hash bug that @edwoodward is currently working on with a CNX intern: https://trello.com/c/HTRKJnP1/131-bug-cannot-link-to-id-in-webview

**Comment by helenemccarron** [comment]
It is! cc @reedstrm, this has been a known issue for quite some time.

**Comment by kerwinso** [comment]
See https://github.com/Connexions/webview/issues/1450

**Comment by kerwinso** [comment]
Addressed in https://github.com/Connexions/webview/pull/1551.

**Comment by kerwinso** [comment]
Still an issue on https://qa.cnx.org/contents/GFy_h8cu@10.115:ChOPx4vW@10.115/Critical-Thinking-Questions, although if you open the link in a new tab it goes (mostly) to the right place. This suggests that the link is coded correctly, but perhaps the back button/browser history bug is interfering with the navigation. See [this related comment](https://github.com/Connexions/cnx-recipes/issues/215#issuecomment-313214276) for more info.

**Comment by kerwinso** [comment]
Technically this works now, but there is still the "in book link reloads page twice" bug that needs to be addressed: https://trello.com/c/ihhMXAOO/68-bug-in-book-links-break-browser-history

**Comment by kerwinso** [comment]
Testing https://github.com/Connexions/webview/pull/1577 and finding that the behavior is still inconsistent. 

If I go to https://qa.cnx.org/contents/GFy_h8cu@10.115:wlbMNDPm@10.115/Critical-Thinking-Questions (the Critical Thinking Questions for chapter 30), and click on question 43, it takes me to the top of the Answer Key rather than the specific solution.

**Comment by kerwinso** [comment]
Verified fix on https://qa.cnx.org/contents/GFy_h8cu@10.115:Kgo-j7Fr@10.115/Critical-Thinking-Questions on `fix-reload` branch, commit `30f6fab` from https://github.com/Connexions/webview/pull/1577. 

The browser title flashes a few times when clicking hash links (due to the code change forcing correct browser history behavior) -- but, the page is not reloading, and the browser history entries are correct. This is the desired behavior. The hash link goes to the correct answer (which is not hidden by the nav header), and the back button in the browser works.
