### ISSUE TITLE
College Biology => Index link in webview does not go to reference

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#215]
1. Go to https://dev00.cnx.org/contents/GFy_h8cu@10.61:OlLnl474@10.61/Index
1. Click on `Accessory fruits`

In my browser (Chrome 58 incognito, OS X El Capitan), clicking the link goes to the top of the page that contains the index term -- but not to the term itself, which is the expected behavior.

Occasionally it does go straight to the right term, or just below it -- the behavior is inconsistent. 

Looks similar to #213.

**Comment by kerwinso** [comment]
This may be due to the URL hash bug that @edwoodward is currently working on with a CNX intern: https://trello.com/c/HTRKJnP1/131-bug-cannot-link-to-id-in-webview

**Comment by caderitter** [comment]
Seems to be working consistently for me - however, the fixed nav bar covers up the term, since the page jumps such that the term appears at the very top of the viewport.

**Comment by kerwinso** [comment]
- Cade is using Chrome on Sierra, non-incognito and cannot reproduce this bug.
- I am on Chrome on El Capitan, incognito mode, and can only reproduce inconsistently. I do believe it is because of the CNX bug I mentioned in [the comment above](https://github.com/Connexions/cnx-rulesets/issues/215#issuecomment-303502234).

RE: the nav bar covering up the term -- this is a UI annoyance that should be addressed. I filed the request here: https://trello.com/c/4GtPLxud/81-webview-scroll-up-in-browser-to-make-index-term-visible
cc @helenemccarron

**Comment by kerwinso** [comment]
Addressed in https://github.com/Connexions/webview/pull/1551.

**Comment by kerwinso** [comment]
URL to Biology Index: https://qa.cnx.org/contents/GFy_h8cu@10.115:OlLnl474@10.115/Index

Very strange. The behavior is still inconsistent for me. Sometimes clicking the index term goes to the correct place (and, it's not covered up by the top nav somehow!) Most of the time, though, it's going to the top of the page. I wonder if it's related at all to the back button bug that Cade is working on? (card here: https://trello.com/c/ihhMXAOO/68-bug-new-baked-pages-are-not-being-added-to-browser-history)

Sending this back to the developers. cc @tomjlw @caderitter

**Comment by kerwinso** [comment]
Technically this works now, but there is still the "in book link reloads page twice" bug that needs to be addressed: https://trello.com/c/ihhMXAOO/68-bug-in-book-links-break-browser-history

**Comment by kerwinso** [comment]
Verified on https://qa.cnx.org/contents/GFy_h8cu@10.115:OlLnl474@10.115/Index. 
Fixed by Zach's PR, https://github.com/Connexions/webview/pull/1577. That PR also fixes the bug where the top nav bar covers up the term.
