### ISSUE TITLE
College Biology => Scientific Connection feature should be Scientific Method Connection

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#218]
The feature 'Scientific Connection' should be re-titled 'Scientific Method Connection' to match the PDF.

Webview URL (Ch. 6.3): https://dev00.cnx.org/contents/GFy_h8cu@10.61:HZOoT9Pk@7/63-The-Laws-of-Thermodynamics

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26457372/7c4e0152-4135-11e7-9547-e4f42c7779b8.png)

**Comment by kerwinso** [comment]
Weirdly, this does not seem to affect all Scientific Method Connection features. This one looks correct ([Ch. 10.2](https://dev00.cnx.org/contents/GFy_h8cu@10.61:1tJ55Ot6@7/102-The-Cell-Cycle)):

![image](https://cloud.githubusercontent.com/assets/11298165/26470194/7477305c-4162-11e7-9ec9-3105299f1baa.png)

**Comment by tomjw64** [comment]
Should be addressed in PR #229

**Comment by kerwinso** [comment]
Verified fix on https://dev.cnx.org/contents/GFy_h8cu@10.61:yNlSxj0E@6/192-Population-Genetics:

![image](https://cloud.githubusercontent.com/assets/11298165/26797160/9387c578-49f1-11e7-9ccc-57850947cb3a.png)
