### ISSUE TITLE
College Biology => Everyday Connection feature says "Everyday Connection" twice

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#219]
Similar to #201. In webview, the Everyday Connection feature has a title "Everyday Connection", and also a subtitle "Everyday Connection", in addition to the actual subtitle. 

Webview URL: 
https://dev00.cnx.org/contents/GFy_h8cu@10.61:MnC6GuJi@7/65-Enzymes

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26457705/bbf94bee-4136-11e7-89cf-f7d06966959f.png)

**Comment by tomjw64** [comment]
Addressed in PR #229

**Comment by kerwinso** [comment]
Verified fix on https://dev.cnx.org/contents/GFy_h8cu@10.61:MnC6GuJi@7/65-Enzymes:

![image](https://cloud.githubusercontent.com/assets/11298165/26792046/b620dfe2-49de-11e7-92c6-67d17f10d6d6.png)
