### ISSUE TITLE
Multiple books => Appendix tables missing table numbers

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#220]
The table in Appendix C is missing the number for the table (`Table C1`).

Webview URL: 
https://dev00.cnx.org/contents/GFy_h8cu@10.61:-p-m85Qc@4/Appendix-C-Measurements-and-th

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26458013/bc796e4a-4137-11e7-800b-36693b024afa.png)

**Comment by kerwinso** [comment]
Also an issue in AP Physics:
https://dev.cnx.org/contents/jQSmhtXo@14.5:qvMKVKNW@5/Appendix-A-Atomic-Masses

![image](https://cloud.githubusercontent.com/assets/11298165/26736194/a721cb1a-478a-11e7-8e10-0fd7791750e2.png)

**Comment by kerwinso** [comment]
In AP Physics, this is really a problem in Appendix C which contains multiple tables and a makeshift table of contents linking to each table: https://dev.cnx.org/contents/jQSmhtXo@14.5:cjQyhWg-@7/Appendix-C-Useful-Information#import-auto-id1374373

In webview, the link for every table says `Exercise 34.31`. Compare that to the PDF on the right in this screenshot.

![image](https://cloud.githubusercontent.com/assets/11298165/26789898/6a8180f2-49d7-11e7-9d9d-7134f112eb6e.png)

**Comment by kerwinso** [comment]
List of affected books, each will be checked off when it passes QA:

- [ ]  College Biology
- [ ]  AP Physics

**Comment by tomjw64** [comment]
Addressed in PR #237

**Comment by tomjw64** [comment]
@kerwinso The output rulesets containing the fix can be found here: https://github.com/Connexions/cnx-recipes/tree/appendix-fix/rulesets/output

**Comment by kerwinso** [comment]
Verified fix in [College Biology](https://dev.cnx.org/contents/GFy_h8cu@10.61:-p-m85Qc@4/Appendix-C-Measurements-and-th):

![image](https://user-images.githubusercontent.com/11298165/27092960-b735ceb8-502a-11e7-99d6-1051fba9aef3.png)

**Comment by kerwinso** [comment]
Verified fix in [AP Physics](https://dev.cnx.org/contents/jQSmhtXo@14.5:qvMKVKNW@5/Appendix-A-Atomic-Masses):

![image](https://user-images.githubusercontent.com/11298165/27096933-3e876e14-5038-11e7-9f64-118e70ab75e9.png)

For the Appendix C weirdness in AP Physics, this has been copied into a separate issue. Refer to https://github.com/Connexions/cnx-recipes/issues/242.

**Comment by kerwinso** [comment]
Just noticed this on College Physics, need to rebake and test.

**Comment by kerwinso** [comment]
Verified on College Physics, looks the same as AP Physics.
