### ISSUE TITLE
College Biology => Appendix figures missing figure numbers

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#221]
The figures in the appendices are missing the numbers (`Figure B1`, `Figure B2` etc).

Webview URL: 
https://dev00.cnx.org/contents/GFy_h8cu@10.61:rr1s_Dnm@4/Appendix-B-Geological-Time

Webview on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26458238/49819920-4138-11e7-9a45-cd8f158d2e60.png)

**Comment by tomjw64** [comment]
Please only note the second commit that referenced this issue. The first commit is the same changes, but the commit message is in error.

**Comment by tomjw64** [comment]
Addressed in PR #237

**Comment by tomjw64** [comment]
@kerwinso The output rulesets containing the fix can be found here: https://github.com/Connexions/cnx-recipes/tree/appendix-fix/rulesets/output

**Comment by kerwinso** [comment]
Verified fix on https://dev.cnx.org/contents/GFy_h8cu@10.61:hYdhUM0j@6/Appendix-A-The-Periodic-Table-. Whoomp, there they are:

![image](https://user-images.githubusercontent.com/11298165/27092784-251d7a9e-502a-11e7-8cf2-92f8ceaa04d3.png)

![image](https://user-images.githubusercontent.com/11298165/27092787-295a60e0-502a-11e7-8eea-886fe8c36f9b.png)
