### ISSUE TITLE
College Biology => Footnote number on its own line

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#223]
In Chp. 9.4 '[Signaling in Single-Celled Organisms](https://dev00.cnx.org/contents/GFy_h8cu@10.61:Gj6xeWoG@7/94-Signaling-in-Single-Celled-#footnote1)', the footnote number is on its own line, with the citation beneath it.

In other chapters (such as [this one, Chp. 2.2](https://dev00.cnx.org/contents/GFy_h8cu@10.61:pPjfgsd4@10/22-Water#footnote2)), the footnotes are inline with their citations.

Seems like they should be consistent. IMHO the inline alignment looks better.

![image](https://cloud.githubusercontent.com/assets/11298165/26469506/d40d649e-415f-11e7-875a-dda1e90793ba.png)

**Comment by kerwinso** [comment]
Also occurs in Ch. 11.1:
![image](https://cloud.githubusercontent.com/assets/11298165/26498646/5bf2b1bc-41f5-11e7-9c82-2e8717235984.png)

**Comment by kerwinso** [comment]
Actually this may be a content bug. The instances where this bug occurs in webview also occur in the PDF. 

Here's an example from Ch. 11.1. In both the webview and the PDF, the footnote numbers are on their own lines.

![image](https://cloud.githubusercontent.com/assets/11298165/26501039/eed751e2-41fd-11e7-9e68-7aff61532103.png)

**Comment by tomjw64** [comment]
Footnotes with line breaks:
![footnotes w/line breaks](https://cloud.githubusercontent.com/assets/1285308/26502859/12937a74-4204-11e7-9f47-616381f443ee.png)

Footnotes without:
![footnotes without](https://cloud.githubusercontent.com/assets/1285308/26503036/c974d9f4-4204-11e7-84e7-923b9062238d.png)

We _should_ be able to fix this via ruleset

**Comment by kerwinso** [comment]
It's probably OK to attempt a fix by ruleset, but the origin of the issue appears to be in content that. So ideally that content would be updated to be consistent, in this book and wherever else it appears.
 
@helenemccarron: perhaps you could discuss this with Alina, or we could park it sometime? (Choose your scrum :P)

**Comment by kerwinso** [comment]
It's probably OK to attempt a fix by ruleset, but the origin of the issue appears to be in content that. So ideally that content would be updated to be consistent, in this book and wherever else it appears.
 
@helenemccarron: perhaps you could discuss this with Alina, or we could park it sometime? (Choose your scrum :P)

**Comment by openstaxalina** [comment]
@kerwinso I don't seem to be able to edit this issue because it's in cnx-rulesets.  This should be assigned to Bey, the lead CM on _Biology_, to try to figure out why this is happening in the content.  Is it possible to change the repo and/or copy the issue in our repo so it can be tracked accordingly?

As a worst case, I can report this as book errata.  Just let me know!

**Comment by kerwinso** [comment]
Copied this issue into https://github.com/Connexions/oer.exports/issues/2794.
Closing since this is now a content team task.
