### ISSUE TITLE
College Biology => Bullet metadata exposed in table

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#224]
Webview URL (Chrome 58 incognito, OS X El Capitan):
https://dev00.cnx.org/contents/GFy_h8cu@10.61:x4Wo0QTK@7/121-Mendels-Experiments-and-th

In table 12.1, under the column `F2 Offspring Traits` displays:
`[data-bullet-style=CUSTOM NOT_IMPLEMENTED-YET]`

Also, in the PDF, this content does not appear to be bulleted.

Webview on left, PDF on right:
![image](https://cloud.githubusercontent.com/assets/11298165/26499239/7bd27f56-41f7-11e7-9030-8ef7c158207b.png)

**Comment by caderitter** [comment]
This was evidently already covered, it's a type issue in content: https://trello.com/c/kf6D9lKE/119-html-transform-bug-lists-in-tables

**Comment by kerwinso** [comment]
This might be due to outdated content. On production, in the newer version, this has been fixed (see the table `Results of Mendel’s Garden Pea Hybridizations`):
https://cnx.org/contents/GFy_h8cu@10.100:x4Wo0QTK@8/Mendels-Experiments-and-the-La

**Comment by helenemccarron** [comment]
see https://trello.com/c/kf6D9lKE/119-html-transform-bug-lists-in-tables for full description

**Comment by kerwinso** [comment]
@helenemccarron How do we get updated data to test this on dev?

**Comment by kerwinso** [comment]
Copied content over from production and verified this is fixed on dev:
https://dev.cnx.org/contents/GFy_h8cu@10.62:x4Wo0QTK@8/Mendels-Experiments-and-the-La

![image](https://user-images.githubusercontent.com/11298165/27098579-ab62e202-503d-11e7-9d41-6ca299e23bb3.png)
