### ISSUE TITLE
Economics => Extra space after review/crit-think question number

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#226]
# Scenario

There is an extra space following the number in Review and Critical Thinking Questions.

# Reproducibility Details

* **Impact area**: Content
*  **User**: n/a
*  **URL / Location**: https://dev00.cnx.org/contents/aWGdK2jw@11.332:QiH_J3Tm@11.332/Review-Questions
* **How many times were you able to reproduce the issue?** n/a

*  **Steps to reproduce**:

n/a

* **Images or screenshots Included:** Yes  (_attach below_)
![image](https://cloud.githubusercontent.com/assets/12678235/26601902/4b2b8dcc-4547-11e7-914b-22292cbee3e8.png)

# Environment:

* **Instance**: Dev00
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: Medium
* **Frequency of occurrence**: Common

**Comment by caderitter** [comment]
This is a webview issue - there is padding on os-number below that causes the problem.

/webview/src/scripts/modules/media/body/

`.os-figure {
  display: table;
  margin: 1rem auto 0;
  .os-caption-container {
    padding-top: 1rem;
    display: table-caption;
    caption-side: bottom;
    font-size: 1.2rem;
    color: @gray;
    .os-title-label {
      font-weight: bold;
    }
    .os-number {
      font-weight: bold;
      padding-right: .5rem;
    }
  }`

**Comment by zroehr** [comment]
@Stackblocks @kerwinso ready for testing

**Comment by Stackblocks** [comment]
Fixed in Self-Check questions, Review Questions sections still have this issue after re-bake using using ruleset from `master`.

![image](https://user-images.githubusercontent.com/12678235/27293594-8330ec04-54dc-11e7-9c07-52fe18cb7118.png)

![image](https://user-images.githubusercontent.com/12678235/27293610-8d3ddbee-54dc-11e7-85bf-8e5c823eb02a.png)

**Comment by Stackblocks** [comment]
Looking good on QA.

![image](https://user-images.githubusercontent.com/12678235/27871526-81be8b74-616b-11e7-8957-4e3d8b875749.png)
