### ISSUE TITLE
TEG => Spacing issues

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#228]
# Scenario

There is no break between an imge caption and the following paragraph, and there is a large gap following the learning objectives at the top of the chapter. 

This is to be discussed during the meeting on 2017-05-31

# Reproducibility Details

* **Impact area**: Content
*  **User**: Alan
*  **URL / Location**: https://stg.texasgateway.org/resource/11-science-biology
* **How many times were you able to reproduce the issue?** n/a

*  **Steps to reproduce**:

n/a

* **Images or screenshots Included:** Yes  (_attach below_)
![image](https://cloud.githubusercontent.com/assets/12678235/26638973/2fc5f6ec-45e9-11e7-80f5-209d97aed927.png)
![image](https://cloud.githubusercontent.com/assets/12678235/26638992/3b80136e-45e9-11e7-9d70-86ac2dce58fd.png)

# Environment:

* **Instance**: Other: 
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

**Comment by Stackblocks** [comment]
Update:
1. Whitespace following Learning Objectives is by design. Will be left in unless TEA says otherwise.
2. TEG will take care of the issue with no spacing after captions in text.

**Comment by chcase** [comment]
Hi - Theming has been updated for issue #2 above on staging. 

Please confirm:  https://stg.texasgateway.org/resource/11-science-biology
