### ISSUE TITLE
AP Physics => Check Your Understanding feature says "Check Your Understanding" twice

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#232]
In AP Physics, the Check Your Understanding feature says "Check Your Understanding" twice.

URL: https://dev.cnx.org/contents/jQSmhtXo@14.5:L4pdOADV@2/11-Physics-An-Introduction#fs-id1165298745067

![image](https://cloud.githubusercontent.com/assets/11298165/26732182/50c0c73e-477c-11e7-97df-61f00aaab41b.png)

**Comment by tomjw64** [comment]
Addressed in PR #239

**Comment by tomjw64** [comment]
@kerwinso The output containing the fix can be found here: https://github.com/Connexions/cnx-recipes/tree/physics-dupl-note/rulesets/output

**Comment by kerwinso** [comment]
Verified fix on `master` branch:

![image](https://user-images.githubusercontent.com/11298165/27190302-a61c9860-51b9-11e7-87cd-7f9e168f684d.png)
