### ISSUE TITLE
College Biology => Video embed contains entire webpage

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#241]
# Scenario

In College Biology, there is a embed of a YouTube video that instead of embedding the video itself, embeds an iframe containing the entire page of the YouTube video, title, likes, comments and all.

Additionally, the iframe doesn't even show up on webview.

The source of the issue is that the iframe link https://www.openstaxcollege.org/l/boyles_law takes you to a full YouTube page. A normal embedded video would take you to a special embed page (e.g. https://www.openstaxcollege.org/l/boyle_breathing)

Not sure who can fix a bad link in content.

# Reproducibility Details

- **Impact area**: Section 39.3 Breathing in College Biology
- **User**: Thomas?
- **URL / Location**: tea.cnx.org, College Biology, uuid: 185cbf87-c72e-48f5-b51e-f14f21b5eabd, or https://tea.cnx.org/contents/GFy_h8cu@10.61:E4i-YQIZ@6/393-Breathing
- **How many times were you able to reproduce the issue?**: Too many

## Steps to reproduce:

- Open local biology-raw or biology-baked xhtml on browser
- Wait for the page to fully load on your browser and you will be automatically scrolled to the iframe's position in the document, because the video autoplays once the page loads (because the video itself isn't embedded)

## Screenshots

![Ex1](https://user-images.githubusercontent.com/1285308/27096045-64801542-5035-11e7-951e-40d254ea0bcc.png)

![Ex2](https://user-images.githubusercontent.com/1285308/27095963-2acb3138-5035-11e7-86a3-73d133aa2063.png)

On WebView:

![ex1webview](https://user-images.githubusercontent.com/1285308/27096714-92edbb26-5037-11e7-82e1-3bb24918a8a1.png)

# Environment:

- **OS**: Windows 10
- **Browser**:  Chrome

# Impact

- **Severity**: Really annoying for Thomas and Helene because there is an auto-playing video, but I guess not super terrible.
- **Frequency of occurrence**: Every time I open biology.

**Comment by kerwinso** [comment]
Maybe this would be addressed by a content fix? Seems related to this issue: https://github.com/Connexions/cnx-recipes/issues/202

**Comment by kerwinso** [comment]
This was supposed to have been addressed by an errata fix (https://openstax.org/errata/3241), but looks like it was not: https://cnx.org/contents/GFy_h8cu@10.114:E4i-YQIZ@6/Breathing

Need to consult with Alina.

**Comment by kerwinso** [comment]
@tomjw64 What is the reason you were working in College Bio on the TEA server? TEA only does high school books, and for assignable webview we are currently testing College Bio on dev.cnx.org, not on tea.cnx.org.

**Comment by tomjw64** [comment]
@kerwinso  I've just confirmed that it is still and issue on dev.cnx. The reason that it appears to be fixed on cnx.org is because it was removed altogether? Perhaps that was the only solution...

**Comment by kerwinso** [comment]
@tomjw64 Try dev.cnx again, I just updated the content on https://dev.cnx.org/contents/GFy_h8cu@10.63:E4i-YQIZ@7/Breathing. If this issue is resolved, feel free to close it.

**Comment by tomjw64** [comment]
The embedded link has been deleted and the issue is resolved. Thanks Kerwin!
