### ISSUE TITLE
Multiple books => Extra period in appendix table numbers

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#247]
EDIT: this actually affects more books than initially thought, but originally spotted in AP Physics.

Inside the AP Physics appendices, the table numbers have an extra period that should be removed, i.e. the table number should be `Table A1`, not `Table A.1`, in order to match the PDF. 

https://dev.cnx.org/contents/jQSmhtXo@14.5:cjQyhWg-@7/Appendix-C-Useful-Information

![image](https://user-images.githubusercontent.com/11298165/27239874-5803cf74-5298-11e7-8a21-e0fb7db1c767.png)

**Comment by kerwinso** [comment]
Here it is in [Principles of Economics](https://dev.cnx.org/contents/aWGdK2jw@11.332:Nihva8h5@11/Appendix-A-The-Use-of-Mathemat):

![image](https://user-images.githubusercontent.com/11298165/27241788-d34ecac4-529f-11e7-9463-e2ae40339c87.png)

**Comment by kerwinso** [comment]
Checklist for QA:

- [ ] TEA AP Bio
- [ ] TEA AP Physics
- [ ] TEA Econ
- [ ] TEA HS Physics
- [ ] TEA Statistics
- [ ] AP Bio?
- [ ] [AP Physics](https://dev.cnx.org/contents/jQSmhtXo@14.5:cjQyhWg-@7/Appendix-C-Useful-Information)
- [ ] [College Biology](https://dev.cnx.org/contents/GFy_h8cu@10.62:-p-m85Qc@4/Appendix-C-Measurements-and-th) 
- [ ] [Econ](https://dev.cnx.org/contents/aWGdK2jw@11.332:Nihva8h5@11/Appendix-A-The-Use-of-Mathemat)
- [ ] [College Physics](https://dev.cnx.org/contents/Ax2o07Ul@9.44:qvMKVKNW@5/Appendix-A-Atomic-Masses)
- [ ] [Statistics](https://dev.cnx.org/contents/MBiUQmmY@18.13:PvgwvFJH@5/Appendix-B-Data-Sets)

**Comment by kerwinso** [comment]
@caderitter AP Physics not quite fixed (see https://dev.cnx.org/contents/jQSmhtXo@14.5:cjQyhWg-@7/Appendix-C-Useful-Information#import-auto-id1211982):

![image](https://user-images.githubusercontent.com/11298165/27293769-fb8ee534-54dc-11e7-9160-addf6ce6503b.png)

**Comment by Stackblocks** [comment]
Showing as resolved for all applicable books. Closing!
