### ISSUE TITLE
Incorrect titles appearing in raw

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#25]
There are incorrect titles that appear in the Statistics raw HTML file. Most match the PDF, but a few are different. Shall we override them with the rulesets or change them at an earlier stage of the process?

**Comment by tomjw64** [comment]
All collaborative exercise titles appear like this in the PDF (and in most cases in the raw HTML):

<img width="1242" alt="screen shot 2016-06-01 at 3 16 20 pm" src="https://cloud.githubusercontent.com/assets/1285308/15724241/d653962e-280b-11e6-96ab-e8bb644cf504.png">

**Comment by mjbuchholz** [comment]
<img width="972" alt="screen shot 2016-06-01 at 3 17 02 pm" src="https://cloud.githubusercontent.com/assets/19391481/15724420/9c08a544-280c-11e6-981b-3776dc819e55.png">
<img width="1220" alt="screen shot 2016-06-01 at 3 18 00 pm" src="https://cloud.githubusercontent.com/assets/19391481/15724428/a2c1f002-280c-11e6-991e-0083db6a94e4.png">
<img width="1263" alt="screen shot 2016-06-01 at 3 19 03 pm" src="https://cloud.githubusercontent.com/assets/19391481/15724433/a80f417c-280c-11e6-904f-c5d478ad4345.png">
<img width="1252" alt="screen shot 2016-06-01 at 3 19 43 pm" src="https://cloud.githubusercontent.com/assets/19391481/15724446/ade07b48-280c-11e6-8911-e898a789c565.png">
<img width="1246" alt="screen shot 2016-06-01 at 3 20 15 pm" src="https://cloud.githubusercontent.com/assets/19391481/15724450/b34e20b2-280c-11e6-9103-757e04f2f339.png">

**Comment by tomjw64** [comment]
Additionally, there are sections that have a calculator title image, like so:

<img width="544" alt="screen shot 2016-06-01 at 3 31 30 pm" src="https://cloud.githubusercontent.com/assets/1285308/15724710/f49ed9fc-280d-11e6-923a-cb1c86f19d4c.png">

These sections appear with no title in the raw file, or are incorrectly labeled like collaborative exercises.
