### ISSUE TITLE
TEA - HS Physics and AP Bio Teacher Support

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#250]
# Scenario

TEA does not want to see Teacher Support content. We need to remove them in the recipes

# Reproducibility Details

- **Impact area**: Gateway
- **User**: TEA
- **URL / Location**: Gateway/epub
- **How many times were you able to reproduce the issue?** : all the time

## Steps to reproduce:

- Load the page

## Screenshots

N/A, HS physics isn't in the Gateway at the moment. One way to see it is open the epub, Webview hides it.

# Environment:

- **Instance**: doesn't matter
- **OS**: doesn't matter
- **Browser**: doesn't matter

# Impact

- **Severity**: high
- **Frequency of occurrence**: all the time

**Comment by tomjw64** [comment]
Addressed in PR #252
