### ISSUE TITLE
Multiple books => extra period in appendix figure numbers

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#251]
Example from Principles of Economics on dev.cnx.org:

Webview on the left, PDF on the right:
![image](https://user-images.githubusercontent.com/11298165/27294103-03d378e4-54de-11e7-8b22-522523c919fa.png)

**Comment by kerwinso** [comment]
Checklist for QA (Alan will test TEA books, Kerwin will test the others):

- [ ] TEA AP Bio
- [ ] TEA AP Physics
- [ ] TEA Econ
- [ ] TEA HS Physics
- [ ] TEA Statistics
- [ ] [AP Physics](https://dev.cnx.org/contents/jQSmhtXo@14.5:cjQyhWg-@7/Appendix-C-Useful-Information) 
- [ ] [College Biology](https://dev.cnx.org/contents/GFy_h8cu@10.62:-p-m85Qc@4/Appendix-C-Measurements-and-th) (this wasn't broken, but needs regression test)
- [ ] [Econ](https://dev.cnx.org/contents/aWGdK2jw@11.332:Nihva8h5@11/Appendix-A-The-Use-of-Mathemat)
- [ ] [College Physics](https://dev.cnx.org/contents/Ax2o07Ul@9.44:qvMKVKNW@5/Appendix-A-Atomic-Masses)
- [ ] [Statistics](https://dev.cnx.org/contents/MBiUQmmY@18.13:PvgwvFJH@5/Appendix-B-Data-Sets)

Branch to test: `appendix-number-fix`

**Comment by Stackblocks** [comment]
Showing as resolved for all applicable books. Closing!
