### ISSUE TITLE
Economics => Appendix title too long (doesn't match PDF)

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#260]
I think this is low-priority, but filing it anyway.  In Econ, the appendix titles don't match the PDF (or Testy McTestface). They include the name of the appendix, whereas in the PDF they don't.

Webview says: `Appendix C Present Discounted Value`
PDF just says: `Appendix C`

URL: https://dev.cnx.org/contents/aWGdK2jw@11.333:EOodLrFw/Appendix-C-Present-Discounted-

Screenshot:
![image](https://user-images.githubusercontent.com/11298165/27391174-d3f92f24-5668-11e7-9a8a-2657a4327818.png)

**Comment by helenemccarron** [comment]
@openstaxalina or maybe (or maybe @nyxer95 ), it seems to me that keeping the title value is preferable.
Should we discard the title if there is one to match the PDF or keep it?

**Comment by openstaxalina** [comment]
@helenemccarron I agree, it is preferable to have the title on the PDF (in addition to web view) because that is more valuable info than just "Appendix [letter]".  

I thought we were structuring the appendix titles with horizontal bars like this:

A l [title]
B l [title]

Is there a way to style both web view and PDF so there is the appendix letter, vertical bar, and title?

We can discuss in scrum, as well.

**Comment by helenemccarron** [comment]
Yes, we will add the `|` in the recipes, it will display both in the PDF and Webview (and everywhere else).

**Comment by kerwinso** [comment]
@helenemccarron @openstaxalina So to clarify: for all the Economics books, in both webview and PDF, the Appendix titles will look like this: `Appendix C | Present Discounted Value`?

**Comment by openstaxalina** [comment]
I am not sure whether it says "Appendix C" (for example) or just "C".  I plan to park this in scrum this week.  Unless anyone knows for sure?

**Comment by openstaxalina** [comment]
Decision: we will style appendices as "[letter] | [title]", for example: "C | Present Discounted Values".

This applies to every book.

**Comment by tomjw64** [comment]
Addressed in PR #261

**Comment by kerwinso** [comment]
Verified fix on https://dev.cnx.org/contents/aWGdK2jw@11.333:EOodLrFw@6/C--Present-Discounted-Value -- it now says `C | Present Discounted Value` in both the left nav link and the page title:

![image](https://user-images.githubusercontent.com/11298165/27494844-3d4c88b0-5815-11e7-8e07-2f8459b2fc8f.png)
