### ISSUE TITLE
University Physics => In book search removes table and figure numbering

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#270]
# Scenario

When searching in the newly baked University Physics book, the search results strip the content of table and figure numbering. Note that this doesn't appear to be happening in other baked books (such as Introductory Statistics).

# Reproducibility Details

- **Impact area**: search
- **User**: all (not logged in)
- **URL / Location**: https://dev.cnx.org/contents/1Q9uMg_a@5.13:Gofkr9Oy@6/Preface
- **How many times were you able to reproduce the issue?** Every time in University Physics

## Steps to reproduce:

- Go to University Physics: https://dev.cnx.org/contents/1Q9uMg_a@5.13:Gofkr9Oy@6/Preface
- Search in the book for `table`
- Click the results for module `1.2 Units and Standards`

If you look at the tables and figures in the content on the right, they now are missing numbers. Also the links that refer to tables and figures are also missing numbers.

## Screenshots

Search view on left, non-search view on right:
![image](https://user-images.githubusercontent.com/11298165/27548692-4ac9a80a-5a5f-11e7-81fb-b8ee7970038a.png)

![image](https://user-images.githubusercontent.com/11298165/27548707-58e2f3f6-5a5f-11e7-87c9-27f4f3ab9449.png)

# Environment:

- **Instance**: dev.cnx.org
- **OS**: OSX El Capitan
- **Browser**: Chrome 58, non-incognito

# Impact

- **Severity**: 
- **Frequency of occurrence**: all the time

**Comment by helenemccarron** [comment]
It looks like the results display the raw version and not the baked version (even if the `nav` displays baked data).

**Comment by kerwinso** [comment]
Ross sez: try to rebake this.

**Comment by kerwinso** [comment]
@reedstrm @helenemccarron I tried rebaking this on several different branches, most recently `master`, and this problem is still occurring. Do you have any suggestions?

**Comment by reedstrm** [comment]
Now that we've got qa.cnx.org working. could you verify that it happens there as well?

**Comment by kerwinso** [comment]
No longer on issue on qa.cnx.org:

![image](https://user-images.githubusercontent.com/11298165/27879432-3bc18e48-6187-11e7-8564-d68418118410.png)
