### ISSUE TITLE
University Physics => 'Note: Interactive' should be titled 'Interactive'

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#272]
Univ. Phys. vol 1, Chp 1.2 URL: https://dev.cnx.org/contents/1Q9uMg_a@5.13:eEWK1Haa@5/12-Units-and-Standards

The note for Interactive features should be titled `Interactive` -- not `Note: Interactive`.

EDIT: this applies to all Notes, such as 'Note: Problem-Solving Strategy: Rotational Dynamics' in Ch. 10.7.

![image](https://user-images.githubusercontent.com/11298165/27555346-13e1c2ec-5a77-11e7-8950-20b6741b6c6f.png)

**Comment by tomjw64** [comment]
The `Note:` part of the title is from a `::before` in webview styling.

**Comment by zroehr** [comment]
This has been fixed in PR https://github.com/Connexions/webview/pull/1559

**Comment by kerwinso** [comment]
Next steps for testing:

- [ ] PR https://github.com/Connexions/webview/pull/1559 code review approved
- [ ] Get baking fixed on qa.cnx.org ([Trello card](https://trello.com/c/qDzwVAkU/24-fix-ruleset-baking-on-qacnxorg))
- [ ] Deploy PR to webview repo qa.cnx.org
- [ ] Test

**Comment by kerwinso** [comment]
Verified fix on qa.cnx.org for all notes including 'Interactive' and 'Problem-Solving Strategy'. Other features such as Examples, equation callouts, and 'Check Your Understanding' look fine too.

![image](https://user-images.githubusercontent.com/11298165/27878520-20d74bac-6184-11e7-95a5-9850a949cb10.png)

![image](https://user-images.githubusercontent.com/11298165/27878527-24bc1c3e-6184-11e7-8d74-9571fa563397.png)

**Comment by kerwinso** [comment]
This is occurring again on qa.cnx.org. See https://qa.cnx.org/contents/1Q9uMg_a@5.22:eEWK1Haa@5/12-Units-and-Standards

And for the 'Note: Problem-Solving Strategy' regression, see https://qa.cnx.org/contents/1Q9uMg_a@5.22:JXOmS3vN@3/108-Newtons-Second-Law-for-Rot

**Comment by kerwinso** [comment]
keep an eye on this one after switching qa.cnx.org back to master

**Comment by kerwinso** [comment]
This is fixed, will test again during regression testing phase. The test case is specific to University Physics and is here:
https://openstax.testrail.net/index.php?/cases/view/132554&group_by=cases:section_id&group_id=7804&group_order=asc
