### ISSUE TITLE
TEG => Mis-matched prefaces

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#276]
# Scenario

On TEG, if you are in the Statistics book, if you click on an appendix page, the book you are in becomes AP Physics. The top navigation then correctly contains all chapters of AP Physics, but maintains the appendices of Statistics. Additionally the appendices in the book AP Physics are not those for AP Physics, they are the appendices for Statistics.

In short, it looks like our Statistics appendices got attached to AP Physics somehow, and ANY links to those appendices take you to where those appendices are located in the AP Physics book.

Additionally, this means that the **real** AP Physics appendices are nowhere to be found.

**Update**: Helene notes that this issue occurs in **_all_** books. Every book in TEG uses our statistics appendices rather than their own. If you click on any of them, then you are brought to the AP Physics book.

## Steps to reproduce:

1. Go to the Statistics book on TEG. Use the navigation to access any appendix page, say, `Appendix A Review Exercises (Ch 3-13)`
2. Notice that the book in the upper left now reads TEAapphysics
3. Click TEAapphysics to navigate the book and notice that the chapters of TEAapphysics appear, but so do the appendices of statistics.

Note: It appears that if you also access TEAapphysics directly, the statistics appendices are listed under it. No need to follow links, even though it's more fun to watch the magic happen.

## Screenshots
![teastatistics](https://user-images.githubusercontent.com/1285308/27646651-c5e8c580-5bee-11e7-87cf-9e486c738bf3.png)
![teaapphysics](https://user-images.githubusercontent.com/1285308/27646656-c957fc04-5bee-11e7-8271-83788f55d33f.png)
![teaproblems](https://user-images.githubusercontent.com/1285308/27646661-cc6140f4-5bee-11e7-8e78-a04378628a74.png)

# Environment:

- **Instance**: ?
- **OS**: Windows 10
- **Browser**:  Chrome

# Impact

- **Severity**: idk
- **Frequency of occurrence**: always

**Comment by tomjw64** [comment]
UPDATE: Due to the current state of the uploaded books, it is now the case that the Biology sample preface is in every book and the macroeconomics appendices are in every book (when accessed through the Book Outline and the Table of Contents dropdown)

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/29478876-d0e3db64-8434-11e7-99ea-50c87a80a593.png)

Still present as of 2017-08-18. Appendices appear to be working correctly, but currently:
- AP Bio does not have a preface on the Table of Contents page, in the book's drop-down it gives the error `The requested page "/node/215366?book=280771" could not be found.`
-AP Microecon is being re-loaded and cannot be tested currently.
- HS Statistics loads the AP Bio preface
- HS Physics does not have a preface
- AP Macroecon loads the correct preface
- AP Physics 1 loads the correct preface
- AP Physics 2 loads the correct preface
![image](https://user-images.githubusercontent.com/12678235/29479248-abe3f68a-8436-11e7-8fc5-f2b64ade09d0.png)

**Comment by Stackblocks** [comment]
Appears resolved on staging as of 2017-09-12
