### ISSUE TITLE
TEG => Pre-Learning Objectives content missing from AP Physics

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#277]
# Scenario

Pre Learning Objective content is missing from AP Physics and that throws off figure numbering.

# Reproducibility Details

- **Impact area**: TEG AP Physics
- **User**: Openstax@texasgateway.org
- **URL / Location**: https://stg.texasgateway.org/resource/connection-ap%C2%AE-courses

## Screenshots
1. Pre Learning Objective content is missing. 
![image](https://user-images.githubusercontent.com/12678235/27647371-dcfe6476-5bf0-11e7-9445-5df9345c33ab.png)

2. Numbering is thrown off due to missing content. 
![image](https://user-images.githubusercontent.com/12678235/27647503-371861c8-5bf1-11e7-89f7-f69e652095c8.png)

# Environment:

- **Instance**: Gateway Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by tomjw64** [comment]
Addressed in PR #297

**Comment by openstaxalina** [comment]
Issue moved to [openstax/tea-teg #1](https://github.com/openstax/tea-teg/issues/1) via [**ZenHub**](https://www.zenhub.com/)
