### ISSUE TITLE
University Physics => Index missing letter 'A' header

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#278]
URL: https://dev.cnx.org/contents/1Q9uMg_a@5.13:cqPvIeML@5.13/Index

The header for index terms starting with the letter 'A' is missing. Note that this index does not seem to have index terms that start with a symbol. Does the ruleset require terms with symbols to be present in order for the `A` to display?

![image](https://user-images.githubusercontent.com/11298165/27648122-22beb536-5bf3-11e7-82db-e8329eaa9f68.png)

**Comment by tomjw64** [comment]
Addressed in PR #281

**Comment by kerwinso** [comment]
Verified fix on https://qa.cnx.org/contents/1Q9uMg_a@5.22:cqPvIeML@5.22/Index after rebaking on `index-symbol` branch.

![image](https://user-images.githubusercontent.com/11298165/27919020-35b48c30-6236-11e7-99cc-18856ca22d69.png)
