### ISSUE TITLE
TEG => Styling issues in AP Physics

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#279]
# Scenario

An overview of styling issues in AP Physics. Can be broken into individual issues as needed.

# Reproducibility Details

- **Impact area**: TEG AP Physics
- **User**: Openstax@texasgateway.org
- **URL / Location**: https://stg.texasgateway.org/resource/connection-ap%C2%AE-courses

## Screenshots
- `Note` type features are unstyled and indistinguishable from body copy.
![image](https://user-images.githubusercontent.com/12678235/27648919-c1816cc0-5bf5-11e7-84ef-a3866a5e0bd6.png)

- No delineation between Check your Understanding problems and solutions.
![image](https://user-images.githubusercontent.com/12678235/27648902-b751661a-5bf5-11e7-8a56-0fe6f33efc6c.png)

- Content gets jumbled when window descends below a certain size.
![image](https://user-images.githubusercontent.com/12678235/27648893-b023388c-5bf5-11e7-8faa-880ea51a2727.png)

# Environment:

- **Instance**: Gateway Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by chcase** [comment]
Sorry just seeing this.  (Guess my jira integration isn't working)   We are taking a look at the items noted

**Comment by Stackblocks** [comment]
Issue predates the separation of AP Physics content into two volumes. New issues were created for those books and dealt with. Closing this issue.
