### ISSUE TITLE
Multiple books => Introduction modules are numbered

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#282]
For all the baked books on qa.cnx.org, the chapter Introduction modules are numbered. They should not be because it differs from the PDF.

Here it is in [University Physics](https://qa.cnx.org/contents/1Q9uMg_a@5.22:bG-_rWXy@5/11-Introduction) (PDF on left, webview on right):

![image](https://user-images.githubusercontent.com/11298165/27875141-d10fe964-6177-11e7-8408-c73fa8557f51.png)

**Comment by kerwinso** [comment]
Also, the chapter outlines are missing again, see #185.

**Comment by tomjw64** [comment]
I'm betting the `.introduction` class was removed from the intro page, somehow, ...again. That would cause both of the issues described. If it's added back into the raw content before baking, the issue will likely be resolved.

**Comment by kerwinso** [comment]
@tomjw64 Here's the content for the intro module in University Physics: https://legacy-qa.cnx.org/content/m58268/latest/source

Looks like the `class="introduction"` is there.

**Comment by tomjw64** [comment]
@kerwinso Welp... That's strange. In any case, it doesn't make it through to the baked version of the book. Is there any way of seeing if it makes it into the raw xhtml? Something may be broken along the way.

**Comment by tomjw64** [comment]
@reedstrm @helenemccarron It appears `class="introduction"` is in the cnxml, but doesn't persist into the baked file (and thus I'm assuming the raw file as well).

**Comment by nyxer95** [comment]
Per @reedstrm, this requires cnxml to html transform. After code is deployed, requires re-baking.

**Comment by nyxer95** [comment]
Per @reedstrm -- All regressions between dev and QA probably got fixed with deploy on Monday and additional code changes that we deployed an hour ago.

**Comment by kerwinso** [comment]
Appears to be fixed on qa.cnx.org after rebake.
