### ISSUE TITLE
Multiple books => lines running through Answer Key content

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#283]
In re-baked books with an Answer Key, there are thin lines running through every line of content in the Answer Key. This greatly affects readability.

Look closely at the following screenshots. So far found in College Biology and University Physics, but I'm guessing it affects every baked book with an answer key.

Environment: Chrome 59 incognito, OS X El Capitan

**College Biology answer key** 
(https://qa.cnx.org/contents/GFy_h8cu@10.115:otIsPXu6@10.115/Answer-Key):
![image](https://user-images.githubusercontent.com/11298165/27883543-7b10611e-6196-11e7-8fde-f88afb70c157.png)

**University Physics answer key**
(https://qa.cnx.org/contents/1Q9uMg_a@5.22:5qqYClIo@5.22/Answer-Key):
![image](https://user-images.githubusercontent.com/11298165/27883557-87551ae6-6196-11e7-9a40-24fda03baa37.png)

**Comment by Stackblocks** [comment]
Can confirm it happening in Prince of Econ too.
![image](https://user-images.githubusercontent.com/12678235/27883683-004ee2a6-6197-11e7-9421-0e5eb5ef9bb6.png)

**Comment by kerwinso** [comment]
QA checklist:
- [ ] Econ
- [ ] University Physics
- [ ] College Biology
- [ ] more...

**Comment by tomjw64** [comment]
`[data-type="solution"]` has been given a top border in webview CSS

**Comment by caderitter** [comment]
@zroehr [here?](https://github.com/Connexions/webview/blob/master/src/scripts/modules/media/body/content-common.less#L541)

**Comment by tomjw64** [comment]
Suggestion for the selector depending on what Zach was using it for:
```css
[data-type="note"],
[data-type="exercise"],
[data-type="example"] {
  [data-type="solution"],
  .solution {
    border-top: .1rem solid #dcdcdc;
  }
}
```

**Comment by zroehr** [comment]
@caderitter lets implement @tomjw64 solution.

**Comment by caderitter** [comment]
Addressed [here](https://github.com/Connexions/webview/pull/1567)

**Comment by kerwinso** [comment]
Verified fix on qa.cnx.org (`v0.22.2.beta-dev8651376`) for University Physics and Principles of Economics. We will check other books during the regression testing phase.

![image](https://user-images.githubusercontent.com/11298165/27966080-8f5cd7a6-6303-11e7-93b2-614ca5e22f63.png)

![image](https://user-images.githubusercontent.com/11298165/27966077-8b4659ee-6303-11e7-8d6e-372c8e8d570f.png)
