### ISSUE TITLE
Econ => Figure titles not styling correctly 

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#284]
# Scenario
Figure titles in Principles of Economics are not bold, also some figure captions are not spaced properly from the figure title.

# Reproducibility Details
Persistent throughout the book.

- **Impact area**: figure titles
- **User**: n/a
- **URL / Location**: https://qa.cnx.org/contents/aWGdK2jw@11.345:6RH0nLs4@8/12-What-Is-Economics-and-Why-I
- **How many times were you able to reproduce the issue?** Persistent throughout the book.

## Steps to reproduce

- Open the baked webview on qa.cnx.org
- View a figure.

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/27915857-0f289bfa-622d-11e7-87dc-6cd6a1f32555.png)

![image](https://user-images.githubusercontent.com/12678235/27916006-7d5af8e8-622d-11e7-9ca1-4fe5e79d0a82.png)

# Environment

- **Instance**:  qa.cnx.org
- **OS**: macOS
- **Browser**: Chrome

# Impact

- **Severity**: moderate
- **Frequency of occurrence**: persistent throughout book

**Comment by caderitter** [comment]
Addressed in [webview:1570](https://github.com/Connexions/webview/pull/1571).

**Comment by kerwinso** [comment]
Another example of the missing space between figure title and caption bug: http://qa.cnx.org/contents/aWGdK2jw@11.345:vF-Cvj3d@5/14-How-Economists-Use-Theories
(Source: https://legacy-qa.cnx.org/content/m48593/latest/source)
![image](https://user-images.githubusercontent.com/11298165/28027126-ad694df4-655d-11e7-9e1b-9772b42d7ffe.png)

But, here's one that looks OK, whose markup looks the same (spacing etc.):
https://qa.cnx.org/contents/aWGdK2jw@11.345:JgDXaOLP@11/11-Introduction
(Source: https://legacy-qa.cnx.org/content/m48590/latest/source)
![image](https://user-images.githubusercontent.com/11298165/28027154-bc7a522a-655d-11e7-98e4-c27f0693a8a6.png)

Hmmmm.

**Comment by tomjw64** [comment]
I'll post here a copy pasta of a slack message regarding the spacing issue:

> When Cade and I went through this issue, it looked like a transform problem, as spaces were inserted into the raw html file before baking, but weren't in the cnxml. However, I might be able to make a temporary recipe fix for the issue if it's high priority, even though the fix probably doesn't belong there since the transforms shouldn't do that in the first place.

**Comment by kerwinso** [comment]
also see https://github.com/Connexions/oer.exports/issues/2871

**Comment by caderitter** [comment]
@kerwinso should be fixed now, in both webview and recipes.

**Comment by caderitter** [comment]
@Stackblocks 

[webview PR](https://github.com/Connexions/webview/pull/1571)
[recipes PR](https://github.com/Connexions/cnx-recipes/pull/294)

**Comment by kerwinso** [comment]
Verified fix on Principles of Econ, https://qa.cnx.org/contents/aWGdK2jw@11.345:JgDXaOLP@11/Introduction. 

Figure titles are bold (thanks to the webview PR), and after rebaking with the `figure-title-fix` branch, the spacing looks correct between figure titles and captions.

![image](https://user-images.githubusercontent.com/11298165/28383005-a1e7a316-6c85-11e7-840d-2327cade18b6.png)

![image](https://user-images.githubusercontent.com/11298165/28383007-a5479dea-6c85-11e7-8cd3-aae3fca8073d.png)

![image](https://user-images.githubusercontent.com/11298165/28383017-a8e610d0-6c85-11e7-84a4-05f8495491d4.png)
