### ISSUE TITLE
University Physics => Some H3 section headers are displaying as H1

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#290]
In University Physics chp. 2, 'Products of Vectors', the heading `The Scalar Product of Two Vectors (the Dot Product)` is supposed to render as H3. On https://qa.cnx.org/contents/1Q9uMg_a@5.22:Bioz__AG@5/25-Products-of-Vectors, it's rendering as an H1.

QA (wrong) on the left, dev (correct) on the right:
![image](https://user-images.githubusercontent.com/11298165/28028406-0d86735c-6562-11e7-8f5d-cfcf0b56c8d2.png)

Also found in module 1.1:
![image](https://user-images.githubusercontent.com/11298165/28139945-e0b8edb2-671b-11e7-99ef-a8fa41b848de.png)

**Comment by kerwinso** [comment]
Also, some H4s are displaying as H2s:

![image](https://user-images.githubusercontent.com/11298165/28140021-3c050688-671c-11e7-9486-03560bdc2bab.png)

**Comment by nyxer95** [comment]
This may be fixed by re-baking. Front-End Devs could not fix so may require more research.

**Comment by reedstrm** [comment]
looking at the bare page, it seems to be an H3, now, so I rebake should fix it: https://qa.cnx.org/contents/Bioz__AG@5/Products-of-Vectors

**Comment by nyxer95** [comment]
All regressions between dev and QA probably got fixed with deploy on Monday and additional code changes that we deployed an hour ago.

**Comment by reedstrm** [comment]
https://qa.cnx.org/contents/Bioz__AG@5/Products-of-Vectors shows the bare page, and it seems to be an H3 there now.

**Comment by kerwinso** [comment]
Verified fix on https://qa.cnx.org/contents/1Q9uMg_a@5.22:Bioz__AG@5/24-Products-of-Vectors:

![image](https://user-images.githubusercontent.com/11298165/28435543-1b18a75c-6d59-11e7-89d1-dc2b22dd002e.png)
