### ISSUE TITLE
TEG => Tables have no vertical separators

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#292]
# Scenario

Tables on TEG have no vertical line separators, which can be confusing very when a table has empty cells to be filled out.

## Screenshots

This is not the worst example, but I can see problems occurring on fill in the blank type questions.

Table in stats:
![statstable](https://user-images.githubusercontent.com/1285308/28084212-901b8df8-663d-11e7-88a9-2e4bb64449a9.png)

Table in TEG:
![tegtable](https://user-images.githubusercontent.com/1285308/28084216-924cca24-663d-11e7-98d5-4e9e4831314c.png)

**Comment by helenemccarron** [comment]
@chcase is it possible to add some CSS styling to table cells to make them a bit more legible?

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/30562847-7db6b8d0-9c85-11e7-8633-6517dae48c35.png)
