### ISSUE TITLE
TEG => Key terms are left unstyled on TEG

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#293]
# Scenario

Terms are not styled on TEG

## Screenshots

This section has many terms including numerical variables, categorical variables, parameter, statistic, etc.

The currently bolded terms have `<strong>` tags, and are not terms

![tegterms](https://user-images.githubusercontent.com/1285308/28084955-ec75141e-663f-11e7-99ac-ca98e0b3837d.png)

**Comment by helenemccarron** [comment]
The element `data-type="term"` should have `bold` css style applied to it.

**Comment by Stackblocks** [comment]
Resolved on the gateway.
