### ISSUE TITLE
Run SQL Query to Find Weird Lists

### ISSUE THREAD

**Issue by nyxer95** [Connexions/cnx-recipes#296]
# Scenario
[CTE.Pipeline1.04] Modify the epub pipeline so that the output for each step is HTML-parseable XHTML
Same testing as for [CTE.Pipeline1.11] Modify HTML format to be EPUB-compatible ?
Big one that we started talking about this morning. 
Some of this work was completed. 
Split up - smaller piece fixed that addresses the problem of having notes that are in paragraphs; this changes were merged, but other changes were not. 
What changed and how to test it? 
Various bug fixes in rhaptos-cnxml-utilties.
Impacts non-OpenStax books; the impact is the style of lists in webview has changed so that they are no longer 1, 2, 3, 4 and a, b, c, d - now matches how the list is styled in the cnxml.
Look at a few non-OpenStax modules. Find a few modules that have these weird lists in them. SQL documented in trac for cnx.org (Cade could run this for you).

Can have one of the CMs help with this testing.

**Comment by kerwinso** [comment]
Translation: Apparently there's a SQL query documented somewhere in Trac that can help us pinpoint non-Openstax authored collections with lists in them on CNX. This would be to help us test https://github.com/Connexions/cnx-recipes/issues/295

**Comment by caderitter** [comment]
```
-- input: page uuid
-- output: book name, book uuid, input page uuid

create or replace function get_books_containing_uuid_versionless(input_uuid uuid) RETURNS table(name text, uuid uuid, root_page_uuid uuid)
AS
$$
BEGIN
return query
WITH RECURSIVE t(node, title, parent, path, value, root_page_uuid) AS (
  SELECT nodeid, title, parent_id, ARRAY[nodeid], documentid, m.uuid
  FROM trees tr, modules m
  WHERE m.uuid = input_uuid
  AND tr.documentid = m.module_ident
  AND tr.parent_id IS NOT NULL
UNION ALL
  SELECT c1.nodeid, c1.title, c1.parent_id, t.path || ARRAY[c1.nodeid], c1.documentid, t.root_page_uuid /* Recursion */
  FROM trees c1
  JOIN t ON (c1.nodeid = t.parent)
  WHERE not nodeid = any (t.path)
)
SELECT m.name, m.uuid, t.root_page_uuid
FROM t
JOIN modules m on t.value = m.module_ident
WHERE t.parent IS NULL;
END
$$
language plpgsql;
```

```
-- input: none
-- output: table of page uuids and boolean whether they contain the xpath
create or replace function find_lists() returns table(uuid uuid, bool boolean) as
$$
begin
        return query
        select m.uuid, xpath_exists(e'//*[local-name() = \'problem\']/*[local-name() = \'para\']/*[local-name() = \'list\']/*[local-name() = \'item\']', convert_from(file,'utf8')::xml)
        from modules m
        natural join module_files
        natural join files
        where filename = 'index.cnxml';
exception when others then
--ignore the malformed xml doc
end
$$
language plpgsql;
```

```
-- select pages with the xpath in them
create or replace view tmp as (
select fl.uuid from find_lists() fl where fl.bool = 't'
);

-- find books containing this page using get_books_containing_uuid_versionless()
select distinct gb.name, gb.uuid, gb.root_page_uuid from tmp t, LATERAL get_books_containing_uuid_versionless(t.uuid) gb;
```

**Comment by kerwinso** [comment]
Here's a cleaned-up file containing the results of Cade's query. These are all modules and books on qa.cnx.org that have `<list>` tags inside `<para>` tags.

[books_with_problem_para_lists.xlsx](https://github.com/Connexions/cnx-recipes/files/1177877/books_with_problem_para_lists.xlsx)

**Comment by philschatz** [comment]
Cool! Could a similar query be made to search through the generated XHTML (since it is also XML)? That would help QA in verifying things work by verifying that no occurrences of a particular XPath exist

**Comment by kerwinso** [comment]
Cade ran his query on the XHTML on qa.cnx.org, searching specifically for the XPath `div[@data-type="list"]//div[@data-type="item"]`. There were 0 results, suggesting the problem in #295 has been eradicated (at least in this environment).

**Comment by caderitter** [comment]
Nothing of interest found in those pages with your suggested `[not(ol) and not(ul)]` ?

**Comment by kerwinso** [comment]
@caderitter Nope, just stuff like this:

```html
<div data-type="list">
  <div data-type="title">...</div>
</div>
<ul>
  <li>...</li>
  <li>...</li>
</ul>
```
(Example: https://qa.cnx.org/contents/IwweRb5B@15/Ear-Training)

The lists are still being rendered properly in the HTML.
