### ISSUE TITLE
TEG => Mathjax in AP Macroeconomics showing incorrectly.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#298]
# Scenario

# Reproducibility Details

- **Impact area**: AP Macroecon content on Gateway Staging
- **User**: openstax@texasgateway.org
- **URL / Location**: https://stg.texasgateway.org/resource/31-demand-supply-and-equilibrium-markets-goods-and-services?book=244336
- **How many times were you able to reproduce the issue?** Constant.

## Steps to reproduce:

- Access book.
- Scroll to section containing MathJax (possible correlation with the `$` character).
- Observe

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/28683995-5c53ed34-72c8-11e7-8de0-52981b068902.png)
![image](https://user-images.githubusercontent.com/12678235/28683997-6089575e-72c8-11e7-9dba-1ea88aed6431.png)
![image](https://user-images.githubusercontent.com/12678235/28684007-693a2fd6-72c8-11e7-94df-a406068a7ee6.png)

# Environment:

- **Instance**: stg.texasgateway.org
- **OS**: macOS
- **Browser**: Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**:

**Comment by philschatz** [comment]
I am not sure how the TEG server loads and configures MathJax to run on their pages... but it seems that would be where the problem is.
