### ISSUE TITLE
TEA AP Macro not working on tea.cnx.org webview

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#300]
# Scenario

The TEA server with updated AP Macro content is throwing an internal server error upon request of the webview for TEA AP Macroeconomics - Final Delivery.

In order for us to move forward on bug fixes for TEA AP Macro, we must at minimum have access to the info in the More Information tab in webview (to get the uuid of the book)

## Steps to reproduce:

- Go to the legacy-tea page for TEA AP Macro Final Delivery: https://legacy-tea.cnx.org/content/col10015/latest/
- Start reading the book by clicking Start or by navigating to any page of the book.
- Click the link inside `Note: You are viewing an old style version of this document. The new style version is available here.` in an attempt to view the webview version of the book.
- The current address in the url bar should be something like `https://cnx.org/content/m70824/1.5/?collection=col10015` and you should see a `404 Not Found` error message. This is expected as the collection is not on production. Change the server to TEA, by adding `tea` as the subdomain like so: `https://tea.cnx.org/content/m70824/1.5/?collection=col10015`
- Witness, in awe, the beautiful error message below.

## Screenshots

![screenshot_3](https://user-images.githubusercontent.com/1285308/28731951-91a9a356-739b-11e7-87a6-719a2eddb32a.png)

# Environment:

- **OS**: Windows 10
- **Browser**: Chrome

# Impact

- **Frequency of occurrence**: Always and forever

**Comment by philschatz** [comment]
Adding @karenc to see if she can help 😄
