### ISSUE TITLE
TEG => Notes not styled on the Gateway

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#301]
# Scenario

`Note` type elements are being displayed as plain body text instead of being styled.

# Reproducibility Details

- **Impact area**: Gateway Staging
- **User**: openstax@texasgateway
- **URL / Location**: https://stg.texasgateway.org/resource/11-physics-introduction?book=251761 under "Models, Theories, and Laws"
- **How many times were you able to reproduce the issue?** Constant.

## Steps to reproduce:

n/a

## Screenshots

![2017-08-02_12-00-02](https://user-images.githubusercontent.com/12678235/28889090-8a077a88-7788-11e7-9503-7bd887ab989c.png)
![2017-08-02_12-16-41](https://user-images.githubusercontent.com/12678235/28889091-8b866d06-7788-11e7-8e24-2e30d1b61c10.png)

# Environment:

- **Instance**: stg.texasgateway.org
- **OS**: macOS
- **Browser**: Chrome

# Impact

- **Severity**: high
- **Frequency of occurrence**: constant

**Comment by helenemccarron** [comment]
We will submit suitable CSS to be included in the stylesheet on the Gateway

**Comment by philschatz** [comment]
Confirmed at https://stg.texasgateway.org/resource/11-definitions-statistics-probability-and-key-terms?book=261661#fs-idp138853216

![image](https://user-images.githubusercontent.com/253202/29427623-62e4504e-8358-11e7-9ea2-7323d3acb705.png)
