### ISSUE TITLE
Check Your Understanding in AP Physics missing Solution heading

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#304]
# Scenario

The Check Your Understanding elements in AP Physics are missing the solution heading. There doesn't seem to be a recipe which add it.

## Screenshots
![screenshot_13](https://user-images.githubusercontent.com/1285308/29035930-f9010fd4-7b62-11e7-943b-970bb9fdfd3b.png)
![screenshot_14](https://user-images.githubusercontent.com/1285308/29035934-fc41209e-7b62-11e7-89d5-f6aacb825e11.png)

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/30562666-efd3ad52-9c84-11e7-8a90-6d4a60d8a89a.png)
