### ISSUE TITLE
TEG => Check Your Understanding answer styling.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#305]
# Scenario
The answers to `Choose Your Understanding` problems need beautification. More details in the screenshots section.

# Reproducibility Details

- **Impact area**: Content
- **User**: 
- **URL / Location**: 
    - AP Physics 1: https://stg.texasgateway.org/resource/12-physical-quantities-and-units?book=262941
    - AP Physics 2: https://stg.texasgateway.org/resource/12-conductors-and-insulators?book=266191&binder_id=

## Steps to reproduce:

n/a

## Screenshots
![2017-08-07_13-31-40](https://user-images.githubusercontent.com/12678235/29040525-fe3093b4-7b74-11e7-9556-8bfbd6432979.png)

![2017-08-07_10-20-22](https://user-images.githubusercontent.com/12678235/29040389-722d32dc-7b74-11e7-9bba-f57813c786a0.png)

# Environment:

- **Instance**: Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by tomjw64** [comment]
Additionally, it seems as though we have some content/recipe issues with whether or not we have the words "Answer" or "Solution" or no words at all preceding the solutions of check your understanding problems.

**Comment by helenemccarron** [comment]
`[data-type="solution"]` instead of `.solution` for styling, fix needed for the missing title

**Comment by philschatz** [comment]
Confirmed this element has a top border and vertical padding (see https://stg.texasgateway.org/resource/11-definitions-statistics-probability-and-key-terms?book=261661#fs-idm78922614 )

![image](https://user-images.githubusercontent.com/253202/29427359-92816694-8357-11e7-9b06-fb31f5a0db98.png)
