### ISSUE TITLE
TEG => Conceptual Question numbering beautification.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#306]
# Scenario

The numbering on Conceptual Questions (and possibly other problems) are unstyled and flush with the question. They need to have a space between and preferably the number should be bolded.

# Reproducibility Details

- **Impact area**: Content
- **User**: n/a
- **URL / Location**: https://stg.texasgateway.org/resource/conceptual-questions?book=262941

## Steps to reproduce:

n/a

## Screenshots

![2017-08-07_10-29-47](https://user-images.githubusercontent.com/12678235/29040754-d99fc26c-7b75-11e7-815e-dd3bbf9aa044.png)

# Environment:

- **Instance**: Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by helenemccarron** [comment]
@chcase please the following snippet:
```
.os-chapter-outline {
  padding-bottom: 1em;
}

[data-type="exercise"] [data-type="problem"] .os-number {
  float: left;
  font-weight: bold;
  margin-right: 1em;
}
```

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/30562697-0a0dc36a-9c85-11e7-8904-91d43f23f7bd.png)
