### ISSUE TITLE
TEG  => Chapter Outline flush with the splash image

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#307]
# Scenario

Chapter Outline is flush with the splash image. 

_Per Alana some top padding on the splash image should resolve this._

# Reproducibility Details

- **Impact area**: Content
- **User**: n/a
- **URL / Location**: https://stg.texasgateway.org/resource/connection-ap%C2%AE-courses?book=262941

## Steps to reproduce:

n/a 

## Screenshots

![2017-08-07_10-26-08](https://user-images.githubusercontent.com/12678235/29040816-146ee1fc-7b76-11e7-8acd-729a06845030.png)

# Environment:

- **Instance**: Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by helenemccarron** [comment]
@chcase please the following snippet:
```
.os-chapter-outline {
  padding-bottom: 1em;
}
