### ISSUE TITLE
Content appears before Chapter Objectives Header in TEA HS Stats

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#310]
Content (a single figure, basically) is appearing before the first h3 (Chapter Objectives) header in every intro module in HS Statistics. This will likely cause this figure to be missing once uploaded on TEG. A recipe change must be made to correct the ordering of the intro modules.

If resolved, the Chapter Objectives section will appear prior to the intro figures.

Screenshot of issue:

![screenshot_23](https://user-images.githubusercontent.com/1285308/29349336-dc00cda8-821e-11e7-9b44-fbec73505a95.png)

**Comment by tomjw64** [comment]
Resolved in PR #297 
Pinging in:
@helenemccarron 
@openstaxalina 
To double-check that this change is desirable and still required...

**Comment by helenemccarron** [comment]
This isn't needed for introduction modules because they are handled differently in the Gateway. See here: https://www.texasgateway.org/resource/introduction-0?binder=141866

**Comment by tomjw64** [comment]
As per @helenemccarron's previous comment, this change has been reverted in PR #297
