### ISSUE TITLE
TEA => Display Issues in High School Statistics

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#312]
# Scenario

This issue collects the various display issues encountered in TEA High School Statistics. Individual issues can be spun off as necessary.

# Reproducibility Details

- **Impact area**: Gateway Staging
- **User**: openstax@texasgateway.org
- **URL / Location**: stg.texasgateway.org
- **How many times were you able to reproduce the issue?** n/a

### 1.
![image](https://user-images.githubusercontent.com/12678235/29424110-f0466428-8343-11e7-8a56-9fe3461a5e86.png)
**[Ch. 1.6](https://stg.texasgateway.org/resource/16-sampling-experiment?book=261661) -- Line breaks missing**

Per Helene:
>Due to the fact that a title was added to a `para` in the CNXML, which translates to a `span` >with a `data-type="title"`.  Quickest way to solve this is to add CSS to the Gateway. 
>```
>p span [data-type="title"] {
>display: block;
>}
>```
>or something similar

### 2.
![image](https://user-images.githubusercontent.com/12678235/29422013-75b3f934-833c-11e7-869f-86d99f520423.png)
**[Ch 1.2 Table 1.8](https://stg.texasgateway.org/resource/12-data-sampling-and-variation-data-and-sampling?book=261661&binder_id=261591) -- Caption appearing unstyled above table**

![image](https://user-images.githubusercontent.com/12678235/29462970-ad80ea42-83f6-11e7-9944-be1132fbaf40.png)
**[HS Stats 4.2](https://stg.texasgateway.org/resource/42-mean-or-expected-value-and-standard-deviation?book=261661)-- Caption pushed above table and compressed.**

Per Helene:
>The following CSS needs to be added for captions to display at the bottom of tables
>```caption {
>caption-side: bottom;
>padding-top: 1em;
>font-size: 0.8em;
>}
>```

### 3.
![image](https://user-images.githubusercontent.com/12678235/29423542-c5c65ee4-8341-11e7-8c52-eb11072064de.png)
**Book-wide -- Missing em-dashes**

>Per Phil, related to #314 (`;` issue)

# Environment:

- **OS**: macOS
- **Browser**: Chrome

**Comment by helenemccarron** [comment]
- 1st screenshot is due to the fact that a title was added to a `para` in the CNXML, which translates to a `span` with a `data-type="title"`.  Quickest way to solve this is to add CSS to the Gateway. 
```
p span [data-type="title"] {
display: block;
}
```
or something similar

**Comment by helenemccarron** [comment]
- 2nd screenshot, captions. The following CSS needs to be added for captions to display at the bottom of tables
```
caption {
caption-side: bottom;
padding-top: 1em;
font-size: 0.8em;
}

```

**Comment by helenemccarron** [comment]
- 3d screenshot, em-dashes
Per Phil, related to #314 (`;` issue)

**Comment by philschatz** [comment]
The "Disappearing characters" should be fixed in https://github.com/Connexions/rhaptos.cnxmlutils/pull/160 .

In order to test, it seems like we would need to:

1. (optionally, merge the PR)
1. deploy the code to tea.cnx
1. rebuild all the HTML files (maybe using https://github.com/karenc/db-migrator/pull/39 )
1. fetch the new HTML (using `./script/fetch-html`)
1. bake the book
1. (verify by opening the baked HTML file in a browser)

And then:

1. build an epub
1. upload to the Gateway
1. (verify)

**Comment by philschatz** [comment]
It sounds like emdashes were verified but the line breaks and table captions have not been fixed.

Do we have to fix those line breaks or could we just make them bold. I am concerned about having to support complex CSS. Making it bold (and adding spacing) is relatively easy but adding a line break might be more complex.

**Comment by helenemccarron** [comment]
`p > span > [data-type="title"]` would work better than `p span [data-type="title"] `

use:
```
p > span > [data-type="title"] {
display: block;
}
```

**Comment by Stackblocks** [comment]
Tested with Helene's tea-styles.css and updates made by the TEG. Resolved.
