### ISSUE TITLE
TEA = Content Issues in High School Physics

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#313]
# Scenario

This issue collects the various content issues encountered in TEA High School Physics. Individual issues can be spun off as necessary.

# Reproducibility Details

- **Impact area**: Gateway Staging
- **User**: openstax@texasgateway.org
- **URL / Location**: stg.texasgateway.org
- **How many times were you able to reproduce the issue?** n/a

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/29420465-a630e9e6-8337-11e7-8ea1-003c01ceccc0.png)
**Bookwide -- Section Key Terms missing on gateway, present in delivered epub.**

![image](https://user-images.githubusercontent.com/12678235/29421796-c4840050-833b-11e7-95e4-4c9814a96e09.png)
**[Ch. 3.2](https://stg.texasgateway.org/resource/32-representing-acceleration-equations-and-graphs?book=256821) -- Practice problems missing on gateway, present in epub**

![image](https://user-images.githubusercontent.com/12678235/29430623-b437fa16-835a-11e7-97f6-3bbe012de2ad.png)
**[Ch. 11.4](https://stg.texasgateway.org/resource/114-test-homogeneity?book=261661) - Introductory paragraph missing**

![image](https://user-images.githubusercontent.com/12678235/29464190-bb3ceb6e-83fa-11e7-9f94-6f4748543190.png)
**[Ch. 18.5 Practice Problems](https://stg.texasgateway.org/resource/185-capacitors-and-dielectrics?book=256821)**
# Environment:

- **OS**: macOS
- **Browser**: Chrome

**Comment by helenemccarron** [comment]
Related to #315

**Comment by Stackblocks** [comment]
Relevant content moved to #315, closing this specialized issue.
