### ISSUE TITLE
TEA => Alignment glitches on Gateway

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#316]
# Scenario

Content is getting mis-aligned on the gateway.

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/29419708-6a636792-8335-11e7-9a69-540471938dfe.png)
**[Ch. 1 Chapter Review 38A](https://stg.texasgateway.org/resource/chapter-review?book=256821)**

![image](https://user-images.githubusercontent.com/12678235/29434791-1072647e-836a-11e7-886f-7ca02c6baa90.png)
**[Ch. 4 Test Prep 19](https://stg.texasgateway.org/resource/test-prep-2?book=256821)**

![image](https://user-images.githubusercontent.com/12678235/29434692-b810ca6e-8369-11e7-97d2-851ca135fa26.png)
**[HS Stats Ch. 8 Homework](https://stg.texasgateway.org/resource/homework-6?book=261661)**

![image](https://user-images.githubusercontent.com/12678235/29434917-86783036-836a-11e7-916d-e28c7a7a19f9.png)
**[HS Stats Ch.2 Homework](https://stg.texasgateway.org/resource/bringing-it-together-homework-0)**

![image](https://user-images.githubusercontent.com/12678235/29435019-dd7dc666-836a-11e7-955e-c288a81fb497.png)
[HS Stats Ch.10 Homework](https://stg.texasgateway.org/resource/homework-8?book=261661)

# Environment:

- **Instance**: Gateway Staging
- **OS**: macOS
- **Browser**: Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**:

**Comment by helenemccarron** [comment]
the list display is caused by display: flex; on that element in the Gateway's CSS, it needs to be removed see #311

**Comment by helenemccarron** [comment]
the list display is caused by display: flex; on that element in the Gateway's CSS, it needs to be removed see #311

**Comment by philschatz** [comment]
I _think_ https://github.com/Connexions/cnx-recipes/issues/286#issuecomment-324109223 will fix this issue as well. But folks would need to inject-the-css-into-the-gateway (maybe using browser dev tools) to be sure

**Comment by Stackblocks** [comment]
Tested with Helene's tea-final-deliveries branch tea-styles.css and updates made by the TEG. Resolved.
