### ISSUE TITLE
TEA => Over-wide equation in HS Stats 4.2 causing display issues.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#317]
![image](https://user-images.githubusercontent.com/12678235/29463308-db3125fa-83f7-11e7-86ab-030baa22e229.png)
**[Ch. 4.2](https://stg.texasgateway.org/resource/42-mean-or-expected-value-and-standard-deviation?book=261661) -- Over-long equation.**

# Environment:

- **Instance**: tea.cnx.org / stg.texasgateway.org
- **OS**: macOS
- **Browser**: Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**:

**Comment by oscryan** [comment]
Made a math table to break that line up

**Comment by oscryan** [comment]
<img width="1030" alt="screen shot 2017-08-18 at 11 18 37 am" src="https://user-images.githubusercontent.com/1895432/29467694-00af1c24-8407-11e7-843c-73baf665ac35.png">

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/29474939-64a423fc-8423-11e7-8e3b-c64a43679ba7.png)
