### ISSUE TITLE
TEA => AP Physics 1 issues for review

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#319]
# Scenario

This issue will collect the issues in the Final Delivery content for AP Physics 1 which can be spun out into separate issues as necessary.

### 1. [PhET Simulations load incorrectly](https://stg.texasgateway.org/resource/13-accuracy-precision-and-significant-figures?book=288786)
![image](https://user-images.githubusercontent.com/12678235/29500424-3a482652-85e6-11e7-89f5-bd44ac95ecc9.png)
Per Ryan:
> Looks like the link is loading the .jar file directly

**2017-09-12 Status:** ✅ 

### 2. [Sub & Superscript padding issues](https://stg.texasgateway.org/resource/test-prep-ap%C2%AE-courses-33?book=288786)
![image](https://user-images.githubusercontent.com/12678235/29502147-7d628754-85f3-11e7-897e-297c4faf4f51.png)
Related: #311 

**2017-09-12 Status:** ✅ 

### 3. [Math in title displays incorrectly](https://stg.texasgateway.org/resource/28-graphical-analysis-one-dimensional-motion?book=288786)
![image](https://user-images.githubusercontent.com/12678235/29502262-4ec07838-85f4-11e7-91bd-15a4f87623f6.png)

**2017-09-12 Status:** ✅  (Gateway-specific issue)

### 4. [12.3 Direct link to imagefrombulgaria.com which is now a weird loan-sharking site.](https://stg.texasgateway.org/resource/123-most-general-applications-bernoulli%E2%80%99s-equation?book=303326)
![image](https://user-images.githubusercontent.com/12678235/29671193-7db6621c-88ae-11e7-9931-59bebfc01ac7.png)

**2017-09-12 Status:** ⚠️ 

# Environment:

- **Instance**: Gateway Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by tomjw64** [comment]
2. Should be fixable via replacing the current CSS with something like what Phil mentioned in this comment: https://github.com/Connexions/cnx-recipes/issues/286#issuecomment-324109223

**Comment by philschatz** [comment]
3 ) This is an import bug in TEG. It strips any elements inside an `<h3>`. Related to https://github.com/Connexions/cnx-recipes/issues/318#issuecomment-324423497

**Comment by Stackblocks** [comment]
No.3 spun off into issue #323

**Comment by philschatz** [comment]
1 ) No change
2 ) The content in the screenshot is no longer available at that page
3 ) No change (spun off into separate issue)
4 ) No change

**Comment by tomjw64** [comment]
@openstaxalina The link in part 4 is probably not what we intended and should probably be removed from the content, but I assume since it is part of a photo credit, we need to be careful with this one?

**Comment by openstaxalina** [comment]
emailed WiseWire regarding imagesfrombulgaria link.  thanks @Stackblocks and @tomjw64 !

**Comment by openstaxalina** [comment]
@tomjw64 @Stackblocks the link in item 4 has been removed from the content on tea.cnx.org.  that part of this issue is resolved.

**Comment by openstaxalina** [comment]
@tomjw64 @helenemccarron I confirmed with Gaston that the PhETs render properly now in AP Physics 1.  He has yet to test AP Physics 2.  But Ryan had Gaston and Nick replace the jars with links in both titles so we should be fine.

I misspoke re: HS Physics - we don't expect this issue to come up.  Gaston is testing that book next and will raise the alarm if he sees the ugly jar rendering in that title.
