### ISSUE TITLE
TEA => AP Physics 2 issues for review

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#320]
# Scenario

This issue will collect the issues in the Final Delivery content for AP Physics 2 which can be spun out into separate issues as necessary.

### 1. [PhET Simulations load incorrectly (same as AP Physics 1)](https://stg.texasgateway.org/resource/13-accuracy-precision-and-significant-figures?book=288786)
![image](https://user-images.githubusercontent.com/12678235/29500937-440bd0c2-85ea-11e7-98be-180d0c938d9c.png)
Per Ryan:
> Looks like the link is loading the .jar file directly

Per Kerwin:
>on webview the link is: https://tea.cnx.org/resources/18d681501d90172f9d9f263a210752fe855a258e/travoltage_en.jar
>
>on TEG: 
>https://stg.texasgateway.org/sites/default/files/AP-Physics2/resources/18d681501d90172f9d9f263a210752fe855a258e

**2017-09-12 Status:** ✅ 

### 2. [Content Missing in 2.7](https://stg.texasgateway.org/resource/27-energy-stored-capacitors?book=293891)
![image](https://user-images.githubusercontent.com/12678235/29502205-e4da6924-85f3-11e7-9981-d6143dbec886.png)

**2017-09-12 Status:** ✅ 

### 3. [Math in Note Title displaying incorrectly](https://stg.texasgateway.org/resource/26-capacitors-series-and-parallel?book=293891)
![image](https://user-images.githubusercontent.com/12678235/29502242-298e36f4-85f4-11e7-8fa4-2464ea431e5e.png)

**2017-09-12 Status:** ✅  (Gateway specific issue, discussed with TEG)

### 4. [Note title displaying in answer section](https://stg.texasgateway.org/resource/22-electric-potential-uniform-electric-field?book=293891) and link to [tea.cnx.org](https://tea.cnx.org/contents/Eq-JXx7D@4.4:WdUyopSY@4/21-Electric-Potential-Energy-P#fs-id824424)
![image](https://user-images.githubusercontent.com/12678235/29502299-99ad9c36-85f4-11e7-9442-591d9c35b3f3.png)

[Another example of mis-located note title](https://stg.texasgateway.org/resource/21-electric-potential-energy-potential-difference?book=293891)
![image](https://user-images.githubusercontent.com/12678235/29502328-b8109688-85f4-11e7-98cf-13b96b88481d.png)

**2017-09-12 Status:** ✅ 

# Environment:

- **Instance**: Gateway Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by tomjw64** [comment]
Working on (4)

**Comment by philschatz** [comment]
3 ) This is an import bug in TEG first-commented in https://github.com/Connexions/cnx-recipes/issues/319#issuecomment-324428297

**Comment by helenemccarron** [comment]
Thomas fixed 4 https://github.com/Connexions/cnx-recipes/pull/297/commits/e4d6294be0dbb2c65f410034b67fa7ef62a530ec - needs to be rebake to verify

**Comment by Stackblocks** [comment]
No.2 added to #315
