### ISSUE TITLE
TEA => AP Macroecon issues for review

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#321]
# Scenario

This issue will collect the issues in the Final Delivery content for AP Macroecon which can be spun out into separate issues as necessary.

### 1. [Preface]() -- Preface missing
![image](https://user-images.githubusercontent.com/12678235/29584128-5de39962-8748-11e7-9b2f-db3f171c54d8.png)
Rebecca with the TEG is looking into this.

**2017-09-12 Status:** ✅ 

### 2. [Ch. 17 Intro](https://stg.texasgateway.org/resource/introduction-impacts-government-borrowing?book=291906) -- Double-double quotes
![image](https://user-images.githubusercontent.com/12678235/29673499-05086bba-88b5-11e7-9c28-63f7b9cb3af2.png)

**2017-09-12 Status:** ✅ 

### 3. [Ch. 5 Intro](https://stg.texasgateway.org/resource/introduction-macroeconomic-perspective?book=291906&binder_id=291806) -- Titles missing
![image](https://user-images.githubusercontent.com/12678235/29674469-e78c2326-88b7-11e7-830a-5fd9be8c2333.png)

**2017-09-12 Status:** ✅ 

# Environment:

- **Instance**: Gateway Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by kerwinso** [comment]
Part 1 (missing preface link) appears to be fixed:

![image](https://user-images.githubusercontent.com/11298165/30220222-3dd220c8-9484-11e7-93c3-b0108c83a692.png)

**Comment by openstaxalina** [comment]
Issue 3 affects AP Macroecon, HS Stats, and possibly other books.
Suggestion from Helene is to put all these related screenshots/locations into an issue and assign to Christine at TEG.

**Comment by openstaxalina** [comment]
Issue 2 is a content issue and related to fixing the Windows quote character (?).  This issue may be occur in multiple places.  However, we are going to leave it as-is for now.
