### ISSUE TITLE
TEA => some emdashes are being dropped during import

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-recipes#324]
# Scenario

It seems that the Gateway importer sometimes removes emdash (`&#8212;`) characters and possibly others when importing content (see example links and screenshot below).

It appears that the characters are removed in text that occurs before an element but not after. From the example below, it seems that something like this:

```html
<p>
  Case 1 &#8212;
  <em>Case 2 &#8212;</em>
  Case 3 &#8212;
</p>
```

... is currently imported as:

```html
<p>
  Case 1
  <em>Case 2 </em>
  Case 3 &#8212;
</p>
```

... but it should not remove those characters.

# Reproducibility Details

## Steps to reproduce:

This particular piece of content illustrates both cases: when emdashes are removed and when emdashes are preserved.

[Link to Openstax version](https://tea.cnx.org/contents/uK6yCvlh@5/Practical-Problems-with-Discre#fs-idp82512800)

[Link to Gateway version](https://stg.texasgateway.org/resource/166-practical-problems-discretionary-fiscal-policy?book=291906#content-291491)

## Screenshots

![image](https://user-images.githubusercontent.com/253202/29683028-0ac91830-88db-11e7-8176-076763298756.png)

# Environment:

- **OS**: macos
- **Browser**: Chrome

# Impact

- **Severity**: medium
- **Frequency of occurrence**: sporadic

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/30564150-bc207dd2-9c89-11e7-8076-f7fdb754666b.png)
