### ISSUE TITLE
TEA => Missing headers in introduction modules for multiple books

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#327]
**[HS Statistics](https://stg.texasgateway.org/resource/introduction-7?book=278536&binder_id=299966):**

Chp. 4:
![image](https://user-images.githubusercontent.com/11298165/30222349-848d2b36-948c-11e7-90ad-a90ae3785ab7.png)

Chp. 5:
![image](https://user-images.githubusercontent.com/11298165/30222339-7c5602d0-948c-11e7-9223-9b5ea792f0b8.png)

**[AP Macro Econ](https://stg.texasgateway.org/resource/introduction-macroeconomic-perspective?book=283446&binder_id=):**
Chp. 5:
![image](https://user-images.githubusercontent.com/11298165/30222367-914aa5ba-948c-11e7-88af-e76c6c99c98e.png)

**[HS Physics](https://stg.texasgateway.org/resource/introduction-42?book=289991)**:
Ch. 2
![image](https://user-images.githubusercontent.com/11298165/30231747-ec6dae40-94b1-11e7-9d09-1ba132720dcc.png)

Ch. 3
![image](https://user-images.githubusercontent.com/11298165/30231827-6a457802-94b2-11e7-9ff7-8eac20c81b5e.png)

Also check Chp. 4 @Stackblocks 

cc @helenemccarron @tomjw64

**Comment by rfreedholm** [comment]
This issue has been fixed on Gateway staging
