### ISSUE TITLE
University Physics links to equations not correct

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-recipes#331]
# Scenario
I noticed when viewing the release candidate video that we seem to have an issue with links to equations in University Physics - links to equations are displayed as links to the previous Figure. The actual link seems ot be correct (#id points to the div around the equation)

Unbaked version of page says Equation there. Book was baked with recipe w/ hash 872066e821b89d8c88553f4c4dfef4d7f8168076, which matches u-physics.css on tip of tea-final-deliveries branch.

# Screenshots
![screenshot from 2017-09-21 08-12-12](https://user-images.githubusercontent.com/253212/30697618-41139a20-9ea5-11e7-8972-29c75e33d27e.png)

- **Impact area**:  University Physics
- **User**: Ross
- **URL / Location**:  https://qa.cnx.org/contents/1Q9uMg_a@5.26:ffNtT2kw@6/21-Scalars-and-Vectors#fs-id1167133686173

**Comment by tomjw64** [comment]
Addressed in PR #297

**Comment by kerwinso** [comment]
Verified fix with `tea-final-delivery` branch version of `u-physics.css` on staging: http://staging.cnx.org/contents/1Q9uMg_a@5.59:ffNtT2kw@7/21-Scalars-and-Vectors#fs-id1167133394048

![image](https://user-images.githubusercontent.com/11298165/30765180-ef5e20f0-9fb3-11e7-8d7b-4b8c5e96a94d.png)
