### ISSUE TITLE
TEA => row-oriented image bug in AP Biology

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#332]
# Scenario

The third image in a row of three images becomes tiny.

# Reproducibility Details

- **Impact area**: AP Biology
- **URL / Location**: 

1. https://www.texasgateway.org/resource/362-life-histories-and-natural-selection?book=323226
2. https://www.texasgateway.org/resource/364-population-dynamics-and-regulation?book=323226

- **How many times were you able to reproduce the issue?** Constant

### 1.
![image](https://user-images.githubusercontent.com/12678235/30753298-82a0ab10-9f84-11e7-84a2-61b3648110c5.png)

### 2. 
![image](https://user-images.githubusercontent.com/12678235/30753427-e16a19ce-9f84-11e7-89d6-38c60da92212.png)

# Environment:

- **OS**: MacOS
- **Browser**: Chrome

**Comment by chcase** [comment]
@Stackblocks This issue has been resolved on staging and will be included in the next release to production.   Date TBD - either 9/28 or week of 10/2

Confirming the row-orientated images now render properly:
https://stg.texasgateway.org/resource/362-life-histories-and-natural-selection
https://stg.texasgateway.org/resource/364-population-dynamics-and-regulation

**Comment by chcase** [comment]
@Stackblocks We pushed a maintenance update tonight and included a fix for this issue as well.  Confirmed on production.  If you notice any other issues let us know.
