### ISSUE TITLE
University Physics => Escaped markup in section titles

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#333]
Same issue as in #171 
http://staging.cnx.org/contents/1Q9uMg_a@5.59:bG-_rWXy@5/Introduction

![image](https://user-images.githubusercontent.com/11298165/30765495-93a760b2-9fb5-11e7-8c11-a3ed603d3233.png)

**Comment by tomjw64** [comment]
@philschatz This isn't happening on my local bakes. It looks like you sorted this out last time. Could you take a look?

**Comment by tomjw64** [comment]
as per Ross, this may already be fixed, but the version of webview on staging may be different than on qa

**Comment by philschatz** [comment]
Yep, which version of webview is on staging? It should be the same version as what is on QA

**Comment by kerwinso** [comment]
`webview` was not tagged for AW release, hence an old version got deployed to staging. karen deploying https://github.com/Connexions/webview/releases/tag/v0.23.1 right now as I type. I will reverify this after deployment.

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1
