### ISSUE TITLE
TEA => Exposed HTML in AP Bio section title

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#335]
# Scenario

The `G0 Phase` section title in Chapter 10.2 is showing exposed HTML.
# Reproducibility Details

- **URL / Location**: https://www.texasgateway.org/resource/102-cell-cycle?book=323226
- **How many times were you able to reproduce the issue?** Persistent

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/30822872-e7824990-a1ef-11e7-9401-7e9bd4fe0f87.png)

# Environment:

- **Instance**: Production
- **OS**: MacOS
- **Browser**: Chrome / FireFox

**Comment by chcase** [comment]
@Stackblocks We pushed a maintenance update tonight and included a fix for this issue as well.  Confirmed on production.  If you notice any other issues let us know.
