### ISSUE TITLE
Assignable Webview :Feature: Interactive "Note"

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#336]
# Scenario

The Interactive note feature still says "Note: Interactive"
# Reproducibility Details

- **Impact area**: Webview
- **User**: 
- **URL / Location**: 
- **How many times were you able to reproduce the issue?**  consistently throughout

## Steps to reproduce:

- Step 1 
Go to any module in: https://staging.cnx.org/contents/1Q9uMg_a@5.59:aAA3IrFE@4/54-Mass-and-Weight
- Step 2
Find an Interactive Feature

## Screenshots
![screen shot 2017-09-26 at 8 51 23 am](https://user-images.githubusercontent.com/12631203/30864173-8639fa80-a298-11e7-90b0-552fcc1fa9d9.png)

# Environment:

- **Browser**: Google Chrome

 
- **Frequency of occurrence**:  High

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1
