### ISSUE TITLE
Assignable Webview: Problem Solving Strategy: "Note"

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#337]
# Scenario
Problem solving features say "Note:" in Webview 

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**: https://staging.cnx.org/contents/1Q9uMg_a@5.59:mJu6YvwH@4/35-Free-Fall
- **How many times were you able to reproduce the issue?** 

## Steps to reproduce:

- Step 1 
Go to any module in https://staging.cnx.org/contents/1Q9uMg_a@5.59:mJu6YvwH@4/35-Free-Fall
- Step 2
Find a problem solving feature

## Screenshots
![screen shot 2017-09-26 at 9 00 44 am](https://user-images.githubusercontent.com/12631203/30864494-63e9a04c-a299-11e7-9e2b-55742a7bb50d.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**:  Google Chrome

# Impact

- **Frequency of occurrence**:  High

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1
