### ISSUE TITLE
Assignable Webview: Back Button Issues

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#338]
# Scenario
When the back button is clicked after being directed to something by a link, the back button does not direct the user back to the previous page. It takes the user back two pages.

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**:  https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- **How many times were you able to reproduce the issue?** 5/5

## Steps to reproduce:

- Step 1 
Go to any module in https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and- 
- Step 2
Click on a linked equation/figure/table link
- Step 3
After being redirected, click the Back button

## Screenshots

N/A

# Environment:

- **Instance**:
- **OS**:
- **Browser**:  Google Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**: high

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1
