### ISSUE TITLE
Assignable Webview: Support email address

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#339]
# Scenario
The email address in the Attributions tab says partners@openstaxcollege.org  not support@openstax.org.

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**: https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- **How many times were you able to reproduce the issue?** many

## Steps to reproduce:

- Step 1
Go to any module in: https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- Step 2
Go to the attributions tab
- Step 3

## Screenshots

![screen shot 2017-09-26 at 9 15 05 am](https://user-images.githubusercontent.com/12631203/30865134-644dfc8e-a29b-11e7-8b22-9556dd2c264f.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**:  Google Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**: high

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1
