### ISSUE TITLE
TOC isues on webview

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#34]
The spans are showing as text
The elements with a drop down functionality aren't being populated
The second level of the list doesn't pull data from the cooked TOC (this is also true for the page titles)

Examples of this can be found here:
http://cte-cnx-dev.cnx.org/contents/LEDsXZAc@1.1:PEuUso5_@2/span-xmlnshttpwwww3org1999xhtm

**Comment by reedstrm** [comment]
Helene, the problem is not display - Ed's going to fix that part.  The adapt-single-file issue is  that the titles for the modules and overrides are not being filled in correctly. Could you link to the cooked html, and show where you're expecting the titles to be pulled from?

**Comment by helenemccarron** [comment]
The cooked version can be found here http://mountainbunker.org/~helene/statistics.html. Webview navigation should be retrieving the data from the TOC, including the inner html within links:
`<a href="#"><span>1.1</span> <span> | </span><span>Definitions of Statistics, Probability, and Key Terms</span></a>`
In other terms, only the blue text on the screenshots. 
![2016-06-15_16-30-53](https://cloud.githubusercontent.com/assets/8514591/16098019/9fcac3d2-3316-11e6-90a2-7629a7d4620a.png)

**Comment by philschatz** [comment]
Is this still an issue? I noticed the cnx-archive ToC contains the escaped HTML: 

![image](https://cloud.githubusercontent.com/assets/253202/19948115/6b91580a-a121-11e6-968d-fd02f6d82b0a.png)

http://archive-cte-cnx-dev.cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6%4011.330

**Comment by helenemccarron** [comment]
Nope, closing
