### ISSUE TITLE
Assignable Webview: TOC Not Bold

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#340]
# Scenario
Chapter number in TOC and page title should be in bold font but are not.

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**: https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- **How many times were you able to reproduce the issue?** constant

## Steps to reproduce:

- Step 1
Go to: https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- Step 2
Click on the TOC

## Screenshots

![screen shot 2017-09-26 at 9 18 46 am](https://user-images.githubusercontent.com/12631203/30865363-f7f0429e-a29b-11e7-9bd1-0ebc078e992f.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**: Google Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**: high

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1
