### ISSUE TITLE
Assignable Webview:  Summary Toggle Duplication

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#341]
# Scenario
When the summary toggle is clicked (it's clickable) the duplicated content appears.

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**: https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- **How many times were you able to reproduce the issue?** constant

## Steps to reproduce:

- Step 1 
Go to any module in: https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- Step 2
Click the Summary Toggle at the top of the content.

## Screenshots
![screen shot 2017-09-26 at 9 23 03 am](https://user-images.githubusercontent.com/12631203/30865534-856634f8-a29c-11e7-8b64-803f0a499c79.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**: Google Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**: high

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1 (summary toggle no longer appears)
