### ISSUE TITLE
Assignable Webview: Equation numbers not on same line as equation

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#342]
# Scenario

Equation numbers are not on the same line as equations.

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**: https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- **How many times were you able to reproduce the issue?** 

## Steps to reproduce:

- Step 1
Go to any module in https://staging.cnx.org/contents/1Q9uMg_a@5.59:Ej8o3nbb@5/32-Instantaneous-Velocity-and-
- Step 2
Search for an equation.

## Screenshots

![screen shot 2017-09-26 at 9 27 14 am](https://user-images.githubusercontent.com/12631203/30865709-f5b6ccb8-a29c-11e7-9275-8252e71cecf3.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**:  Google Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**: high

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1
