### ISSUE TITLE
Assignable Webview: Footnote links to Reference

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#343]
# Scenario

Footnotes are not clickable. There is only one in all of University Physics Volume 1.

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**: https://staging.cnx.org/contents/1Q9uMg_a@5.59:r3A2YRIg@4/173-Sound-Intensity
- **How many times were you able to reproduce the issue?**  1

## Steps to reproduce:

- Step 1 Go to: https://staging.cnx.org/contents/1Q9uMg_a@5.59:r3A2YRIg@4/173-Sound-Intensity
- Step 2 Find the footnote and try to click it.

## Screenshots

![screen shot 2017-09-26 at 9 56 59 am](https://user-images.githubusercontent.com/12631203/30867287-28dbf1b4-a2a1-11e7-8521-3aa0cdbcf04b.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**:  Google Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**:  1

**Comment by kerwinso** [comment]
Discussed with Britt, this looks like a content issue (not code). In the prod PDF, this footnote is also not hyperlinked:

![image](https://user-images.githubusercontent.com/11298165/30873053-96d16130-a2b1-11e7-93f4-ceac67830828.png)
