### ISSUE TITLE
Assignable Webview: Spacing in EOC Questions

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#344]
# Scenario

There are extra spaces in even numbered problems only.

# Reproducibility Details

- **Impact area**: 
- **User**: 
- **URL / Location**:  https://staging.cnx.org/contents/1Q9uMg_a@5.59:YYRm2YA3@5.59/Chapter-Review
- **How many times were you able to reproduce the issue?** many

## Steps to reproduce:

- Step 1 Go to any chapter in the collection holding: https://staging.cnx.org/contents/1Q9uMg_a@5.59:YYRm2YA3@5.59/Chapter-Review
- Step 2
Go to the Chapter Review section and scroll to the Conceptual Questions section.

## Screenshots

![screen shot 2017-09-26 at 10 30 00 am](https://user-images.githubusercontent.com/12631203/30869078-e940aaea-a2a5-11e7-9fab-fedced4ac3db.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**:  Google Chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**: high

**Comment by kerwinso** [comment]
No longer an issue, fixed after deploying https://github.com/Connexions/webview/releases/tag/v0.23.1

![image](https://user-images.githubusercontent.com/11298165/30873106-bfcdec7a-a2b1-11e7-8f2f-a33eebc0d2ee.png)
