### ISSUE TITLE
CSS comments should include the recipe name

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-recipes#345]
Currently they contain snippets which are not super-useful. It should say the name of the recipe instead.

**Comment by kerwinso** [comment]
This will be helpful in the content status tool, which links to the actual contents of the recipe.

**Comment by openstaxalina** [comment]
The exit criteria has already been met via other work.  I am going to close this.

<img width="1440" alt="screen shot 2018-08-05 at 5 07 15 pm" src="https://user-images.githubusercontent.com/7863733/43690591-238796fa-98d2-11e8-8c0b-d066137aebcb.png">
