### ISSUE TITLE
TEA Books => Space between problem number and period

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#350]
# Scenario
In TEA Stats, there is an error in the end of chapter materials where a space is inserted after the number before the period.

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/31730740-7d7cff66-b3f8-11e7-8e4c-49fb17e9c9c4.png)

# Environment:

- **Instance**: Production
- **OS**: macOS
- **Browser**: Chrome, Firefox

**Comment by elenafournier** [comment]
Hello,
This issue has been fixed on production.  Could you please confirm? Thank you.

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/33279202-62fcc380-d363-11e7-902a-207485da9a33.png)
