### ISSUE TITLE
TEA Books => Text wrapping broken in Statistics

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#351]
# Scenario

TEA Statistics, 2.4 Box Plots, Introduction, text wrapping is broken. The grey portion is running outside of the content window.

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/31738267-b6d5df8c-b40f-11e7-944c-d9fba0072a15.png)

# Environment:

- **Instance**: Production
- **OS**: macOS
- **Browser**: Chrome, Firefox

**Comment by elenafournier** [comment]
Hello, 
This has been fixed on production.  Could you please confirm?  Thank you.

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/33279123-19d14e88-d363-11e7-82ad-8bdae95a1d4f.png)
