### ISSUE TITLE
TEA Books => Editor issues on texasgateway.org

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#352]
# Scenario
The content team is running into a variety of issues when attempting to use the content editor on texasgateway.org such as difficulty editing near equations, not presenting a wysiwig editing view and only showing full source editing, and content appearing incorrect after editing.

# Reproducibility Details

- **Impact area**: Editor
- **User**: openstax@texasgateway.org
- **URL / Location**: texasgateway.org
- **How many times were you able to reproduce the issue?** 

## Steps to reproduce:

Editing near an equation:
> I was trying to replace the period with a colon in a sentence.
>
> Here is what I did 
> 1. Opened content to edit per usual process.  
> 2. When I clicked on the sentence to edit it, “2x” appeared randomly in front of the first equation (2xy=3+2x)
> 3. I tried to delete “2x” but when I did so, I lost the math formatting and the equation jumped to inline.
> 4. I “cancelled” the edits.
> 5. When I viewed the page again, the equation read “y=3+”.  The 2x disappeared from the equation entirely.
> 6. I then took the attached video which shows me trying to make the correction two separate times.  Note at 1:24, when the “2x” appears, I didn’t type it.  It pops up on its own.
> 7. Even when the “2x” appears in the editor, once I saved, I could not see it when viewing the content.
> 8. I elected to completely re-type the equation.  However, this disrupted the formatting.
> 
> Editing the font size/style in the editor does not seem to work.  In fact, sometimes when I selected a bigger font, the equation got smaller.  I corrected the equation as best I could; however, this will prove extremely cumbersome for any future updates to this content.

## Screenshots

Editing near an equation:
![2017-10-18_15-35-15-1](https://user-images.githubusercontent.com/12678235/31741722-dc17fc3e-b41a-11e7-81db-7cf2ff5a5083.gif)

No WYSIWYG (https://www.texasgateway.org/dashboard/resources/step-two/296336/297616):
![2017-10-18_15-42-57](https://user-images.githubusercontent.com/12678235/31741880-7ba9645e-b41b-11e7-899e-ade17afa79f6.gif)

# Environment:

- **Instance**: Production
- **OS**: macOS
- **Browser**: Chrome

**Comment by chcase** [comment]
@Stackblocks  This ended up being two issues:

1. The fix for the math equation has been fixed on staging and will be released in the next release.  Currently scheduled for evening of Wed 1/1/17.

2. Editing the wysiwyg has been updated and fixed on production.  You should be able to see that on production now.  Was due to the large volume of characters in the html.  

We'll let you know once the release has been confirmed on production.

**Comment by elenafournier** [comment]
Hello, could you please confirm this on production?  Thank you.

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/33281799-14ddd7d0-d36c-11e7-9279-d7d357bc7b0e.png)
![image](https://user-images.githubusercontent.com/12678235/33281805-18fee2d2-d36c-11e7-9f3a-b36edae88579.png)
