### ISSUE TITLE
TEA Books => AP Reserved symbol superscript breaking in searched titles

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#356]
# **Description of the issue**
When you search for OpenStax and select Book as the content type the AP books have their Registered ®️ symbol superscript tags exposed. We cannot remove the tags since the manner of display is strictly regulated.

# **Screenshots**
![image](https://user-images.githubusercontent.com/12678235/32237019-d2b66de4-be31-11e7-986f-8ba063219fd3.png)

# **Impact**
-   Search Content

# **Priority**
-   High

**Comment by elenafournier** [comment]
Hello, we released the fix on production.  Could you please confirm? Thank you.

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/33279062-e712d160-d362-11e7-88ac-98f90084dcb8.png)
