### ISSUE TITLE
TEA Books => Editor not reflecting changes from numeric list to alpha list

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#357]
# Scenario

Content manager replaced markup to convert numeric lists to alpha lists, but the lists remained numeric in the display.

# **Screenshots**
![image](https://user-images.githubusercontent.com/12678235/32508164-10561c3a-c3af-11e7-9975-0945b9fa41d2.png)
![image](https://user-images.githubusercontent.com/12678235/32508167-13d66504-c3af-11e7-90f2-40f506e7ec3f.png)

# **Impact**
-   Editor

**Comment by elenafournier** [comment]
Hello, 
The fix for this bug has been released to production as of last night.  Could you please confirm?  Thank you,
Elena
