### ISSUE TITLE
TEA Books => TEA AP® Physics 2 is not appearing in the content editor

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#360]
# Scenario

On the production instance of the gateway we can search for and return `TEA AP® Physics 2: Algebra-Based` using the main search on the site, but in the content editor we are unable to return it by searching for Openstax, searching for the title of the book (full or partial) or simply filtering the library by book.

# Reproducibility Details

- **Impact area**: Production Gateway
- **User**: openstax@texasgateway.org
- **URL / Location**: texasgateway.org

## Steps to reproduce:

- Access texasgateway.org
- Click the Search link and enter TEA AP® Physics 2: Algebra-Based (results returned)
- Open the Content Editor & repeat the search (no results)

## Screenshots

![image](https://user-images.githubusercontent.com/12678235/33495448-23baf828-d68c-11e7-9df6-5f5938f3f288.png)

![image](https://user-images.githubusercontent.com/12678235/33495453-28ea4452-d68c-11e7-8475-f255b0315585.png)

**Comment by elenafournier** [comment]
Hello,
Apparently, TEA had temporarily assigned authorship to one of their employees, Tammy Brite, to facilitate easier editing for such a large content. We have the ability to change the author back to OpenStax. However, before we do that, please  reach out to Kathy Ferguson at TEA to coordinate access privileges and the editing process. Please let us know once you have come up with a decision.  Thank you.

**Comment by Stackblocks** [comment]
Thanks for investigating that for us. We will follow up with the TEA in our next report & will follow up here once a decision is reached.

**Comment by elenafournier** [comment]
The other alternative which was suggested is to give Tammy Brite the login info for openstax@texasgateway.org. This way, we can change the author back to OpenStax.  We think this will solve the issue.  Let us know, please.

**Comment by elenafournier** [comment]
FYI - TEA agreed to change the author back to Openstax for now while  both parties are waiting to discuss a permanent solution.  Please confirm that you are able to search for it under Openstax. Thank you.

**Comment by elenafournier** [comment]
Good morning, 
Would it be ok to go ahead and close this ticket in our Jira system? Thanks.

**Comment by Stackblocks** [comment]
@elenafournier That would be fine. I'll close the issue on this end as well, and if there are any updates that impact us both I will reach out to you.
