### ISSUE TITLE
TEA HS Stats --> STAAR formatting needs to be applied to appendices

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#361]
# Scenario
The STAAR formatting should be applied to answer choices.  STAAR formatting includes capital, bolded letters.  This formatting was applied in chapter content, but not in appendices.  This formatting needs to be applied in appendices.

# Reproducibility Details

- **Impact area**: Appendices in TEA HS Stats.  _**There aren't any multiple choice exercises in other TEA titles, but up to @helenemccarron whether you apply this globally or specifically to HS Stats**._
- **User**: any
- **URL / Location**: https://www.texasgateway.org/resource/review-exercises-ch-3%E2%80%9313?book=297701
- **How many times were you able to reproduce the issue?** multiple

## Steps to reproduce:

- Step 1 Navigate to above URL
- Step 2 Note that the answer choices in the exercises use non-bolded, lowercase formatting with a period, rather than STAAR formatting, which is uppercase, bold, without a period. 

## Screenshots
The below screenshot shows STAAR formatting correctly applied in chapter content:
![staar formatting in gateway](https://user-images.githubusercontent.com/7863733/33733966-03dec6f0-db51-11e7-96a0-89ad62b9a7d7.png)

# Environment:
texasgateway.org
- **Instance**: production
- **OS**: any
- **Browser**: any

# Impact

- **Severity**: high to med
- **Frequency of occurrence**: all exercises in Appendices

**Comment by helenemccarron** [comment]
The CSS in the Gateway should be updated using the following code:

```
/* appendix STARR styling - this applies to all appendices alpha lists */
 .appendix-container ol[type="a"] {
    list-style-type: none;
    counter-reset: listAlphaCounter;
    margin-left: 2em;
}

 .appendix-container ol[type="a"] > li {
    counter-increment: listAlphaCounter;
    /*for testing only*/ display: block;
}

 .appendix-container ol[type="a"] > li:before {
    content: counter(listAlphaCounter, upper-alpha);
    font-weight: bold;
    display: inline-block;
    position: absolute;
    left: 4.5em;
}
```

**Comment by helenemccarron** [comment]
To test:
![2017-12-08_11-08-49](https://user-images.githubusercontent.com/8514591/33776817-37ce4ea6-dc08-11e7-86f8-13765b131531.png)

**Comment by openstaxalina** [comment]
Can we apply STAAR format to all alpha lists in all appendices for all TEA titles?  Yes

- AP Bio: no appendices
- HS Physics: no alpha lists in appendices
- AP Macro and AP Micro: no alpha lists in appendices
- AP Physics 1 & 2: no alpha lists in appendices
- HS Stats: all alpha lists in appendices can be STAAR format

cc @helenemccarron

**Comment by Stackblocks** [comment]
@helenemccarron After inserting the changes into the site CSS locally, the appendix lists match up with the STAAR formatting in the chapter content, so it looks good to me.

![image](https://user-images.githubusercontent.com/12678235/33852239-5c672890-de7f-11e7-8f89-420fdacabbc5.png)

**Comment by elenafournier** [comment]
Hello, thank you for sending this over. For some reason, it did not create a Jira ticket on our end.  I believe that it should be assigned to Christine Case when the ticket is created so that the trigger will work. Could you please try assigning it to her?  If that does not work, I can manually copy it in Jira so that our developer can work on it.  Thank you.

**Comment by helenemccarron** [comment]
@elenafournier I have assigned Christine, please let me know if you need anything else.

**Comment by elenafournier** [comment]
Thanks @helenemccarron. It still did not come through so I will create it manually in Jira.

**Comment by openstaxalina** [comment]
@elenafournier thank you!  This has been confirmed.  I will leave this issue open for @Stackblocks to review and close.  However, no further work is needed at this time.  Happy holidays!

<img width="1108" alt="screen shot 2017-12-21 at 4 34 26 pm" src="https://user-images.githubusercontent.com/7863733/34277813-f8608e22-e66c-11e7-9a73-5557e6aaa14e.png">
<img width="1143" alt="screen shot 2017-12-21 at 4 34 45 pm" src="https://user-images.githubusercontent.com/7863733/34277814-f86dedec-e66c-11e7-897e-cc369c8cb099.png">
