### ISSUE TITLE
TEG - Can't unitalicize text in WYSIWYG

### ISSUE THREAD

**Issue by lwtchu** [Connexions/cnx-recipes#371]
# Scenario

Tried to unitalicize something in AP Bio in the WYSIWYG. It doesn't do anything so I have to go into full source. Please see if you've filed this bug with them...if you have close and ignore this issue.

# Reproducibility Details

- **Impact area**:  Texas Education Gateway
- **User**:  
- **URL / Location**: https://www.texasgateway.org/dashboard/resources/step-two/316181/318336 "Biology is a science" paragraph: change "knowledge" to ""knowledge"" (roman + double quotes)
- **How many times were you able to reproduce the issue?**  1? Need to find another instance.

## Steps to reproduce:

- Step 1 Go to edit.
- Step 2 Try to un-italicize something.
- Step 3 It doesn't work unless you go into full source.

## Screenshots

(_attach here_)

# Environment:

- **Instance**: Gateway
- **OS**: macOS high sieerrra 10.13.1
- **Browser**: chrome

# Impact

- **Severity**:  low
- **Frequency of occurrence**:  low

**Comment by elenafournier** [comment]
Hello,
I am not able to reproduce the issue. Each time you make a change within the WYSIWYG, are you making sure you are hitting SAVE within the WYSIWYG editor window before you hit the blue "SAVE" button that let's you move to the next section of the Overview?
