### ISSUE TITLE
start="#" attribute in lists do not work

### ISSUE THREAD

**Issue by lwtchu** [Connexions/cnx-recipes#373]
# Scenario
The `start="#"` attribute in `<ol>` tags are not working. The screenshot below is the HTML and the following screenshot is the output - it should be D & E.

# Reproducibility Details

- **Impact area**: Texas Education Gateway
- **User**:  
- **URL / Location**:  https://www.texasgateway.org/dashboard/resources/step-two/316506/319236
- **How many times were you able to reproduce the issue?** 
Twice on that page.

## Steps to reproduce:

- Make `<ol start="3" type="A">` list in the HTML and hit save.

## Screenshots

![screen shot 2018-01-09 at 12 39 12 pm](https://user-images.githubusercontent.com/11299125/34737066-96e407f0-f53a-11e7-8645-7b6611fa4650.png)
![screen shot 2018-01-09 at 12 50 16 pm](https://user-images.githubusercontent.com/11299125/34737396-a8b545c4-f53b-11e7-8516-a214ed672056.png)

# Environment:

- **Instance**: 
- **OS**: MacOS
- **Browser**:  Chrome

**Comment by elenafournier** [comment]
Hello, this was fixed on prod on our last release.  Could you please confirm? 
- thanks

**Comment by openstaxalina** [comment]
Verified.  Thank you!

**Comment by openstaxalina** [comment]
Issue moved to [openstax/tea-teg #2](https://github.com/openstax/tea-teg/issues/2) via [**ZenHub**](https://www.zenhub.com/)
