### ISSUE TITLE
Improper text wrapping around exercise figures

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#388]
Question text wraps incorrectly in some exercises that start with images:

---

![screen shot 2018-05-04 at 3 21 02 pm](https://user-images.githubusercontent.com/28710954/39650856-61a2246c-4faf-11e8-9678-827061a2287a.png)
---
![screen shot 2018-05-04 at 3 20 48 pm](https://user-images.githubusercontent.com/28710954/39650857-61afbb18-4faf-11e8-98e4-d542fccf7194.png)

**Comment by lwtchu** [comment]
https://github.com/Connexions/webview/issues/1636 moved
