### ISSUE TITLE
"f" appearing in Visual Connection

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#389]
First visual connection in Section 1.1 has an "f" at the beginning of the question, following the figure.

---

### Previously:
![screen shot 2018-05-02 at 11 38 04 am](https://user-images.githubusercontent.com/28710954/39536841-687c66ac-4dfd-11e8-8bf4-cc3939a98383.png)

--- 
### Now:
![screen shot 2018-05-02 at 11 38 25 am](https://user-images.githubusercontent.com/28710954/39536840-6865d4dc-4dfd-11e8-91ee-2c1eb00203a4.png)

---
### The question content is being drawn from Tutor.
![screen shot 2018-05-02 at 11 39 53 am](https://user-images.githubusercontent.com/28710954/39536919-a5d379c8-4dfd-11e8-8c9c-b1286fbf6d53.png)

**Comment by openstaxalina** [comment]
This is assessment 1 in Exercises.  I reviewed all versions and did not find any that contained the letter "f" in that position.  It may be worth rebaking the book to see if this issue occurs again (?).  cc @Stackblocks @helenemccarron 

<img width="1440" alt="screen shot 2018-07-09 at 1 29 57 pm" src="https://user-images.githubusercontent.com/7863733/42469078-4dae00b0-837c-11e8-87ab-eaef93313c02.png">

**Comment by PatBoj** [comment]
@helenemccarron I have a problem with featching this book.

```
patboy@Destroyer:~/Dokumenty/github/cnx-recipes$ sudo USER=patryk ./script/fetch-html apbiology
==> Activating Python virtualenv ... OK
==> DEPRECATED: Setting correct node version using nvm. Try using https://github.com/nodenv/nodenv instead (add it to Brewfile) ... OK
==> Fetching apbiology from tea.cnx.org (~20 minutes if it has exercises) ... 
patryk@tea.cnx.org: Permission denied (publickey).
./script/fetch-html: ERROR: could not run [ssh patryk@tea.cnx.org [ -e ${HOME}/temp.internal.epub ] && rm ${HOME}/temp.internal.epub; [ -e ${HOME}/temp.xhtml ] && rm ${HOME}/temp.xhtml; /var/cnx/venvs/publishing/bin/cnx-archive-export_epub /etc/cnx/publishing/app.ini 27cf60e4-bd82-418a-a7bb-a939c40f8f50 ${HOME}/temp.internal.epub && /var/cnx/venvs/publishing/bin/cnx-epub-single_html --exercise_host exercises.openstax.org --mathmlcloud_url http://mathmlcloud.cnx.org:1337/equation/ ${HOME}/temp.internal.epub > ${HOME}/temp.xhtml]
```
I thnik it's problem with host name in file `books.txt`.
![image](https://user-images.githubusercontent.com/20907906/42499307-b70a9570-842e-11e8-9d43-f888e788509d.png)

My question is: how can I bake this book?

**Comment by helenemccarron** [comment]
Per Dante: "seems like the `f` is in https://exercises-dev.openstax.org/api/exercises/1 which means devb.cnx.org is probably pointing at exercises-dev instead of prod". He will change the exercise on exercises-dev.

**Comment by openstaxalina** [comment]
We will change cnx-deploy to point to Exercises (prod) instead.
