### ISSUE TITLE
Figure numbering shows two numbers (and the bold restarts at 1 on every page)

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#391]
![different figure numbers](https://user-images.githubusercontent.com/33228728/39327743-8e73b80e-495e-11e8-9883-3ed60302e208.jpg)

**Comment by helenemccarron** [comment]
This looks like the book is either unbaked or cached.

**Comment by Stackblocks** [comment]
Cannot locate / reproduce. Closing issue.
