### ISSUE TITLE
Lines on Example boxes not consistent

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#393]
![example double lines](https://user-images.githubusercontent.com/33228728/39324728-d0a914d4-4955-11e8-8518-20ad5bc15708.jpg)

**Comment by lwtchu** [comment]
@Stackblocks this might be due to the fact that there's an exercise embedded in the example. the second line is for the exercise

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/webview #1639](https://github.com/Connexions/webview/issues/1639) via [**ZenHub**](https://www.zenhub.com/)
