### ISSUE TITLE
Answer key has no line breaks

### ISSUE THREAD

**Issue by nicolasdamiani** [Connexions/cnx-recipes#398]
Answer key doesn't have any line breaks, making it one big block of text.
![screen shot 2018-05-21 at 1 44 12 pm](https://user-images.githubusercontent.com/28710954/40324512-5678977c-5cfe-11e8-9b19-1a1de21a422f.png)

**Comment by tomjw64** [comment]
at first glance, this is a styling issue rather than a recipe issue.

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/webview #1644](https://github.com/Connexions/webview/issues/1644) via [**ZenHub**](https://www.zenhub.com/)
