### ISSUE TITLE
Inconsistent spacing between number and first word of question, in Problems & Exercises

### ISSUE THREAD

**Issue by hwangange** [Connexions/cnx-recipes#403]
There are seemingly sporadic instances where no space exists between a question's number and first word. Like question 20 in Ch. 2 Kinematics, Problems & Exercises. 
<img width="852" alt="screen shot 2018-05-21 at 3 54 28 pm" src="https://user-images.githubusercontent.com/12180288/40329472-4497bb1c-5d0f-11e8-8343-a5157eb41879.png">

And question 26 (also Ch. 2).
<img width="737" alt="screen shot 2018-05-21 at 3 54 58 pm" src="https://user-images.githubusercontent.com/12180288/40329499-56f6bbb4-5d0f-11e8-82c1-c9e98ff81c24.png">

And question 59 (also Ch. 2).
<img width="142" alt="screen shot 2018-05-21 at 3 55 27 pm" src="https://user-images.githubusercontent.com/12180288/40329521-6704d888-5d0f-11e8-915b-58089007dc6f.png">

And questions 13-16, Ch.3 Two-Dimensional Kinematics, Conceptual Questions.

<img width="462" alt="screen shot 2018-05-21 at 4 01 16 pm" src="https://user-images.githubusercontent.com/12180288/40329767-3d836528-5d10-11e8-9c13-e6d96a299a16.png">

also in Ch.3 Test Prep, etc.

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/webview #1650](https://github.com/Connexions/webview/issues/1650) via [**ZenHub**](https://www.zenhub.com/)
