### ISSUE TITLE
Space between last term and period in a sentence

### ISSUE THREAD

**Issue by hwangange** [Connexions/cnx-recipes#405]
Ch. 6 (Gravitation and Universal Circular Motion): Section Summary

There is a space between the end of the gravitational constant and the period. 

<img width="824" alt="screen shot 2018-05-21 at 4 35 12 pm" src="https://user-images.githubusercontent.com/12180288/40331150-fbc4528c-5d14-11e8-93df-bde0aa6de201.png">

As a result, the period occupies a new line.

**Comment by lwtchu** [comment]
Might be due to math not being wrappable. We can move to see if there's a potential fix.

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/webview #1649](https://github.com/Connexions/webview/issues/1649) via [**ZenHub**](https://www.zenhub.com/)
