### ISSUE TITLE
Custom bullet point list error

### ISSUE THREAD

**Issue by jonathan-uba** [Connexions/cnx-recipes#406]
In Chapter 21.1, there is an error in the bullet point list for the Virus Classification by Genome Structure table.
![biology 2e error](https://user-images.githubusercontent.com/39272234/40331801-1dac4498-5d17-11e8-9d3e-b0ecc1f15d27.jpg)

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/webview #1647](https://github.com/Connexions/webview/issues/1647) via [**ZenHub**](https://www.zenhub.com/)
