### ISSUE TITLE
Programmatically Add Table Number, Title, and Caption to Table Summary

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#407]
# Scenario
In developing & reviewing the guidelines for writing table summaries, Phil brought up a good point that we could automate placing the table number, title, and caption into the table summary rather than requiring content editors to do so. 

# Reproducibility Details

- **Impact area**: Table elements
- **User**: any
- **URL / Location**: various 
- **How many times were you able to reproduce the issue?** N/A

## Steps to reproduce:

- Step 1 - Navigate to a table
- Step 2 - Place a space in the summary element of the table and save/publish the module.  Ensure that the table is numbered and has a title and caption.  
- Step 3 - Allow the book to bake
- Step 4 - Inspect the html and ensure that the table number, title, and caption have been automatically placed in the summary element.
- Step 5 - With a screenreader, verify that the table number, title, and caption can be read in the summary.

## Screenshots
N/A

# Environment: CNX

- **Instance**: any
- **OS**: any
- **Browser**: any 

# Impact

- **Severity**: N/A
- **Frequency of occurrence**: frequent/all numbered tables

**Comment by brittany-johnson** [comment]
![screen shot 2018-06-07 at 12 02 32 pm](https://user-images.githubusercontent.com/24909007/41114786-0e4eb2e2-6a4b-11e8-952c-72eb17b2424a.png)

@Stackblocks

**Comment by Stackblocks** [comment]
Table Number & Summary showing correctly, but Title needs to be included.

![image](https://user-images.githubusercontent.com/12678235/41118729-70a73940-6a56-11e8-931d-d1ba12b14aca.png)

**Comment by helenemccarron** [comment]
@Stackblocks (cc @openstaxalina )I don't think we should support tables with titles in the first header row at the moment, only when the title is part of the caption (ie when the caption and the title tags are used in the content). The current functionality supports that already. I am working on supporting title top tables (https://github.com/Connexions/cnx-recipes/pull/418) which will require content change to be fully operational (namely, to populate the title tag so it can be used appropriately). Alina, are you ok to release this version first and keep working on tables with fake titles?

**Comment by openstaxalina** [comment]
@helenemccarron yes, this sounds good.  We do not need to bring the title from the header row into the summary.  We only need to bring in the title if it was placed in a < title > tag.
