### ISSUE TITLE
Figure & Table Text not confined within section 

### ISSUE THREAD

**Issue by JoseEscalante6** [Connexions/cnx-recipes#408]
The table in Chapter 13 Linear Regression and Correlation Section 4 The Regression Equation causes the Figure text included within Example 13.5 to appear outside of the box it is supposed to be within. 

![screenshot 19](https://user-images.githubusercontent.com/30252254/40331947-c57433e8-5d17-11e8-9dd1-e55c4062af48.png)

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/webview #1648](https://github.com/Connexions/webview/issues/1648) via [**ZenHub**](https://www.zenhub.com/)
