### ISSUE TITLE
Vertically stretched image

### ISSUE THREAD

**Issue by hwangange** [Connexions/cnx-recipes#410]
<img width="374" alt="screen shot 2018-05-22 at 9 39 14 am" src="https://user-images.githubusercontent.com/12180288/40369641-03749764-5da4-11e8-8129-536cc55f3482.png">

Section 13.6 - Humidity, Evaporation, and Boiling

Image still appears stretched no matter how I resize the browser.

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/webview #1651](https://github.com/Connexions/webview/issues/1651) via [**ZenHub**](https://www.zenhub.com/)
