### ISSUE TITLE
Different font in table

### ISSUE THREAD

**Issue by hwangange** [Connexions/cnx-recipes#411]
<img width="915" alt="screen shot 2018-05-22 at 9 43 34 am" src="https://user-images.githubusercontent.com/12180288/40369892-a268b2c4-5da4-11e8-85ba-d545bb5031da.png">

Section 14.6 Convection

Font is different; typically table cells containing values that aren't equations, have the same font as paragraph text.

**Comment by lwtchu** [comment]
This is due to math being used.
