### ISSUE TITLE
Missing white spaces between numbers and text.

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#426]
# Scenario

In Critical Thinking Questions part of the book in the numbered area there is white space just in the four first points between number and the sentence.

# Reproducibility Details

- **URL / Location**: https://devb.cnx.org/contents/GFy_h8cu@10.120:HT3cB5gC@10.120/Critical-Thinking-Questions

## Screenshots

![space](https://user-images.githubusercontent.com/40228854/41791790-6cb62482-761c-11e8-8a70-c96c9de2f92c.JPG)

**Comment by helenemccarron** [comment]
This is not a recipe issue, the content does not contain extra spaces.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1722](https://github.com/Connexions/webview/issues/1722) via [**ZenHub**](https://www.zenhub.com/)

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1723](https://github.com/Connexions/webview/issues/1723) via [**ZenHub**](https://www.zenhub.com/)
