### ISSUE TITLE
Empty caption in tables

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#434]
@Adrianltd commented on [Tue Jun 19 2018](https://github.com/Connexions/webview/issues/1662)

![image](https://user-images.githubusercontent.com/40228907/41620248-66a8075a-7409-11e8-9275-c0a5c28959aa.png)
There's an empty `<caption></caption>` in each `os-table`. 
The example above  is taken from College Physics For AP® Courses, chapter 1.2

**Comment by Adrianltd** [comment]
@openstaxalina Yes, indeed.

**Comment by wilkus27** [comment]
Verified on katalyst01:

![caption](https://user-images.githubusercontent.com/40228854/43512764-438a78b8-957c-11e8-850b-f7b6b3dcccf7.JPG)
