### ISSUE TITLE
Missing Exercise text in "Critical Thinking Questions" / Biology for AP® Courses

### ISSUE THREAD

**Issue by uskka** [Connexions/cnx-recipes#443]
What: Missing Exercise text in "Critical Thinking Questions" .

Where: Biology for AP® Courses / devb / 29 Critical Thinking Questions 
https://devb.cnx.org/contents/bDIuMp-w@5.1:bbQsJw61@5.1/Critical-Thinking-Questions

![screenshot-devb cnx org-2018 07 06-11-26-47](https://user-images.githubusercontent.com/40228918/42371539-13a22612-8110-11e8-8a3e-965b8a1cf3fb.png)

**Comment by openstaxalina** [comment]
I would like to re-test this once we have the new content from production.  Re-assigned to Stefan for this purpose.

**Comment by openstaxalina** [comment]
@Bkblodget please investigate the markup to determine why this is happening; see assessments 28 and 29 here: https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:IIo-txc1@7.1/Critical-Thinking-Questions

**Comment by wilkus27** [comment]
Rest of pages where this problem occurs:
(1) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:HS_iAAPE@7.1/Test-Prep-for-AP-Courses 

(2) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:OPD5fsd5@7.1/Test-Prep-for-AP-Courses 

(3) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7aYjctTe@5/183-Reconnection-and-Rates-of-  

(4) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:f_wVv68_@7.1/Test-Prep-for-AP-Courses 

(5) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:BbydUv1f@7.1/Review-Questions 

(6) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:-BkPjec3@7.1/Critical-Thinking-Questions 

(7) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:iLVN_ASR@7.1/Test-Prep-for-AP-Courses 

(8) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:LpycqLsc@4/221-Prokaryotic-Diversity 

(9) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:rEmg8NOC@7/222-Structure-of-Prokaryotes 

(10) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:qkjwv_vy@6/261-Neurons-and-Glial-Cells 

(11) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:UU67kyOf@5/262-How-Neurons-Communicate 

(12) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:Al-ibn3C@5/263-The-Central-Nervous-System

(13) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:pA1TThgZ@7.1/Review-Questions

(14) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:iW_8hnMU@7.1/Critical-Thinking-Questions

(15) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:gtw7SXg2@5/292-Bone

(16) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:0YebG23k@7.1/Review-Questions

(17) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:IIo-txc1@7.1/Critical-Thinking-Questions

(18) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:lm2MnLhW@5/313-Mammalian-Heart-and-Blood-

(19) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7X47BpBW@7.1/Critical-Thinking-Questions

(20) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:L6qlqtIh@7.1/Review-Questions

(21) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:MO-67niO@7.1/Critical-Thinking-Questions

(22) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:SRbLt9G2@4/334-Disruptions-in-the-Immune-

(23) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:bo0kDUgK@7.1/Review-Questions

(24) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:tILu-YHY@7.1/Critical-Thinking-Questions

(25) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:OCP4ZSZ7@7.1/Test-Prep-for-AP-Courses

(26) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:NPu7dKPm@7.1/Review-Questions

(27) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:zM1B5uqY@7.1/Critical-Thinking-Questions

(28) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:kxMR6ORY@7.1/Test-Prep-for-AP-Courses

(29) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:ZKBrqg0K@7.1/Review-Questions

(30) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:cHn7ZRRA@7.1/Critical-Thinking-Questions

(31) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:GKQdm6Y0@6/361-Population-Demography

(32) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:OhgzZG6c@5/365-Human-Population-Growth

(33) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:qck8D2cX@7.1/Review-Questions

(34) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:CDsPgSI2@7.1/Critical-Thinking-Questions

(35) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:L83CoCZG@7.1/Test-Prep-for-AP-Courses

(36) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:UhPTXSfQ@7.1/Test-Prep-for-AP-Courses

(37) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:8nkPwMxi@4/383-Threats-to-Biodiversity

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/content-managers #193](https://github.com/Connexions/content-managers/issues/193) via [**ZenHub**](https://www.zenhub.com/)
