### ISSUE TITLE
Intro to Business: Exploring Business Careers sub-title is not formatted in bold

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#444]
Chapter 4 - m10048

[https://content02.cnx.org/contents/oJ6xvjEh@1.1:S6CQr29Q@1/Introduction](url)

**XML Coding:**
![image](https://user-images.githubusercontent.com/39794953/42383554-2bf938dc-8155-11e8-8ccb-270e6a0efa33.png)

**Online View:**
![image](https://user-images.githubusercontent.com/39794953/42383626-61a6e9f2-8155-11e8-8ad3-5361b01bb430.png)

The second title in the Exploring Business Careers is not formatted in bold. This comes across common for some of the chapters, which has the second title.

**Comment by openstaxalina** [comment]
For Monday: Larissa should review.  However, I do not think that we can support two titles.

**Comment by lwtchu** [comment]
It's a paragraph title - I think we can do what we did for the PDF here. For all paragraph and list titles, just bold them.

**Comment by openstaxalina** [comment]
@clteam18 please either use a paragraph title element for "Sole Proprietor" or move Jessica MacLean and Sole Proprietor into the same title element.

**Comment by openstaxalina** [comment]
@clteam18 please post a screenshot here and close this issue when this change is complete.

**Comment by clteam18** [comment]
![image](https://user-images.githubusercontent.com/39794953/42821406-1e341010-89f6-11e8-8bd9-4d973442b26b.png)

**Sole Proprietor** is captured within the paragraph title element and now its rendering correctly.
