### ISSUE TITLE
Intro to Business: Preparing for Tomorrow's Workplace Skills

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#445]
Globall for all Chapters

![image](https://user-images.githubusercontent.com/39794953/42384417-8d7f55ee-8157-11e8-91b0-a717edfb747e.png)

Heading "**Preparing for Tomorrow's Workplace Skills**" displays as "**Preparing for Tomorrow's Workplace**", the word "**Skills**" is cut in online view.

**Comment by openstaxalina** [comment]
For Monday: I'm fairly certain this is a quick fix in the recipe.  We changed the title late, and may have only updated the PDF styling.

**Comment by tomjw64** [comment]
![screenshot-1](https://user-images.githubusercontent.com/1285308/42641843-17a078b8-85bb-11e8-9652-84cca92199c0.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9d46c888-0b76-427c-b58e-ed7ee1492b10)
