### ISSUE TITLE
Intro to Business: Critical Thinking Questions

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#446]
Critical Thinking Case - Global for all Chapters

![image](https://user-images.githubusercontent.com/39794953/42384783-8dab4c3e-8158-11e8-96af-29f4e1f14e8e.png)

**Critical Thinking Questions** under the section **Critical Thinking Case** has no space between paragraph and heading.

**Comment by openstaxalina** [comment]
For Monday: Larissa should prioritize.

**Comment by brittany-johnson** [comment]
Styling issue, moving to webview https://github.com/Connexions/webview/issues/1704

**Comment by brittany-johnson** [comment]
Styling issue, moving to webview https://github.com/Connexions/webview/issues/1716
