### ISSUE TITLE
Intro to Business: References - Global

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#447]
**Global for all Chapters**

![image](https://user-images.githubusercontent.com/39794953/42384974-20f8d420-8159-11e8-87fe-4bb05e1cd6b1.png)

There is no separation between the Note numbers and the text in online view.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1700](https://github.com/Connexions/webview/issues/1700) via [**ZenHub**](https://www.zenhub.com/)
