### ISSUE TITLE
Intro to Business: Notes callout not in superscript

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#448]
Global for all Chapters

![image](https://user-images.githubusercontent.com/39794953/42385250-dfd72306-8159-11e8-844a-d273d83b6f64.png)

Notes callout are not in superscript position, seems to be continuation with the paragraph text.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1699](https://github.com/Connexions/webview/issues/1699) via [**ZenHub**](https://www.zenhub.com/)
