### ISSUE TITLE
Intro to Business: unnumbered list displays as bullet style

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#450]
Chapter 17 - m10295

https://content02.cnx.org/contents/W5lkru-C@1.2:sT9pws9t@1/12-Developing-Interpersonal-Sk

**XML Coding:**
![image](https://user-images.githubusercontent.com/39794953/42385910-bcafdeca-815b-11e8-85a3-a87fa628c860.png)

**Online View:**
![image](https://user-images.githubusercontent.com/39794953/42385851-8dd9c390-815b-11e8-8470-70524bb3010b.png)

**bullet-style** attribute value is **none**, however the content is displayed with bullet style.
This comes across few more chapters.

**Comment by helenemccarron** [comment]
moved to webview:  https://github.com/Connexions/webview/issues/1698
