### ISSUE TITLE
Intro to Business: Introduction in Appendix displays as 1.1 A

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#451]
**Appendix - m10302**

https://content02.cnx.org/contents/uVg-ahUk@1.1:anIA8Ogm@1/11-A--Introduction

![image](https://user-images.githubusercontent.com/39794953/42386316-ce071a2a-815c-11e8-94de-5fb4e8635ead.png)

Introduction in Appendix displays with the prefix 1.1 A both in side TOC and heading.

**Comment by openstaxalina** [comment]
@Bkblodget should confirm, but I believe this is a markup issue.  The Appendix should not be in a subcollection.  Each Appendix can only consist of one module.

**Comment by openstaxalina** [comment]
@clteam18 An Appendix can only be only one module, not nested in a sub collection.  We recommend building a full-book collection as soon as possible and placing the appendix at the end of this collection.

**Comment by openstaxalina** [comment]
@clteam18 , please make Appendix A a single module, per email instructions (use section titles for the current module titles).  Please update the bookmap accordingly.

**Comment by clteam18** [comment]
@openstaxalina We have created Appendix as a single module per email instructions and updated the Bookmap accordingly.
