### ISSUE TITLE
Modify answer key's structure

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#454]
In reference to https://github.com/Connexions/webview/pull/1625 and https://github.com/Connexions/webview/pull/1665, the recipes should modify the answer key to allow for better styling and flexibility

**See requirements below**

**Comment by openstaxalina** [comment]
Requirements:
Find a more elegant way for the assessment number and content to appear on the same line.

We need to see what happens to images with this fix.  If the image falls onto the next line, we will need a separate fix for that.

**Comment by PatBoj** [comment]
I've created a separate container for problem (`class="os-problem-container"`) and solution (`class="os-solution-container"`) content.

Before:
![image](https://user-images.githubusercontent.com/20907906/43519144-8d507dd2-958e-11e8-9b6b-cc1ab7a74dba.png)

After:
![image](https://user-images.githubusercontent.com/20907906/43519151-9043d9f8-958e-11e8-8131-a6ccacf84b7c.png)

**Comment by wilkus27** [comment]
Verified on katalyst01, changes connected with recipes display properly:
![number_text](https://user-images.githubusercontent.com/40228854/43531257-b5a42e8e-95af-11e8-9447-c4e5784d6f20.JPG)
