### ISSUE TITLE
Feature type/title text is the same size/font as body text

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#456]
@Stackblocks commented on [Fri Jun 01 2018](https://github.com/Connexions/webview/issues/1641)

@Stackblocks commented on [Tue May 08 2018](https://github.com/Connexions/cnx-recipes/issues/395)

# In College Physics
<img width="925" alt="screen shot 2018-04-26 at 11 54 55 am" src="https://user-images.githubusercontent.com/1895432/39320088-b3aa117e-4948-11e8-94da-89775959f36a.png">

---

@hwangange commented on [Tue May 22 2018](https://github.com/Connexions/cnx-recipes/issues/395#issuecomment-391013936)

# In AP Physics

AP Physics - Section 13.4 Kinetic Theory - Not only is "Check Your Understanding" the same size/font as paragraph text, but it is placed inside the Solution, and not above the stated problem.
<img width="875" alt="screen shot 2018-05-22 at 9 35 24 am" src="https://user-images.githubusercontent.com/12180288/40369384-795b19d6-5da3-11e8-825d-6c0c8cda2a41.png">

--------------------------------------------

Same issue in Section 21.5. Additionally, "Exercise 1" is written underneath "Check Your Understanding" even though this problem can't possibly be both.

<img width="894" alt="screen shot 2018-05-22 at 10 01 14 am" src="https://user-images.githubusercontent.com/12180288/40370969-16c4d90c-5da7-11e8-9828-83582cb4583a.png">

---

@Adrianltd commented on [Tue Jul 03 2018](https://github.com/Connexions/webview/issues/1641#issuecomment-402197068)

![image](https://user-images.githubusercontent.com/40228907/42228414-2e9edb64-7ee4-11e8-9146-2b1f21733457.png)

that's how it looks on devb.cnx.org (it's baked, but I'm not sure if it's baked correctly. @wilkus27 can say more about that). Can you (@Stackblocks ) check that?

---

@wilkus27 commented on [Tue Jul 03 2018](https://github.com/Connexions/webview/issues/1641#issuecomment-402202521)

At the first moment it looks that it's baked:
![phisics](https://user-images.githubusercontent.com/40228854/42229983-1c75f252-7ee8-11e8-8557-149b79425b21.JPG)
But parts of this book are totally different than in other baked one:

Biology (baked):
![ch_outline_biology](https://user-images.githubusercontent.com/40228854/42230091-6c3dabd6-7ee8-11e8-8f28-d8de0ba2dfb5.JPG)

College Phisics:
![ch_outline_phisics](https://user-images.githubusercontent.com/40228854/42230141-855aabe6-7ee8-11e8-8986-8e7821682015.JPG)

---

@helenemccarron commented on [Thu Jul 05 2018](https://github.com/Connexions/webview/issues/1641#issuecomment-402733082)

@Adrianltd can you verify the book is baked properly?

---

@helenemccarron commented on [Thu Jul 05 2018](https://github.com/Connexions/webview/issues/1641#issuecomment-402777730)

@wilkus27 I believe the last screenshot is actually showing the content baked properly. I think it's a separate issue, the chapter outline isn't styled and thus very confusing. I opened an issue here: #1686

---

@helenemccarron commented on [Thu Jul 05 2018](https://github.com/Connexions/webview/issues/1641#issuecomment-402820420)

@Stackblocks can we move this issues to recipes? This is cause because the markup is an exercise with a type of "check your understanding", so it's not supported.

```
    <exercise id="fs-id1589233" type="check-understanding"><label/><title>Check Your Understanding</title>
    <problem id="fs-id2351786">
    <para id="import-auto-id1168465434656">If you consider a very small object such as a grain of pollen, in a gas, then the number of atoms and molecules striking its surface would also be relatively small. Would the grain of pollen experience any fluctuations in pressure due to statistical fluctuations in the number of gas atoms and molecules striking it in a given amount of time?</para>
    </problem>
````

**Comment by wilkus27** [comment]
There were three problematic places with Check Your Understanding header connected with recipes. All of them are displaying correctly now on devb:

Module 13.4 (https://devb.cnx.org/contents/jQSmhtXo@14.60:lU8zWeww@3/134-Kinetic-Theory-Atomic-and-)
![13 4](https://user-images.githubusercontent.com/40228854/42870846-336a5dee-8a79-11e8-8382-4ffb17d2bb4e.JPG)

Module 21.6 (https://devb.cnx.org/contents/jQSmhtXo@14.60:y3HdLx8N@3/216-DC-Circuits-Containing-Res)
![21 6](https://user-images.githubusercontent.com/40228854/42870902-55393184-8a79-11e8-8596-fdd63e8c211e.JPG)

Module 28.2 (https://devb.cnx.org/contents/jQSmhtXo@14.60:ZJSjB88w@3/282-Simultaneity-And-Time-Dila)
![28 2 2](https://user-images.githubusercontent.com/40228854/42871054-b9e7f9f8-8a79-11e8-9108-88b919c58e42.JPG)

**Comment by Stackblocks** [comment]
Closing this issue since it appears everything is now working correctly.
