### ISSUE TITLE
Appropriately label top level pages in the table of contents

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#457]
We cannot correctly style the preface/index differently from the appendices without appropriately labeling them with classes in recipes.

**Comment by openstaxalina** [comment]
This does not require any content changes.

**Comment by openstaxalina** [comment]
Need to determine which books should be included for the initial release of this change.

**Comment by openstaxalina** [comment]
This should not result in any differences on webview.  @Stackblocks please advise what book you want this turned on for.

**Comment by openstaxalina** [comment]
Need to select a book that is already being regression tested in this release.

**Comment by brittweinstein** [comment]
@tomjw64 we are ready to merge. Please apply to University Physics.

**Comment by Stackblocks** [comment]
Because of the way the Table of Contents is handled in Webview, this will have no visible change. Will continue to monitor moving forward as we make other changes and add elements into the BakedPDF system.
