### ISSUE TITLE
Different font size of header "Coverage and Scope"

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#458]
In most of books header "Coverage and Scope" have smaller font size than header "About (...)", e.g.

Introductory Business Statistics (https://devb.cnx.org/contents/tWu56V64@33.86:qtUkyT_U@19/Preface)
![bus_stati](https://user-images.githubusercontent.com/40228854/42496074-43b66fee-8425-11e8-8a6c-d17d7327a22f.JPG)

University Physics Volume 1 (https://devb.cnx.org/contents/1Q9uMg_a@8.1:Gofkr9Oy@9/Preface)
![physics](https://user-images.githubusercontent.com/40228854/42496117-5988ea68-8425-11e8-8e4c-e3f545f314fb.JPG)

But in Biology (https://devb.cnx.org/contents/GFy_h8cu@10.120:fVAf83sY@13/Preface) this headers are the same font size:
![biology](https://user-images.githubusercontent.com/40228854/42496203-97d9b374-8425-11e8-97e9-e952d1d7014a.JPG)

**Comment by openstaxalina** [comment]
This is not an issue on production: https://cnx.org/contents/jVCgr5SL@8.197:2zYFPFKB@7/Preface

Closing this issue.
