### ISSUE TITLE
Additional white spaces between words in columns headers 

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#459]
In parts of tables there are occuring white spaces between words in headers of columns.

Module 2.2 Example 2.16 (https://devb.cnx.org/contents/tWu56V64@33.86:XEZYKVYN@6/22-Measures-of-the-Location-of)
![big_font](https://user-images.githubusercontent.com/40228854/42504914-7ac321f4-843d-11e8-94e2-dbf4105a5ed1.JPG)

Module 1.3 Example 1.17 (https://devb.cnx.org/contents/tWu56V64@33.86:B2ZsQUfk@8/13-Levels-of-Measurement)
![white_space](https://user-images.githubusercontent.com/40228854/42504957-9b8448d2-843d-11e8-8e5d-4180cb4ce76c.JPG)

**Comment by openstaxalina** [comment]
@marcjeannott, would you be able to investigate if there is any difference in the markup between these two instances?  Specifically, we are looking at the line break between "RELATIVE" and "FREQUENCY" in the second instance.  We are also looking at similar line breaks in the header for the next column ("CUMULATIVE RELATIVE FREQUENCY").

**Comment by marcjeannott** [comment]
The tables in 1.3 had a newline tag used in-between the header text. I've removed these newline tags, and the tables appear correctly now.
