### ISSUE TITLE
Example box in Try It box

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#460]
In the whole book Examples and Try It  are occuring as a separate boxes:
E.g:
Module 3.5 (https://devb.cnx.org/contents/tWu56V64@33.86:fCadB1zn@12/35-Venn-Diagrams)
![ex_sep_try](https://user-images.githubusercontent.com/40228854/42517753-c0e49d20-8460-11e8-8115-a1a748185708.JPG)

But here Example is in Try It:
(the same module)
![ex_in_try](https://user-images.githubusercontent.com/40228854/42517810-e97b4324-8460-11e8-9869-53b3e4a7a5e0.JPG)

**Comment by helenemccarron** [comment]
I believe this is working as intended, included a screenshot of the pdf. cc @openstaxalina 
![2018-07-10_10-24-44](https://user-images.githubusercontent.com/8514591/42520312-8e35221c-842b-11e8-9c3a-d184c40fe159.png)

**Comment by openstaxalina** [comment]
Filed https://openstax.org/errata/6439 for this; we can fix independently of Assignable Webview.
