### ISSUE TITLE
Intro to Business => Customer Satisfaction feature change

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-recipes#466]
Customer Satisfaction feature title should be **Customer Satisfaction and Quality**.

![picture1](https://user-images.githubusercontent.com/11299035/42660228-1fa9cd4a-85f0-11e8-8ad1-003ae1377f58.png)

**Comment by openstaxalina** [comment]
I think this is high priority; we are close to having final XML for this title and cannot generate a final QA content without this fix.  @lwtchu please review/confirm.

**Comment by damondemar** [comment]
Issue was handled in oer.exports https://github.com/Connexions/oer.exports/issues/3700. The note title is already fixed in the recipe.
