### ISSUE TITLE
Intro to Business: Notes callout not in superscript

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#473]
@helenemccarron commented on [Fri Jul 06 2018](https://github.com/Connexions/webview/issues/1699)

@clteam18 commented on [Fri Jul 06 2018](https://github.com/Connexions/cnx-recipes/issues/448)

Global for all Chapters

![image](https://user-images.githubusercontent.com/39794953/42385250-dfd72306-8159-11e8-844a-d273d83b6f64.png)

Notes callout are not in superscript position, seems to be continuation with the paragraph text.

---

@openstaxalina commented on [Mon Jul 09 2018](https://github.com/Connexions/webview/issues/1699#issuecomment-403553579)

Footnote call needs to be superscript.  

---

@openstaxalina commented on [Mon Jul 09 2018](https://github.com/Connexions/webview/issues/1699#issuecomment-403553873)

This may need to move to using a superscript in cnx-recipes.  @helenemccarron to discuss w/ team.

---

@openstaxalina commented on [Mon Jul 16 2018](https://github.com/Connexions/webview/issues/1699#issuecomment-405305271)

This will be a flag, likely for the SRM titles (Introduction to Business, Principles of Management).

**Comment by openstaxalina** [comment]
Moved to this release because it is dependent on the feature flag functionality.

**Comment by openstaxalina** [comment]
Confirm this was fixed for the webview format, examples here: https://cnx.org/contents/Tgl3H6iq@8.5:TGHLb4ZB@7/17-2-Developing-Interpersonal-Skills-Is-Key-to-Your-Success
