### ISSUE TITLE
Biology 2e: Change "Art Connection" to "Visual Connection" in Collating EOC Section

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#474]
# Scenario
We updated the "Art Connection" to "Visual Connection" for _Biology 2e_.  However, we need to make this change in the End of Section "Art Connection Questions" section.

# Reproducibility Details
***Note: the screenshot and links are from Biology (1e) on devb and should be updated once the baked version of Biology 2e is available on katalys01.***

- **Impact area**: EOC "Art Connection Questions" collating section
- **User**: all
- **URL / Location**: https://devb.cnx.org/contents/GFy_h8cu@10.120:dCrNWQTC@10.120/Art-Connection-Questions
- **How many times were you able to reproduce the issue?** multiple

## Steps to reproduce:

- Step 1 Navigate to Biology 2e (baked) on Katalyst01 
- Step 2 Open the ToC until you can view the EOC materials for any chapter
- Step 3 Note that the collating section is misnamed "Art Connection Questions"

## Screenshots
<img width="1294" alt="screen shot 2018-07-17 at 11 48 59 am" src="https://user-images.githubusercontent.com/7863733/42832770-dda46146-89b7-11e8-94c0-105973413979.png">

# Environment:

- **Instance**: all
- **OS**: MacOS (issue will be present in all OS)
- **Browser**: Chrome (issue will be present in all browsers)

# Impact

- **Severity**: moderate
- **Frequency of occurrence**: in every chapter

**Comment by openstaxalina** [comment]
Flag to discuss at Sprint Planning.

**Comment by openstaxalina** [comment]
@Bkblodget changed all "art-connection" classes to "visual-connection" classes in the content on production.

Need to migrate at least a chapter of this updated content to katalyst01.  

Then can change the css to support both art and visual connection.

**Comment by openstaxalina** [comment]
*Decision:* 

@Bkblodget changing all `art-connection` classes to `visual-connection`

@Bkblodget also changing all `free-response` classes to `critical-thinking`

Then, @Bkblodget will migrate a chapter of content to katalys01 for testing.  

The css should support all classes listed above.

**Comment by openstaxalina** [comment]
@Bkblodget could you link to the chapter collection on katalyst01 once you have migrated the new content?

**Comment by Bkblodget** [comment]
@openstaxalina I am blocked from migrating content to Katalyst01 because of a legacy site error. Devops is working to fix this and I will migrate content when possible.

**Comment by Bkblodget** [comment]
@openstaxalina I have migrated Ch.12 of updated content to katalyst01 here: https://katalyst01.cnx.org/contents/jVCgr5SL@8.199:NVWjT7Jd@3/Introduction

**Comment by openstaxalina** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/e068dd5c-9de0-4feb-9f57-f7289961c386-361c6ea6-266f-41d9-8feb-a2c7f8c5a321-v1.png?transparent=1&palette=1&width=246)

**Comment by openstaxalina** [comment]
Reopening because we still want to do the dev work on this :-D

**Comment by openstaxalina** [comment]
superceded by: https://github.com/Connexions/cnx-recipes/issues/563
closing
