### ISSUE TITLE
Business Ethics - Link to Learning feature title missing 'to' in Webview

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#480]
@mwest-WWprod commented on [Thu Jul 19 2018](https://github.com/Connexions/oer.exports/issues/3711)

content01
GLOBAL - Webview

Link to Learning missing 'to' in the feature title, in Webview.

![ll_webview](https://user-images.githubusercontent.com/19212926/42969035-ec6b51c8-8b72-11e8-9e6a-9b6b65bfaa54.png)

---

@openstaxalina commented on [Thu Jul 19 2018](https://github.com/Connexions/oer.exports/issues/3711#issuecomment-406413099)

@Stackblocks, could you move this to cnx-recipes?

**Comment by helenemccarron** [comment]
Resolved in PR #532. Link Learning now says Link to Learning.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d8b5c990-b37a-491a-af8b-2e18762a09b5)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/85b96e4b-3dea-4478-88d7-0f6ad6734ce9)
