### ISSUE TITLE
Business Ethics - Endnote numbering in Webview

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#483]
content 01
GLOBAL - Webview

All endnotes within a chapter should have a unique numeral (as in the PDF).  See below for example of these appear in Webview.

![endnote_numbering](https://user-images.githubusercontent.com/19212926/42972530-c8f31680-8b7d-11e8-9cad-1567e68933cd.png)

**Comment by openstaxalina** [comment]
Covered by: https://github.com/Connexions/cnx-recipes/issues/485; closing.
