### ISSUE TITLE
Business Ethics - Assessment module headers in Webview

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#484]
content01
GLOBAL - Webview

Assessment questions should not have module headers listed in Webview (see PDF), if it is possible to remove them.

![assessment module headers](https://user-images.githubusercontent.com/19212926/42972860-f3a874e6-8b7e-11e8-8629-a52c24675347.png)

**Comment by helenemccarron** [comment]
![2018-08-08_11-29-42](https://user-images.githubusercontent.com/8514591/43850745-643c52b6-9afe-11e8-9731-b3b3d82dcc09.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/87f8373c-eb9c-4e40-8119-eca3e2463593)
