### ISSUE TITLE
Business Ethics - Remove endnote module headers, make numbering continuous in Webview

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#485]
content01
GLOBAL - Webview

Endnotes should not have module headers listed in Webview (see PDF), if it is possible to remove them.

![endnote module headers](https://user-images.githubusercontent.com/19212926/42972970-529d8ac2-8b7f-11e8-8428-99960234bcd5.png)

**Comment by openstaxalina** [comment]
*Decision:* Remove the module headers AND ensure End Notes number continuously through the chapter and reset with the next chapter.

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/webview #1803](https://github.com/Connexions/webview/issues/1803) via [**ZenHub**](https://www.zenhub.com/)

**Comment by helenemccarron** [comment]
![image](https://user-images.githubusercontent.com/8514591/43977454-d9fa6b8a-9ca9-11e8-9775-0c25e8d017f7.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c5d673ff-5b2a-4edd-b674-915da399bc6d)
