### ISSUE TITLE
Intro to Business: Table callout generated as Table A.1, Table A.2

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#487]
@clteam18 commented on [Wed Jul 18 2018](https://github.com/Connexions/oer.exports/issues/3707)

**Appendix - m10302**

**PDF**

![image](https://user-images.githubusercontent.com/39794953/42871801-d7cad71e-8a98-11e8-889a-a6e5460322ec.png)

Table captions generated as (**Table A1**, **Table A2**), whereas the callout in paragraph generates as (**Table A.1**, **Table A.2**).

In web view, the callout and Table caption has (**Table A1**). Hope, the callout should be generated as like web view (**Table A1**) in PDF

---

@openstaxalina commented on [Wed Jul 18 2018](https://github.com/Connexions/oer.exports/issues/3707#issuecomment-405957610)

@lwtchu please prioritize.

---

@lwtchu commented on [Thu Jul 19 2018](https://github.com/Connexions/oer.exports/issues/3707#issuecomment-406366778)

This should affect all titles. 

---

@helenemccarron commented on [Fri Jul 20 2018](https://github.com/Connexions/oer.exports/issues/3707#issuecomment-406636805)

Moving this to recipes.

**Comment by openstaxalina** [comment]
@helenemccarron we should discuss at sprint planning - I think this impacts the PDF, not web view.
