### ISSUE TITLE
No subcaption in Biology 2e  

### ISSUE THREAD

**Issue by uskka** [Connexions/cnx-recipes#489]
**Description**: No subcaption under pictures in Biology 2e.  Screen from  / 1.1 The Science of Biology 

There will be a problem with fixing this because there are some pictures within the same book where subcaptions look fine but they are in the pictures and can't be edited with any code. Pictures with subcaptions inside them unfortunately don't have other class then pictures with missing subcaption.  

**Where** : katayst01 
https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:zmz95BrD@5/11-The-Science-of-Biology
https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:cSl68Xz9@4/Introduction
https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:D6QqvHFC@6/122-Characteristics-and-Traits
https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:Og_t3zwv@4/322-Pollination-and-Fertilizat

 **KATALYST01** Subcaptions inside pictures 

https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:N1f0e7hP@3/304-Leaves

**PDF**

![screenshot-d3bxy9euw4e147 cloudfront net-2018 07 23-15-43-40](https://user-images.githubusercontent.com/40228918/43080513-293943b0-8e90-11e8-8ecf-9747d378066f.png)

**KATALYST01**

![screenshot-katalyst01 cnx org-2018 07 23-15-40-04](https://user-images.githubusercontent.com/40228918/43080520-2b70d594-8e90-11e8-9adb-5df2e9532139.png)

**Comment by openstaxalina** [comment]
@helenemccarron I reviewed and prioritized this issue.

**Comment by wilkus27** [comment]
The same problem in Biology for AP (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7fPPRIT6@4/11-The-Science-of-Biology):
![subcaption](https://user-images.githubusercontent.com/40228854/43129777-6d13fe90-8f35-11e8-8754-f59c68ece2c5.JPG)

**Comment by Adrianltd** [comment]
@helenemccarron It seems that some of the images have the subcaptions on the image itself. Also some of the images are merged into one image (you have one image with 3 subcaptions on the image). This means that if we add subcaptions through recipes, some of the images will have doubled subcaptions and those that are merged 3 in 1 will have additionally 1 subcaption for the whole image.
Taking this all into consideration I think that it would be better to add subcaptions into the images (content issue) than adding class to recipes to those that don't have subcaption at all now.

**Comment by helenemccarron** [comment]
@openstaxalina I am not sure how we handle it in the PDF but I can look. It does look like the content is uneven, what route do you think it most efficient in this case?

**Comment by openstaxalina** [comment]
*Decision:* replace all subfigures (multiple figures inside one figure tag) with an image that has the subfigures labeled - (a), (b), etc.

**Comment by openstaxalina** [comment]
@Bkblodget when you are back, please search Bio 2e and AP Bio CNXML for subfigures and let us know how many times this issue occurs.  Then we can make a plan for how to execute on the decision above.

**Comment by wilkus27** [comment]
Other examples from Biology for AP:
(1) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:YPkNZtMU@7/43-Eukaryotic-Cells -> Figure 4.8, 4.12

(2) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:qn1hGEbS@6/122-Characteristics-and-Traits -> Figure 12.10

(3) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:GZjhDdtl@6/362-Life-Histories-and-Natural -> Figure 36.7

(4) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:ktqpi5Wm@6/364-Population-Dynamics-and-Re -> Figure 36.13

(5) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:2sMTp7KD@5/366-Community-Ecology -> Figure 36.21, 36.23, 36.27

(6) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:PghI2Mhm@5/367-Behavioral-Biology-Proxima -> Figure 36.39

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/content-managers #192](https://github.com/Connexions/content-managers/issues/192) via [**ZenHub**](https://www.zenhub.com/)
