### ISSUE TITLE
"LINK TO LEARNING" is not displayed correctly 

### ISSUE THREAD

**Issue by uskka** [Connexions/cnx-recipes#490]
Description: "LINK TO LEARNING" is not displayed correctly 

Where: Biology 2e / 9.4 Signaling in Single-Celled Organisms
https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:5XhJLPA5@4/94-Signaling-in-Single-Celled-#footnote-ref1

![screenshot-katalyst01 cnx org-2018 07 23-18-12-29](https://user-images.githubusercontent.com/40228918/43089488-0c799f4e-8ea5-11e8-9055-6749dd517cf6.png)

Reference: Biology 2e / 9.2 Propagation of the Signal
![screenshot-katalyst01 cnx org-2018 07 23-18-13-14](https://user-images.githubusercontent.com/40228918/43089495-107b13d4-8ea5-11e8-9095-5d1103427710.png)

**Comment by openstaxalina** [comment]
Good catch!  The URL is incorrect.  Noted as errata: https://openstax.org/errata/6498.  Closing this issue.
