### ISSUE TITLE
Numbering of equations issue

### ISSUE THREAD

**Issue by uskka** [Connexions/cnx-recipes#492]
Description: Numbering of equations only works on University Physics Volume 1-3 but still it's displayed wrong. Numbering was fixed in https://github.com/Connexions/webview/issues/1652

How it should look like:

![41614804-105274e8-73bf-11e8-9a71-a9322c008861](https://user-images.githubusercontent.com/40228918/43205466-b9c037ce-9023-11e8-8b8f-849c786bd0cd.png)

College Physics For AP® Courses/ katalyst01
https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:CQh5rf9m@5/12-Physical-Quantities-and-Uni
![apphysics-katalyst01 cnx org-2018 07 25-14-49-10](https://user-images.githubusercontent.com/40228918/43204154-784a878e-9020-11e8-943e-3602bdb57bfb.png)

University Physics Volume 1 / katalyst01
https://katalyst01.cnx.org/contents/1Q9uMg_a@10.18:C9DRormz@8/16-Significant-Figures
![screenshot-katalyst01 cnx org-2018 07 25-14-42-23](https://user-images.githubusercontent.com/40228918/43204164-7a25e684-9020-11e8-80ef-866a76af59ac.png)

**Comment by helenemccarron** [comment]
Upon a quick investigation, I believe the equations in books other than U-Physics need to be numbered before being moved. That should produce the same markup.
![2018-07-24_10-42-31](https://user-images.githubusercontent.com/8514591/43206114-932cf0d6-8fea-11e8-8ea4-df4a1733335c.png)
![2018-07-24_10-43-00](https://user-images.githubusercontent.com/8514591/43206119-95f77b56-8fea-11e8-9c8d-21e190ab2728.png)

**Comment by PatBoj** [comment]
I've created a separate container for an equation's number (`class="os-number"`) and divider (`class="os-divider"`).

Before:
![image](https://user-images.githubusercontent.com/20907906/43513759-e378c68e-957e-11e8-9592-a3aa2ffc752c.png)

After:
![image](https://user-images.githubusercontent.com/20907906/43513766-e802da82-957e-11e8-8865-1f34340f0b3a.png)

**Comment by wilkus27** [comment]
Verified on katalyst01:
![numbering](https://user-images.githubusercontent.com/40228854/43527313-9e432988-95a6-11e8-993b-ec0f2e5be07a.JPG)
