### ISSUE TITLE
Two types of modules beginning

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#493]
@wilkus27 commented on [Tue Jul 24 2018](https://github.com/Connexions/webview/issues/1736)

In Biology for AP at the beggining of the modules we have two informations: "By the end of this section, you will be able to" and "In this section, you will investigate the following questions" but in pdf we have just one information:

katalyst01 (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7fPPRIT6@4/11-The-Science-of-Biology)
![by_the_end_1 1](https://user-images.githubusercontent.com/40228854/43131843-51750fd0-8f3a-11e8-98d7-5797cd08b800.JPG)

pdf:
![by_the-end_1 1_pdf](https://user-images.githubusercontent.com/40228854/43131860-5bf1c5c0-8f3a-11e8-89c0-1e318fd6e4d0.JPG)

What is more, when in pdf there is box with "By the end of this section, you will be able to" in webview we see doubled information:

katalyst01 (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:L2ccw6bD@7/12-Themes-and-Concepts-of-Biol)
![by_the_end_1 2](https://user-images.githubusercontent.com/40228854/43132059-f3369d2a-8f3a-11e8-8d32-e182bb3ecaca.JPG)

pdf:
![by_the_end_1 2_pdf](https://user-images.githubusercontent.com/40228854/43132013-c8ba5f0a-8f3a-11e8-8690-7fedb54683ad.JPG)

---

@helenemccarron commented on [Wed Jul 25 2018](https://github.com/Connexions/webview/issues/1736#issuecomment-407778646)

This might be a recipe issue. It looks like the content displays both the learning objectives and the metadata abstract. I'll move this to recipes for investigation.

**Comment by wilkus27** [comment]
Verified on katalyst01:
![beginning](https://user-images.githubusercontent.com/40228854/43525694-cd283418-95a2-11e8-9ec1-95059f41e667.JPG)
