### ISSUE TITLE
Inconsistancy in numbering of figures between webview and pdf

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#494]
@wilkus27 commented on [Wed Jul 25 2018](https://github.com/Connexions/webview/issues/1744)

The numbering of figures is the same on katalyst01 and pdf to this moment:
https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:Ao-lRbxu@6/75-Metabolism-without-Oxygen
![figure_7 16_kat](https://user-images.githubusercontent.com/40228854/43206078-23e890e6-9025-11e8-9e59-e209d9eedce3.JPG)

PDF:
![figure_7 16_pdf](https://user-images.githubusercontent.com/40228854/43206169-5b736a2c-9025-11e8-8e8c-b7f876e22f34.JPG)

The next figure on katalyst01 have number **7.18** instead of **7.17**:
https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:jh6WGEi0@5/76-Connections-of-Carbohydrate
![figure_7 18_kat](https://user-images.githubusercontent.com/40228854/43206215-79426ed6-9025-11e8-8e4c-d85463003b21.JPG)

PDF:
![figure_7 17_pdf](https://user-images.githubusercontent.com/40228854/43206238-82e72580-9025-11e8-971a-74c96291f839.JPG)

---

@helenemccarron commented on [Wed Jul 25 2018](https://github.com/Connexions/webview/issues/1744#issuecomment-407779519)

This is most likely a recipe issue, moving the issue over.

**Comment by wilkus27** [comment]
The same problem in module 10.2 (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:ikKSSwrr@9/102-The-Cell-Cycle)

katalyst01:
![figure_10 6_kat](https://user-images.githubusercontent.com/40228854/43249061-fff914ae-90b9-11e8-967d-b04e45777103.JPG)

PDF:
![figure_10 5_pdf](https://user-images.githubusercontent.com/40228854/43249078-08875acc-90ba-11e8-8b0b-3b1bb40d6150.JPG)

**Comment by Adrianltd** [comment]
@helenemccarron What are teacher notes? There's a figure in `os-teacher` which is not displayed anywhere and it gets the missing number. I can't even find that teacher note anywhere in the book. 
I think that adding `@include modify_trash(".os-teacher");` with an if statement set to `false` in common config and to `true` in apbiology would fix that. I am not sure what is this `os-teacher` for and if I can safely trash it.

**Comment by helenemccarron** [comment]
Teacher notes are components used in Tutor (another product) but hidden in Webview and in the PDF. My guess is to make sure the teacher notes aren't included in the counter.

**Comment by openstaxalina** [comment]
Helene and Adrian attempted to target the figures inside teacher notes to make them unnumbered.  However, this is not a good solution.  

Therefore, *we will make all images inside teacher notes unnumbered via content*.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #197](https://github.com/Connexions/content-managers/issues/197) via [**ZenHub**](https://www.zenhub.com/)
