### ISSUE TITLE
Difference in numbering of exercise on webview and pdf

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#497]
On katalyst01 exercise have different number then in pdf.

katalyst01 -> **SCIENCE PRACTICE CONNECTION** (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:ikKSSwrr@9/102-The-Cell-Cycle)

![exercise](https://user-images.githubusercontent.com/40228854/43254751-59133d54-90c8-11e8-91ae-1b51ad0c9505.JPG)

PDF:
![exercise_pdf](https://user-images.githubusercontent.com/40228854/43254771-624aa092-90c8-11e8-9396-3094b16e31c3.JPG)

**Comment by openstaxalina** [comment]
@helenemccarron FYI - I added this to ornery.orthrus in case this can fit into this sprint.

**Comment by wilkus27** [comment]
Verified on katalyst01:
![numbering](https://user-images.githubusercontent.com/40228854/43593838-19911546-9679-11e8-9d45-f3cfc0187afe.JPG)
