### ISSUE TITLE
Human-readable recipe name in the recipe (CSS comments)

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#500]
@brittweinstein commented on [Thu Jul 26 2018](https://github.com/Connexions/content-managers/issues/169)

#Description

See https://github.com/Connexions/cnx-recipes/issues/345

#Acceptance criteria

* 1 Content Manager can see the name of the recipe in the content status tool
* 2 Content Manager can see the name of the recipe in the collection editor
* 3 ... anything else?

#Epic Doc
N/A
# GitHub Bug Tracking
https://github.com/Connexions/cnx-recipes/issues/345

**Comment by openstaxalina** [comment]
The Exit Criteria has already been met through other work.  I am going to close this.

<img width="1440" alt="screen shot 2018-08-05 at 5 07 15 pm" src="https://user-images.githubusercontent.com/7863733/43690585-0da1295a-98d2-11e8-8253-f385c5db901a.png">
