### ISSUE TITLE
Update Testy McTestFace to facilitate recipe creation

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#502]
@brittweinstein commented on [Tue Jul 24 2018](https://github.com/Connexions/content-managers/issues/121)

---

@staxly[bot] commented on [Tue Jul 24 2018](https://github.com/Connexions/content-managers/issues/121#issuecomment-407547577)

The maintainers of this repository would appreciate it if you could provide more information.

**Comment by openstaxalina** [comment]
This does need to be finished this release since Katalyst will be moving onto the next phase of Assignable Webview (new recipe creation).

**Comment by brittweinstein** [comment]
This will be discussed in tomorrow's Katalyst meeting.
