### ISSUE TITLE
Add to baking training documentation (Kerwin, Alan)

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#508]
@brittweinstein commented on [Thu Jul 26 2018](https://github.com/Connexions/webview/issues/1763)

**Comment by openstaxalina** [comment]
@Stackblocks linking to the webview QA documentation he created for the vendors (which has some information about baking).

@kerwinso if you have any documentation, could you link to it in this card?

**Comment by Stackblocks** [comment]
Webview QA documentation for vendors: https://docs.google.com/document/d/1T3Mmbny05_KXegPjPGWdzRAdKg2MBLuUtLH9qaLpFBg/edit

**Comment by kerwinso** [comment]
@openstaxalina Here's some ad-hoc Baking Training documentation:
https://docs.google.com/document/d/1IMmzTjudlaObHUlbMBvewbyXDu5bOpaDJajoeQ7kbXs/edit#
