### ISSUE TITLE
Business Ethics - Hyperlink color contrast

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#512]
content01
GLOBAL

For the color contrast to pass AA requirements, the text must be 14pts or larger.  It appears as though hyperlinks do not currently pass the AA requirements.

![hyperlinks_color contrast](https://user-images.githubusercontent.com/19212926/43348608-f2abc1b0-91c8-11e8-9c18-b307a5a67335.png)

![hyperlinks_color contrast checker](https://user-images.githubusercontent.com/19212926/43348623-0518a4d0-91c9-11e8-97a4-c850f5b1882f.png)

This also applies to hyperlinks on FB backgrounds, where the contrast ratio is less.  

![hyperlinks_fb color contrast](https://user-images.githubusercontent.com/19212926/43348919-a072fefc-91ca-11e8-8419-b171192c2fbb.png)

![hyperlinks_fb color contrast checker](https://user-images.githubusercontent.com/19212926/43348923-a3319f68-91ca-11e8-9b57-288b258c2298.png)

**Comment by openstaxalina** [comment]
I believe this issue is in the PDF.  @Stackblocks, could you please transfer this issue to oer.exports?
cc @mwest-WWprod

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/oer.exports #3727](https://github.com/Connexions/oer.exports/issues/3727) via [**ZenHub**](https://www.zenhub.com/)
