### ISSUE TITLE
Too long distance between words in table

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#519]
The problem from issue #459 also occurs in Biology for AP:
(1) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:qZUaLE-Z@7.1/Science-Practice-Challenge-Que -> table 6.2
![distance_header](https://user-images.githubusercontent.com/40228854/43583335-871f0e5c-965f-11e8-88b5-2b6265ba94bd.JPG)

Other examples:
(2) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7ExM0p8o@7.1/Science-Practice-Challenge-Que -> table 10.5

(3) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:TBWIYI1m@7.1/Science-Practice-Challenge-Que -> table 13.1

(4) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:xBv3uJqm@7.1/Science-Practice-Challenge-Que -> table 35.1

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1800](https://github.com/Connexions/webview/issues/1800) via [**ZenHub**](https://www.zenhub.com/)
