### ISSUE TITLE
Unnecessary links in equation numbering

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#521]
In equation numbering there are links which lead to themselfs (https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:JM3DLi_e@5/25-Motion-Equations-for-Consta#fs-id1164906434690) -> Show Solution -> Equation 2.70, 2.71

![link_in_number](https://user-images.githubusercontent.com/40228854/43633185-c47c9a0e-9708-11e8-99bf-d07a14bc1718.JPG)

**Comment by wilkus27** [comment]
Next example: https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:NBdsQ1o7@5/27-Falling-Objects -> **Check Your Understanding** -> **Show Solution** -> equation **2.88**

**Comment by PatBoj** [comment]
@openstaxalina I don't know if you noticed, but there is an error in screen-shot that you uploaded. Equation (2.71) should look like this

![codecogseqn 1](https://user-images.githubusercontent.com/20907906/43707745-0cb5c1b2-9969-11e8-8a6b-8644a4c0695d.png)

The equation is correct on katalyst01 server.

**Comment by openstaxalina** [comment]
Thanks, @PatBoj!  It looks like this was fixed via errata.  However, the PDF was not revised this year.  Therefore, the PDF content is not as updated as the webview.

**Comment by PatBoj** [comment]
### **Before:**
![image](https://user-images.githubusercontent.com/20907906/43767360-3158c740-9a35-11e8-8a6e-10e7dcdf4cd7.png)

### **After:**
![image](https://user-images.githubusercontent.com/20907906/43767366-353fec6c-9a35-11e8-8dfe-ebbdce214ae5.png)

**Comment by wilkus27** [comment]
Verified on katalyst01:

![link_in_nr](https://user-images.githubusercontent.com/40228854/44042478-ae5feecc-9f20-11e8-9a90-b4dec30c2c1f.JPG)
