### ISSUE TITLE
Business Ethics - Key Terms should appear EOC in Webview

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-recipes#522]
@mwest-WWprod commented on [Thu Jul 19 2018](https://github.com/Connexions/oer.exports/issues/3712)

content01
GLOBAL - Webview

Key Terms should collate EOC in Webview (like Summary, Assessments) instead of being listed EOM, if possible, as seen in the generated PDFs.

![keyterms_eoc collation](https://user-images.githubusercontent.com/19212926/42970207-ab68314c-8b76-11e8-9d4f-22ea35d40d88.png)

**Comment by openstaxalina** [comment]
@lwtchu Please review priority and books assigned.  Does this impact any other titles?

**Comment by helenemccarron** [comment]
@lwtchu The collection we are using doesn't have the content in the screenshot, can we migrate it? Also, based on https://devb.cnx.org/contets/WUj6TfJ0@8.10:aWku4B8a@8.10/Key-Terms I am not sure it's a recipe issue, can you verify that the content is correct? It might save us some time :-D

**Comment by lwtchu** [comment]
@helenemccarron use this collection: https://devb.cnx.org/contents/nfg8oHUF@2.9:R-KhohmW@3/Introduction

**Comment by helenemccarron** [comment]
Addressed in PR #532

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/926bd784-41c0-4a73-aad7-4ef13927b39f)
