### ISSUE TITLE
Number of equation beyond the example box

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#524]
https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:PMna1Pqe@3/123-The-Most-General-Applicati

![beyond_box](https://user-images.githubusercontent.com/40228854/43721428-08f0a9c8-9993-11e8-8410-83b779c4d14d.JPG)

**Comment by helenemccarron** [comment]
@openstaxalina I believe this is a content issue, the equation is too long. I think in the PDF, we broke it down or sized it down but I'm not sure what's the best approach here

**Comment by wilkus27** [comment]
@helenemccarron In the pdf number is under the equation:

![beyond_box_pdf](https://user-images.githubusercontent.com/40228854/43781065-5acb9004-9a5c-11e8-8736-032be0a3f08a.JPG)

(Ps. Inconsistency in numbering is reported in another issue.)

**Comment by openstaxalina** [comment]
@helenemccarron is there a way to have the equation number fall to the next line, as it was done in the PDF?  @oscryan reports we didn't do anything special to the equation to cause this behavior/treatment in the PDF.

**Comment by helenemccarron** [comment]
I'm not sure, we'll investigate for a CSS solution.

**Comment by openstaxalina** [comment]
*Decision from scrum:* @wilkus27 will continue to add screenshots if she finds more examples.  Then assign to Alina for a content fix.

**Comment by wilkus27** [comment]
There are two more examples:

(1) https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:mcFrL3ZY@2/145-Conduction

![beyond2](https://user-images.githubusercontent.com/40228854/44025308-09f3044e-9ef0-11e8-8f90-1c366c7cfd59.JPG)

(2) https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:ZUFT1_5j@5/167-Damped-Harmonic-Motion

![beyond3](https://user-images.githubusercontent.com/40228854/44025332-1cdc7216-9ef0-11e8-8efe-4bf9db10f820.JPG)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #236](https://github.com/Connexions/content-managers/issues/236) via [**ZenHub**](https://www.zenhub.com/)
