### ISSUE TITLE
Extra point in Chapter Outline

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#536]
There is additional point in Chapter Outline: (https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:UWxHQ0zC@2/Connection-for-AP-Courses)

![sentence](https://user-images.githubusercontent.com/40228854/43954877-6afa45e4-9c9e-11e8-94b4-bea37a4e384f.JPG)

It looks like point from Learning Objectives:

![sentence2](https://user-images.githubusercontent.com/40228854/43955148-36da33ae-9c9f-11e8-8fe8-8212f9dd2f4f.JPG)

Maybe it's a previous version of this one, but I'm not sure because these are two different terms.

**Comment by openstaxalina** [comment]
@helenemccarron it looks like "Define radioactivity." is the abstract/summary - here is the content on production (click "Show Summary") https://cnx.org/contents/jQSmhtXo@16.48:UWxHQ0zC@2/Connection-for-AP-Courses

**Comment by helenemccarron** [comment]
It looks like the abstract is suppressed in this book. Should be remove all the abstracts that are present in the content via recipes?

**Comment by openstaxalina** [comment]
@helenemccarron yes, I think we should.  Is this consistent with previous decisions?  Do you have any concerns?

**Comment by helenemccarron** [comment]
I wasn't sure if we did or not, but no, I don't have any concerns. We simply need to set the abstract to false in the config file.

**Comment by PatBoj** [comment]
Do as @helenemccarron says and it works :).

### **Before:**
![image](https://user-images.githubusercontent.com/20907906/44081869-1b77d65c-9fb0-11e8-82d9-23004a59ad96.png)

### **After:**
![image](https://user-images.githubusercontent.com/20907906/44081879-220010fc-9fb0-11e8-8420-91efbc47ca72.png)

**Comment by wilkus27** [comment]
Verified on katalyst01:

![add_point](https://user-images.githubusercontent.com/40228854/44099774-a89d31f2-9fe3-11e8-9024-4f5b28f36d9c.JPG)
