### ISSUE TITLE
AW Feature flags list

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#537]
## https://github.com/Connexions/cnx-recipes/blob/katAW.queued.quadcopter/FEATURES.md

**sup-footnote-call**: issue #473 
- [x] Introductory Business Statistics (_statistics_)
- [ ] Introductory Statistics (_statistics_)

- [ ] Biology  AP® Courses (_ap-biology_)
- [ ] Biology 2e (_biology_)
- [ ] Concepts of Biology (_biology_)

- [ ] AP Macroeconomics 2e (_economics_)
- [ ] Principles of Economics 2e (_economics_)

- [ ] Physics For AP® Courses (_ap-physics_)
- [ ] College Physics (_physics_)

**trash-empty-table-captions**: issue #434
- [x] Introductory Business Statistics (_statistics_)
- [ ] Introductory Statistics (_statistics_)

- [ ] Biology  AP® Courses (_ap-biology_)
- [ ] Biology 2e (_biology_)
- [ ] Concepts of Biology (_biology_)

- [ ] AP Macroeconomics 2e (_economics_)
- [x] Principles of Economics 2e (_economics_)

- [x] Physics For AP® Courses (_ap-physics_)
- [ ] College Physics (_physics_)

**exercise-container**: issue #454
- [x] Introductory Business Statistics (_statistics_)
- [ ] Introductory Statistics (_statistics_)

- [x] Biology  AP® Courses (_ap-biology_)
- [ ] Biology 2e (_biology_)
- [ ] Concepts of Biology (_biology_)

- [ ] AP Macroeconomics 2e (_economics_)
- [x] Principles of Economics 2e (_economics_)

- [ ] Physics For AP® Courses (_ap-physics_)
- [ ] College Physics (_physics_)

**delete-link-in-equation-number**: issue #521
- [ ] Introductory Business Statistics (_statistics_)
- [ ] Introductory Statistics (_statistics_)

- [ ] Biology  AP® Courses (_ap-biology_)
- [ ] Biology 2e (_biology_)
- [ ] Concepts of Biology (_biology_)

- [ ] AP Macroeconomics 2e (_economics_)
- [ ] Principles of Economics 2e (_economics_)

- [x] Physics For AP® Courses (_ap-physics_)
- [ ] College Physics (_physics_)

**table-summaries-are-captions**: issue #407
- [x] Introductory Business Statistics (_statistics_)
- [ ] Introductory Statistics (_statistics_)

- [ ] Biology  AP® Courses (_ap-biology_)
- [ ] Biology 2e (_biology_)
- [ ] Concepts of Biology (_biology_)

- [ ] AP Macroeconomics 2e (_economics_)
- [x] Principles of Economics 2e (_economics_)

- [ ] Physics For AP® Courses (_ap-physics_)
- [ ] College Physics (_physics_)

**preface-has-captions**: issue #455
- [x] Introductory Business Statistics (_statistics_)
- [x] Introductory Statistics (_statistics_)

- [ ] Biology  AP® Courses (_ap-biology_)
- [ ] Biology 2e (_biology_)
- [ ] Concepts of Biology (_biology_)

- [ ] AP Macroeconomics 2e (_economics_)
- [x] Principles of Economics 2e (_economics_)

- [ ] Physics For AP® Courses (_ap-physics_)
- [ ] College Physics (_physics_)

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/webview #1825](https://github.com/Connexions/webview/issues/1825) via [**ZenHub**](https://www.zenhub.com/)

**Comment by openstaxalina** [comment]
This was tracked here instead: https://docs.google.com/document/d/1Oxy08GaYiDBJ94Q9U_aBcLyXk4DnjrHomDWQOXmrTYU
