### ISSUE TITLE
Issue with figures in Answer Key

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#539]
Figures from Answer Key in pdf are numbered but in webview they are not:

**katalyst01**: https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:WwXAbgy9@16.36/Answer-Key
(answers for Chapter 2)

![fig_unnr_kat](https://user-images.githubusercontent.com/40228854/44035733-7136c3b4-9f10-11e8-83c3-f2aeb38d0e9c.JPG)

**PDF**:

![fig_nr_pdf](https://user-images.githubusercontent.com/40228854/44035742-79100820-9f10-11e8-9dc9-4f5e6b989991.JPG)

But in this case it might be a problem with pdf, because module **Answer Key** is not visible in Table of Contents:

![spis_pdf](https://user-images.githubusercontent.com/40228854/44036021-191409c0-9f11-11e8-8a0b-c6b63aa41bf8.JPG)

This is how it looks on katalyst01:

![spis_kat](https://user-images.githubusercontent.com/40228854/44036089-492e2a14-9f11-11e8-9ad3-34888a1a8c86.JPG)

Although it is not visible in Table of Contents, the content of **Answer Key** is between **Glossary of Key Symbols and Notation** and **Index** like on katalyst01.

What's more, the numbering of figures from Answer Key in pdf have been used in earlier modules for other images:

Module **2.5 Motion Equations for Constant Acceleration in One Dimension**

![fig_nr2_pdf](https://user-images.githubusercontent.com/40228854/44036877-2a65b262-9f13-11e8-8357-aa95f50058b3.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 thanks for noting these issues.  The Answer Key will not appear in the Table of Contents in the PDF; this is a known issue/limitation.  I will move this issue over to oer.exports for a possible PDF fix from the OpenStax developers.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/oer.exports #3735](https://github.com/Connexions/oer.exports/issues/3735) via [**ZenHub**](https://www.zenhub.com/)
