### ISSUE TITLE
Enable top-titled for business books

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#541]
Enable top-titled tables in the recipes.

- [x] Intro Business
- [x] Business ethics
- [x] Principles of Management
- [x] Accounting
- [x] Entrepreneurship

**Comment by openstaxalina** [comment]
Is this covered by https://github.com/Connexions/cnx-recipes/issues/606 ?

If not, I will put this in the u.u. milestone (11/5 production deploy)

**Comment by brittany-johnson** [comment]
Accounting
<img width="1675" alt="screen shot 2018-12-04 at 1 46 21 pm" src="https://user-images.githubusercontent.com/24909007/49468636-0b037d80-f7cb-11e8-8e7d-5321c2051b2e.png">

PoM
<img width="1674" alt="screen shot 2018-12-04 at 1 47 20 pm" src="https://user-images.githubusercontent.com/24909007/49468662-28d0e280-f7cb-11e8-8ec4-8a49691ab894.png">

Eship
<img width="1671" alt="screen shot 2018-12-04 at 1 47 52 pm" src="https://user-images.githubusercontent.com/24909007/49468687-3b4b1c00-f7cb-11e8-8b80-c9d9af9612ba.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

# PoM
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7f3193e4-9173-42e2-af9f-05ad02639748)
# Accounting
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5039fc21-edc5-4aed-bb2f-780c44809303)
# Eship
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/439670f5-90f4-4df8-aad9-15f79a132b09)
