### ISSUE TITLE
Lists in exercises without margins

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#555]
After activating _exercise-container_ flag, when the exercise begins with the list, the list displays without margins:

katalyst01 (https://katalyst01.cnx.org/contents/kRfPjKij@4.5:pKpFhGyF@4.5/Answer-Key)

![answer_lists](https://user-images.githubusercontent.com/40228854/44210671-64d23000-a167-11e8-8055-55abf682766e.JPG)

**Comment by helenemccarron** [comment]
@PatBoj I believe you're the most suited to look into this 😄

**Comment by wilkus27** [comment]
Same problem in Introductory Statistics (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:hFIHxBfP@20.1/Solutions)

![answer_statistics](https://user-images.githubusercontent.com/40228854/44266514-1a19ec00-a22b-11e8-8ebd-14944a033567.JPG)

**Comment by wilkus27** [comment]
Issue moved to https://github.com/Connexions/webview/issues/1855 .
