### ISSUE TITLE
Enable top-titled tables for Business-Ethics

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#556]
Top titled tables should be supported in Business Ethics.

**Comment by helenemccarron** [comment]
addressed in PR #532 

![image](https://user-images.githubusercontent.com/8514591/44222413-03e82f00-a14a-11e8-8cb1-a66361961172.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b44d753e-21b6-4722-8e7e-03993a6353d1)
