### ISSUE TITLE
Captions above the figures

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#560]
Captions of images are above, instead of next to the numbering of figures.

katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:CY4aJuYS@17/12-Data-Sampling-and-Variation)

![captions_kat](https://user-images.githubusercontent.com/40228854/44258294-cb5e5900-a20e-11e8-9c5d-5f25260b68a1.JPG)

PDF:

![captions_pdf](https://user-images.githubusercontent.com/40228854/44258309-d3b69400-a20e-11e8-818a-e8d99e8b0fcc.JPG)

**Comment by uskka** [comment]
Also appears in Introductory Business Statistics. 
https://katalyst01.cnx.org/contents/tWu56V64@34.15:PhCRzjQp@15/12-Data-Sampling-and-Variation

**Comment by Adrianltd** [comment]
^ both of them should be affected by #564 fix

**Comment by wilkus27** [comment]
Verified on katalyst01:

1) Introductory Statistics

![cap_stat](https://user-images.githubusercontent.com/40228854/44416280-ced94380-a572-11e8-8020-6768c62c0b44.JPG)

2) Introductory Business Statistics

![cap_bus_stat](https://user-images.githubusercontent.com/40228854/44416308-df89b980-a572-11e8-8849-bf62cb6fa18f.JPG)
