### ISSUE TITLE
Wrong alignment of figures from Show Solution

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#561]
Figures from Show Solution are left aligned instead of being centered. It causes wrapping captions.

katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:KFOdKxbi@7/21-Stem-and-Leaf-Graphs-Stempl)

![fig_align](https://user-images.githubusercontent.com/40228854/44277587-7987f400-a24b-11e8-8cd0-9027effa48bd.JPG)

**Comment by uskka** [comment]
Also appears in Introductory Business Statistics. I have baked the book 3 days ago without any errors. The book looks fully baked. 
https://katalyst01.cnx.org/contents/tWu56V64@34.15:UMM7d-Hy@17/21-Display-Dat
![screenshot-katalyst01 cnx org-2018 08 20-17-59-07](https://user-images.githubusercontent.com/40228918/44351729-d6c9b280-a4a2-11e8-92ee-33d00683525f.png)

**Comment by wilkus27** [comment]
Confim, Introductory Statistics is also fully baked. I've baked it two times, removed cache from server and browser.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1859](https://github.com/Connexions/webview/issues/1859) via [**ZenHub**](https://www.zenhub.com/)

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1860](https://github.com/Connexions/webview/issues/1860) via [**ZenHub**](https://www.zenhub.com/)
