### ISSUE TITLE
Mess with terms from Index

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#562]
@wilkus27 commented on [Mon Aug 13 2018](https://github.com/Connexions/webview/issues/1826)

On katalyst01 (https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:Xm0hU3Qa@16.36/Index) one term from the middle of the index appears on the top and there are two headers **Symbols**

![symbols_kat](https://user-images.githubusercontent.com/40228854/44038267-b89775b8-9f16-11e8-8f41-f2169dfff026.JPG)

In PDF it looks like that:

![symbols_pdf](https://user-images.githubusercontent.com/40228854/44038318-d379c6d8-9f16-11e8-8e52-278f684ef9d6.JPG)

Additional terms from the top of the webview display properly in pdf:

![term_pdf](https://user-images.githubusercontent.com/40228854/44038447-19383952-9f17-11e8-94b2-e295a8e694af.JPG)

But on katalyst01 are missed:

![term_kat](https://user-images.githubusercontent.com/40228854/44038511-3da0a45a-9f17-11e8-9e4f-4f202fa16648.JPG)

---

@openstaxalina commented on [Mon Aug 13 2018](https://github.com/Connexions/webview/issues/1826#issuecomment-412555587)

Since code freeze is this week, and there is a national holiday in Poland, I am going to defer this to the backlog.  cc @helenemccarron @PiotrKozlowski @PatBoj @Adrianltd 

---

@openstaxalina commented on [Mon Aug 13 2018](https://github.com/Connexions/webview/issues/1826#issuecomment-412559841)

Previously this was occurring with terms in figure captions, and we elected not to support terms inside figure captions.  

However, I checked the first term (drift velocity) and it is not in a figure caption, so this could use some additional investigation.

---

@PiotrKozlowski commented on [Fri Aug 17 2018](https://github.com/Connexions/webview/issues/1826#issuecomment-413779652)

This looks like recipes issue, because webview is not manipulating with order of this code.
cc @helenemccarron , @openstaxalina

**Comment by helenemccarron** [comment]
@openstaxalina after some research, it looks like the term `drift velocity` has a space in it: `<term id="import-auto-id1215964"> drift velocity </term>`, the recipes consider that space a "symbol" and treat it as such. Can we remove it to verify if this is the cause of this behavior?

**Comment by openstaxalina** [comment]
@helenemccarron I removed the space before "drift velocity" in the content on katalyst01.  @wilkus27 could you rebake and retest?

If this solves the problem, we should move this issue to the content-managers repo.

**Comment by wilkus27** [comment]
After baking it looks like that:

![index1](https://user-images.githubusercontent.com/40228854/44715021-0f771680-aab7-11e8-8a2c-06e012dc50bc.JPG)

There is new term **decay equation** instead of **drift velocity**, but it also appears in right place:

![index2](https://user-images.githubusercontent.com/40228854/44715145-536a1b80-aab7-11e8-84da-c8aaaf544bd0.JPG)

**Drift velocity** displays correctly:

![index3](https://user-images.githubusercontent.com/40228854/44715205-7399da80-aab7-11e8-8c09-61623aa6d4b7.JPG)

In **SYMBOLS** missing **RC circuit**. It occurs below in list but displays incorrectly:

![index4](https://user-images.githubusercontent.com/40228854/44715310-c5426500-aab7-11e8-9b0d-d8e39f5c972a.JPG)

**Comment by PatBoj** [comment]
Screens below are from raw (not baked) html file.

` change in angular velocity` starts with space:
![image](https://user-images.githubusercontent.com/20907906/44787930-d8793180-ab98-11e8-82c0-7ea15c068dc5.png)

`(peak) emf` starts with "(":
![image](https://user-images.githubusercontent.com/20907906/44787946-ecbd2e80-ab98-11e8-9b50-09566bba316a.png)

`RC circuit` starts with math (it should't):
![image](https://user-images.githubusercontent.com/20907906/44787969-03638580-ab99-11e8-8f71-2bc583b7d5a0.png)

So terms should not start with a space and math. Also, in my opinion, the terms should't start with "(". I suggest to change `(peak) emf` to maximum (peak) emf`.
![image](https://user-images.githubusercontent.com/20907906/44788701-02335800-ab9b-11e8-813f-07664e7c8acc.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #276](https://github.com/Connexions/content-managers/issues/276) via [**ZenHub**](https://www.zenhub.com/)
