### ISSUE TITLE
Biology 2e: Updates to Classes

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#563]
# Scenario
We made updates to the class attributes used in Biology 2e, for content and clarity reasons.  We will make the same updates in Concepts of Biology.

## Art Connection --> Visual Connection Transitioning 
-collation instructions: change class name "art-exercise" to "visual-exercise" **and** the page name from "Art Connection Questions" to "Visual Connection Questions"
*This requires content managers to update art-exercise class to visual-exercise class and remigrate content.*
-note: change class name "art-connection" to "visual-connection" **and** the note title from "Art Connection" to "Visual Connection"

## free-response class to critical-thinking Transitioning
-collation instructions: change class name "free-response" to "critical-thinking" 

# Reproducibility Details
Note that this can only be tested in a targeted chapter that has been remigrated.

**Comment by openstaxalina** [comment]
Content to be used for testing on katalyst01:

Biology2e Ch.6 & Ch.30

Concepts of Bio Ch.4 & Ch.16:

**Comment by PatBoj** [comment]
Ready for testing.

**Comment by wilkus27** [comment]
**Concepts of Biology** - verified on katalyst01 - Chapter 4

1) Visual Connection Questions

![visual_connection_question](https://user-images.githubusercontent.com/40228854/45398484-98a85480-b644-11e8-98e2-05a98459fde1.JPG)

2) Visual Connection - NOTE

![visual_connection](https://user-images.githubusercontent.com/40228854/45398517-bfff2180-b644-11e8-83cd-931e2a2a822e.JPG)

3) Critical Thinking Questions

![critical](https://user-images.githubusercontent.com/40228854/45398547-e02ee080-b644-11e8-88b4-8475d793ccfa.JPG)

**Comment by PatBoj** [comment]
@helenemccarron I've baked book `biology 2e` locally and on the katalyst server using the same recipes. I've double checked if I have the same content as on the server. And locally everything is ok and on the server is not. I have no idea why this is happening.

## **Locally (it should look like this):**
![image](https://user-images.githubusercontent.com/20907906/45427018-13518e00-b69e-11e8-95d2-a38f670a140e.png)

## **From katalyst server:**
![image](https://user-images.githubusercontent.com/20907906/45427027-1e0c2300-b69e-11e8-8263-f05ee586e5c3.png)

**Comment by helenemccarron** [comment]
After rebaking with the latest CSS on katAW.rozzarzona.ropucha and clearing the cache, this is what I see, is this correct?

![2018-09-12_09-03-48](https://user-images.githubusercontent.com/8514591/45430485-0798a400-b66b-11e8-9088-7230a6966103.png)

**Comment by openstaxalina** [comment]
@patboj @helenemccarron note in the second comment on the issue - **only certain chapters have the updated classes in the content on katalyst01**.  I think that is causing the discrepancy with other chapters.

**Comment by PatBoj** [comment]
@openstaxalina Yes, so the chapters marked by red arrows will not appear in the baked book until all of the classes will be changed in the content. But now everything is ok, my changes are visible and the recipes is working as it suppose so.

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.

Biology 2e
<img width="314" alt="screen shot 2018-09-13 at 16 10 33" src="https://user-images.githubusercontent.com/40228918/45493744-be7e4800-b76f-11e8-8db4-08ad840c5ba1.png">

Concepts of Biology
<img width="315" alt="screen shot 2018-09-13 at 16 11 21" src="https://user-images.githubusercontent.com/40228918/45493760-c3db9280-b76f-11e8-9515-43bb54272e95.png">
