### ISSUE TITLE
Principles of Management ONLY: Change Exploring Business Careers class

### ISSUE THREAD

**Issue by brittany-johnson** [Connexions/cnx-recipes#567]
@Bkblodget commented on [Mon Aug 13 2018](https://github.com/Connexions/webview/issues/1828)

Please change the feature title from Exploring Business Careers to **Exploring Managerial Careers**.

Please change the associated class from exploring-business-careers to `exploring-manager-careers`.

Also need to change the text that displays to “Exploring Managerial Careers”.

**Comment by brittany-johnson** [comment]
![screen shot 2018-08-20 at 1 26 20 pm](https://user-images.githubusercontent.com/24909007/44359213-d7e7e900-a47c-11e8-9fd1-8083c60973d8.png)
Title of note has been changed in recipe and class has been updated

**Comment by Stackblocks** [comment]
Seeing the class changed in the markup, but the note box in Webview is lacking the "Exploring Managerial Careers" header. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8838b763-bb03-432d-b53f-a772084a8943)

**Comment by Stackblocks** [comment]
May have been an issue with baking state / server status, but now displaying consistently correctly.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/16160b5e-0fe6-4fbe-8e19-8fd6ed9dae0c)
