### ISSUE TITLE
Exercise answers counting problem

### ISSUE THREAD

**Issue by uskka** [Connexions/cnx-recipes#571]
All answers start with "a". Appears in every exercise that has multiple answers. It only appears on Windows 10 with Mozilla Firefox.

https://katalyst01.cnx.org/contents/tWu56V64@34.15:py_tPsy1@14/3-1-Terminology

Webview
![screenshot-katalyst01 cnx org-2018-08-22-13-56-59](https://user-images.githubusercontent.com/40228918/44462114-c5ec7e80-a613-11e8-9ba8-bb86714445ab.png)

PDF
![0](https://user-images.githubusercontent.com/40228918/44462203-1d8aea00-a614-11e8-832c-b93a855cbb50.png)

**Comment by PiotrKozlowski** [comment]
After talk with Stefan we established this error occurs only on Mozilla at Windows system.

List look like this: (there is `type="a"` which should generate `a.`, `b.` etc.) This is correct markup so i'am betting this is browser specific issue
```
<ol id="fs-idp17343632" type="a">
<li>...</li>
...
```

**Comment by Adrianltd** [comment]
This occurs also on Ubuntu in Firefox (on Chrome it's ok).

**Comment by Adrianltd** [comment]
I've found the answer. When we merge https://github.com/Connexions/webview/pull/1867 the problem will disappear. It looks like when you make a list `display: inline`, Firefox thinks that all `<li></li>` are one element, because they're in one line.

**Comment by PiotrKozlowski** [comment]
This does not occurs for me on Ubuntu Firefox :confused:

**Comment by PatBoj** [comment]
@uskka It should be OK right now, you can test it.

**Comment by uskka** [comment]
Good Job! Works fine. Tested on kastalyst01. 

![screenshot-katalyst01 cnx org-2018 08 29-14-42-03](https://user-images.githubusercontent.com/40228918/44788213-ba600100-ab99-11e8-9e01-f2014b44f960.png)
