### ISSUE TITLE
Different order of modules on webview and in pdf

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#579]
On katalyst01(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:Z8MO95Dz@20.1/References) first is module **Bringing It Together: Homework** and next one is **References**:

![module](https://user-images.githubusercontent.com/40228854/44784292-6fd88780-ab8d-11e8-83f6-a69c9b2929d3.JPG)

In PDF they are in different order:

![module_pdf](https://user-images.githubusercontent.com/40228854/44784310-7e26a380-ab8d-11e8-8547-7e44cd3e0bb0.JPG)

**Comment by wilkus27** [comment]
Verified on katalyst01

![order](https://user-images.githubusercontent.com/40228854/45293330-27f42180-b4f8-11e8-8772-af71467cae64.JPG)

**Comment by lwtchu** [comment]
In Chapter 1 it goes "Bringing It Together: Homework" and then into "References".

It should match the original before it changed and the change should've applied to the PDF since it's out of order in the PDF for chapter 12 and 13.

**Comment by helenemccarron** [comment]
@lwtchu we cannot change the order of collations per chapter in recipes, so we would have to align the PDF if not all chapters are identical.

**Comment by lwtchu** [comment]
@helenemccarron 

References and Bringing It Together: Homework should be flipped back. I'm going to fix the PDF to match since those are the two chapters that are out of order in the PDF. Sorry if my comment wasn't clear.

It should go:

Key Terms
Chapter Review
Formula Review
Practice
Homework
Bringing It Together: Homework
References 
Solutions

**Comment by wilkus27** [comment]
Verified on katalyst01:

- in all chapters with module **Bringing It Together: Homework** order displays correctly

![with](https://user-images.githubusercontent.com/40228854/45884155-6d93d280-bdb3-11e8-9f97-15b930732e81.JPG)

- in all chapters without this module order is as follows:

![without](https://user-images.githubusercontent.com/40228854/45884800-20b0fb80-bdb5-11e8-801b-89e023c363be.JPG)

-in one chapter is extra module **Bringing It Together: Practice**. Order of modules from this chapter is the same in PDF.

![3](https://user-images.githubusercontent.com/40228854/45885027-a2088e00-bdb5-11e8-9121-f386fd260bea.JPG)

**Comment by openstaxalina** [comment]
Confirmed we are back to the original (desired) after rev and rebake on staging:
![screen shot 2018-09-21 at 2 44 26 pm](https://user-images.githubusercontent.com/7863733/45902690-e3487000-bdac-11e8-9a62-f6ec033e18d0.png)
