### ISSUE TITLE
All of the figures in one section are unnumbered

### ISSUE THREAD

**Issue by uskka** [Connexions/cnx-recipes#580]
All of the figures and tables in this section are unnumbered. 

https://katalyst01.cnx.org/contents/tWu56V64@34.15:p4GSo9Dk@18/Statistical-Tables

PDF
![u](https://user-images.githubusercontent.com/40228918/44794404-bf787c80-aba8-11e8-800d-644435bb8724.png)
Webview
![screenshot-katalyst01 cnx org-2018 08 29-16-28-34](https://user-images.githubusercontent.com/40228918/44794408-c0a9a980-aba8-11e8-972c-9ebf0deef28d.png)

**Comment by openstaxalina** [comment]
I believe this is occurring because the modules are missing the appendix class.  moving to the content-managers repo.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #277](https://github.com/Connexions/content-managers/issues/277) via [**ZenHub**](https://www.zenhub.com/)
