### ISSUE TITLE
Module without appendix class

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#581]
On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:kIxIs3X-@9/Practice-Tests-1-4-and-Final-Exams) one module is missing appendix class:

![append](https://user-images.githubusercontent.com/40228854/44795141-44b06100-abaa-11e8-9a76-2ef24f583bac.JPG)

The result of this is that tables are unnumbered.
This is how it looks in PDF:

![append_pdf](https://user-images.githubusercontent.com/40228854/44795181-61e52f80-abaa-11e8-8258-5beabe763413.JPG)

**Comment by helenemccarron** [comment]
@openstaxalina This is due to the appendix missing the class `appendix`

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #278](https://github.com/Connexions/content-managers/issues/278) via [**ZenHub**](https://www.zenhub.com/)
