### ISSUE TITLE
Many different margins

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#584]
On katalyst01 in the whole book are inconsistent margins. A few examples:

https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:AeeflfGs@10/10-1-Two-Population-Means-with-Unknown-Standard-Deviations

![align1](https://user-images.githubusercontent.com/40228854/44845694-898dd380-ac4e-11e8-9c88-0676c626f287.JPG)

![align2](https://user-images.githubusercontent.com/40228854/44845701-8eeb1e00-ac4e-11e8-8c17-241439dd1303.JPG)

https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:_WrUBaGD@6/10-2-Two-Population-Means-with-Known-Standard-Deviations

![align3](https://user-images.githubusercontent.com/40228854/44845780-be018f80-ac4e-11e8-8aaf-0dc891d3e949.JPG)

**Comment by helenemccarron** [comment]
The content is inconsistently using paragraphs, which have padding applied left and right.
![2018-08-30_13-37-55](https://user-images.githubusercontent.com/8514591/44872043-2b66ed80-ac5a-11e8-85f1-20abae4d3a54.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #285](https://github.com/Connexions/content-managers/issues/285) via [**ZenHub**](https://www.zenhub.com/)
