### ISSUE TITLE
Extra empty header

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#585]
On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:tnzKK6cn@2/11-8-Lab-2-Chi-Square-Test-of-Independence) in **NOTE** box is extra empty header:

![lines2](https://user-images.githubusercontent.com/40228854/44847376-96f98c80-ac53-11e8-99ac-7bf6c5c7d027.JPG)

This issue could be related with problems from https://github.com/Connexions/cnx-recipes/issues/576 and https://github.com/Connexions/webview/issues/1872.

**Comment by PatBoj** [comment]
It's **not** a content issue, I've checked.

## **Improper display**
![image](https://user-images.githubusercontent.com/20907906/44849741-63226500-ac5b-11e8-9943-5de5e26a51a8.png)
![image](https://user-images.githubusercontent.com/20907906/44849745-6584bf00-ac5b-11e8-8048-393721b012b0.png)

## **Proper display**
![image](https://user-images.githubusercontent.com/20907906/44849756-6c133680-ac5b-11e8-99cd-88de7dbc5fd9.png)
![image](https://user-images.githubusercontent.com/20907906/44849759-6fa6bd80-ac5b-11e8-8ed1-1d0ec46d69e3.png)

So this issue can be related to recipes.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/content-managers #306](https://github.com/Connexions/content-managers/issues/306) via [**ZenHub**](https://www.zenhub.com/)
