### ISSUE TITLE
All headers in the same size

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#586]
On katalyst01 in two modules all headers are in the same size.
1) https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:w-xBY099@6/E-Mathematical-Phrases-Symbols-and-Formulas

![head](https://user-images.githubusercontent.com/40228854/44851128-9ff05b00-ac5f-11e8-9d30-0b9045207d21.JPG)

PDF:

![head_pdf](https://user-images.githubusercontent.com/40228854/44851133-a7176900-ac5f-11e8-9691-dbcf525f99de.JPG)

2) https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:0LoYM_DS@6/F-Notes-for-the-TI-83-83-84-84-Calculators

**Comment by openstaxalina** [comment]
Resolved via https://github.com/Connexions/webview/issues/1637 and will be visible in updated content on staging.cnx.org.  Closing this issue.
