### ISSUE TITLE
Change to Managerial Decisions: Practice Header

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#588]
@openstaxalina commented on [Wed Aug 29 2018](https://github.com/Connexions/webview/issues/1885)

![mde pom](https://user-images.githubusercontent.com/7863733/44801018-870f7900-ab7d-11e8-9014-10d9fa80ccdb.png)

This issue was already resolved in the PDF; I am not sure how.  Maybe in the collation instructions?

Content: https://content02.cnx.org/contents/smnX8BSm:UiFE6wQb

**Comment by brittany-johnson** [comment]
![screen shot 2018-09-04 at 3 49 19 pm](https://user-images.githubusercontent.com/24909007/45057043-2e971a80-b05a-11e8-95a7-59474a66f490.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4c6b570e-c9d7-4b87-85cc-925b8e4045fa)
