### ISSUE TITLE
Change to Management Applications Skills: Practice Header

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#589]
@openstaxalina commented on [Wed Aug 29 2018](https://github.com/Connexions/webview/issues/1884)

![msae pom](https://user-images.githubusercontent.com/7863733/44800727-ba053d00-ab7c-11e8-919b-955c9c0b592a.png)

This is already correct in the PDF; I am not sure how.  Maybe the collation instructions?

Content: https://content02.cnx.org/contents/smnX8BSm:yiA6pMgN

**Comment by brittany-johnson** [comment]
![screen shot 2018-09-04 at 2 54 14 pm](https://user-images.githubusercontent.com/24909007/45054389-6ef29a80-b052-11e8-8063-5763cd1982a5.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code. ![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b9ffd2e2-b6d7-43bd-96cc-ffe305bef129)
