### ISSUE TITLE
Missing sections in PDF and Webview

### ISSUE THREAD

**Issue by uskka** [Connexions/cnx-recipes#594]
PDF is missing the "The Expenditure-Output Model" section and Webview is missing "B | The Expenditure-Output Model" section and "The Expenditure-Output Model" looks like it is not baked 
because all of the figures are unnumbered and tables descriptions are grey. 

https://staging.cnx.org/contents/J_WQZJkO@6.1:2cZ9K6tp@4/The-Expenditure-Output-Model

PDF
![screenshot-d3bxy9euw4e147 cloudfront net-2018 09 05-14-02-15](https://user-images.githubusercontent.com/40228918/45094416-877ab780-b11b-11e8-9db4-0eeecaa18881.png)

Webview
![screenshot-staging cnx org-2018 09 05-14-01-56](https://user-images.githubusercontent.com/40228918/45094421-8a75a800-b11b-11e8-9374-4006e9b3a5be.png)

Webview table from "The Expenditure-Output Model"
![screenshot-staging cnx org-2018 09 05-12-14-01 1](https://user-images.githubusercontent.com/40228918/45094766-89914600-b11c-11e8-83f9-abb7e35d4489.png)

**Comment by helenemccarron** [comment]
@openstaxalina this looks like a classic case of a missing `appendix` class.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #292](https://github.com/Connexions/content-managers/issues/292) via [**ZenHub**](https://www.zenhub.com/)
