### ISSUE TITLE
Tables from Answer Key without os-table class

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#595]
On staging.cnx.org (https://staging.cnx.org/contents/kRfPjKij@5.1:pKpFhGyF@5.1/Answer-Key) all tables in **Answer Key** don't have `os-table` class:

![table](https://user-images.githubusercontent.com/40228854/45097480-44244700-b123-11e8-8587-a49e09690f78.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 could you clarify the end-user impact?  How does the display compare to the PDF?

**Comment by wilkus27** [comment]
@openstaxalina When table don't have os-table class it causes issue with margins, which you have referenced and between paragraphs and this kind of tables occur blank spaces:

staging.cnx.org (https://staging.cnx.org/contents/kRfPjKij@5.1:pKpFhGyF@5.1/Answer-Key -> answers for **Chapter 8**)

![table2](https://user-images.githubusercontent.com/40228854/45147803-1512e180-b1c6-11e8-9302-d088c589f531.JPG)

This is how it looks in PDF:

![table_pdf](https://user-images.githubusercontent.com/40228854/45147826-2360fd80-b1c6-11e8-81a8-9e68fcf9430c.JPG)

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/kRfPjKij@4.5:pKpFhGyF@4.5/Answer-Key)
tables display without blank spaces

![table_blank](https://user-images.githubusercontent.com/40228854/45291316-1c056100-b4f2-11e8-9fc5-d976edd9d9d5.JPG)
