### ISSUE TITLE
Intro to Business - bulleted lists within a table not showing

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-recipes#596]
# Scenario

List-style for a list within a table is set to bulleted - styling is correct in PDF but bullets are not showing in webview

# Reproducibility Details

- **https://cnx.org/contents/Tgl3H6iq@4.164:aJs0fVsd@4/6-2-Planning**: 

## Screenshots

**PDF**
![Screen Shot 2018-09-05 at 10.52.07 AM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/c651dc44-f7f1-4c90-afc6-88d3b05094ed)

**Markup**
![Screen Shot 2018-09-05 at 10.52.46 AM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/70ce4aec-08ff-410f-9ba7-afb4093cff9b)

**Webview**
![Screen Shot 2018-09-05 at 10.52.15 AM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/8794b765-47aa-4d4d-aef9-19af41e27afd)

**Comment by openstaxalina** [comment]
assigning to @lwtchu to prioritize.  I wasn't sure if this was moderate or low based on our Slack thread.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/webview #1923](https://github.com/Connexions/webview/issues/1923) via [**ZenHub**](https://www.zenhub.com/)
