### ISSUE TITLE
AP Physics - Appendix has two symbol sections, orphaned index term

### ISSUE THREAD

**Issue by lwtchu** [Connexions/cnx-recipes#598]
# Scenario

There's two "SYMBOL" sections and drift velocity is orphaned

# Reproducibility Details

- **Impact area**:  Index
- **User**: 
- **URL / Location**: https://staging.cnx.org/contents/jQSmhtXo@17.1:Xm0hU3Qa@17.1/Index
- **How many times were you able to reproduce the issue?** 

## Steps to reproduce:

- Step 1
- Step 2
- Step 3

## Screenshots

![Screen Shot 2018-09-05 at 3.32.56 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/5fbb778e-1dbc-4528-b626-aaffa2aff708)

# Environment:

- **Instance**: staging
- **OS**: mac
- **Browser**:  chrome

# Impact

- **Severity**: 
- **Frequency of occurrence**:

**Comment by openstaxalina** [comment]
This will be handled in content: https://github.com/Connexions/content-managers/issues/276
