### ISSUE TITLE
Concept in Action has a Link to Learning Title in Webview

### ISSUE THREAD

**Issue by lwtchu** [Connexions/cnx-recipes#600]
@marcjeannott commented on [Tue Sep 04 2018](https://github.com/Connexions/content-managers/issues/291)

While regression testing I noticed that the webview call it "Link to Leaning" but the PDF shows a "Concept in Action" 

![concept_in_action_missing_Concepts.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/2ba936c0-9d90-4323-aa62-a36df299aa75)

This is also the case for **Evolution in Action** 
https://staging.cnx.org/contents/s8Hh0oOc@14.1:-Yx1m5Xz@10/1-1-Themes-and-Concepts-of-Biology
![evolution connection](https://user-images.githubusercontent.com/33228728/45175288-b30ca900-b1d2-11e8-8278-f7f682c033bd.jpg)

and **Career Connection**
https://staging.cnx.org/contents/s8Hh0oOc@14.1:-Yx1m5Xz@10/1-1-Themes-and-Concepts-of-Biology
![2018-09-06_12-47-46](https://user-images.githubusercontent.com/33228728/45175454-1a2a5d80-b1d3-11e8-8edc-e72f32a4a68b.jpg)

**Comment by openstaxalina** [comment]
![screen shot 2018-09-06 at 11 45 46 am](https://user-images.githubusercontent.com/7863733/45172252-70df6980-b1ca-11e8-92dc-1b125589fdcc.png)

https://staging.cnx.org/contents/s8Hh0oOc@14.1:-Yx1m5Xz@10/1-1-Themes-and-Concepts-of-Biology

**Comment by openstaxalina** [comment]
@marcjeannott would you be able to find at least one instance of Evolution in Action, and one instance of Career Connection, and share the side-by-side PDF vs Webview and also a link to the content on staging?

**Comment by marcjeannott** [comment]
I've added screenshots with links to the module in my original comment.

**Comment by helenemccarron** [comment]
This is possible (although not ideal) with those two selectors:

`className: 'interactive:not(.non-majors)'` for "Link to Learning"
and 
`(className: 'interactive.non-majors'` for "Concepts in Action"

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/s8Hh0oOc@11.15:-Yx1m5Xz@8/1-1-Themes-and-Concepts-of-Biology)

![concept_learning](https://user-images.githubusercontent.com/40228854/45396645-f6d13980-b63c-11e8-9540-bca03849ac81.JPG)
