### ISSUE TITLE
Unnumbered table in Preface

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#601]
On staging.cnx.org (https://staging.cnx.org/contents/bDIuMp-w@9.1:Hd4bYWPU@7/Preface) don't work flag https://github.com/Connexions/cnx-recipes/issues/455 - tables from Preface are not numbered:

![biology_ap](https://user-images.githubusercontent.com/40228854/45167455-799b6400-b1f9-11e8-8bd9-a46d6067c8b5.JPG)

**Comment by openstaxalina** [comment]
In this case, the PDF doesn't have a number either:
![screen shot 2018-09-06 at 10 37 44 am](https://user-images.githubusercontent.com/7863733/45168461-ef370e00-b1c0-11e8-8c60-8f82bc58b3a2.png)

Therefore, I am going to close this issue.
