### ISSUE TITLE
Check Your Understanding feature in College Physics is numbered in baked webview

### ISSUE THREAD

**Issue by oscryan** [Connexions/cnx-recipes#602]
The markup does not specify it should be unnumbered: `<exercise print-placement="here" type="check-understanding">` but it does include an empty label and the pdf does not number these exercises:

https://staging.cnx.org/contents/Ax2o07Ul@14.1:EC6WBNqn@9/1-2-Physical-Quantities-and-Units
<img width="640" alt="screen shot 2018-09-06 at 1 53 21 pm" src="https://user-images.githubusercontent.com/1895432/45178790-47c7d480-b1dc-11e8-8f0e-99f9eb4ca112.png">
<img width="495" alt="screen shot 2018-09-06 at 1 53 32 pm" src="https://user-images.githubusercontent.com/1895432/45178789-47c7d480-b1dc-11e8-9db0-ae3e80da76ea.png"><img width="483" alt="screen shot 2018-09-06 at 1 53 36 pm" src="https://user-images.githubusercontent.com/1895432/45178788-47c7d480-b1dc-11e8-880d-118cd9ccfa39.png">

**Comment by helenemccarron** [comment]
Mmmh I don't think the recipes currently support not numbering elements solely based on the label. Is that something desirable or would it be sufficient to add an `unnumbered` class to specific element that are normally numbered? cc @openstaxalina

**Comment by openstaxalina** [comment]
*Decision:* Helene to use the same behavior and styling for the (college) physics recipe that the ap-physics recipe already uses.

**Comment by helenemccarron** [comment]
Check your Understanding are no longer numbered in Physics:

![2018-09-11_11-55-07](https://user-images.githubusercontent.com/8514591/45375083-9e0c8d00-b5b9-11e8-8830-3de09b09174c.png)

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/Ax2o07Ul@11.33:EC6WBNqn@7/1-2-Physical-Quantities-and-Units)

![check](https://user-images.githubusercontent.com/40228854/45400109-10797d80-b64b-11e8-9ce4-85da21095c70.JPG)
