### ISSUE TITLE
AP Physics - math not showing up in index

### ISSUE THREAD

**Issue by PatBoj** [Connexions/cnx-recipes#604]
@lwtchu commented on [Wed Sep 05 2018](https://github.com/Connexions/webview/issues/1916)

![Screen Shot 2018-09-05 at 3.37.44 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/21b42c1c-c6ee-4f08-922d-abf539417f4a)

Should look like this: 
![Screen Shot 2018-09-05 at 3.41.23 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/dc49f844-30d1-4ec3-a0fb-d78e815cbe87)

https://staging.cnx.org/contents/jQSmhtXo@17.1:Xm0hU3Qa@17.1/Index

---

@PiotrKozlowski commented on [Thu Sep 06 2018](https://github.com/Connexions/webview/issues/1916#issuecomment-419028389)

This looks like content issue but maybe a recipes issue? @PatBoj, @Adrianltd can you confirm?

---

@oscryan commented on [Fri Sep 07 2018](https://github.com/Connexions/webview/issues/1916#issuecomment-419262652)

A problem in College physics as well:
<img width="810" alt="screen shot 2018-09-06 at 5 32 23 pm" src="https://user-images.githubusercontent.com/1895432/45188631-d9463f00-b1fa-11e8-92e9-4c4fa944e44a.png">

**Comment by openstaxalina** [comment]
The resolution we currently have will break University Physics (Polish and maybe also English). 

We will **not** resolve this issue for any titles for Assignable Webview for Half.  Instead, we will develop a more comprehensive solution in future sprints.

cc @PatBoj @helenemccarron

**Comment by PatBoj** [comment]
Krzysiek already fixed this issue in easybake https://github.com/Connexions/cnx-easybake/pull/96.
