### ISSUE TITLE
College Physics equation numbering

### ISSUE THREAD

**Issue by oscryan** [Connexions/cnx-recipes#608]
# Scenario

College Physics equation numbering does not match from webview to PDF on Staging; on production, the equations do not seem to be numbered at all.

# Reproducibility Details

- **Impact area**: College Physics
- **User**: 
- **URL / Location**: staging https://cnx.org/contents/Ax2o07Ul@13.12:LJeKXQqg@13/Fission
production https://staging.cnx.org/contents/Ax2o07Ul@14.1:LJeKXQqg@11/32-6-Fission
staging https://staging.cnx.org/contents/Ax2o07Ul@14.1:Q7NR5SMN@8/21-4-DC-Voltmeters-and-Ammeters
production https://cnx.org/contents/Ax2o07Ul@13.12:Q7NR5SMN@8/DC-Voltmeters-and-Ammeters

## Screenshots
from staging
https://camo.githubusercontent.com/e4971cb971974d7009e02a3f3b84a44c23b347b4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562353732656334393265303966306432313139333832392f31343039653731382d356466352d343832372d613638642d303965343830613239363762
https://user-images.githubusercontent.com/1895432/45186491-448c1300-b1f3-11e8-96ac-2d761dcf224d.png

# Environment:

- **Instance**: staging
- **OS**: 10.13.6
- **Browser**: Firefox

**Comment by oscryan** [comment]
Neither of the examples I have posted here have class="unnumbered", either on staging or on production.

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/Ax2o07Ul@11.33:LJeKXQqg@9/32-6-Fission)

webview:

![order](https://user-images.githubusercontent.com/40228854/45352299-78cb4f00-b5b8-11e8-9485-fe19a2878ee1.JPG)

PDF:

![order_pdf](https://user-images.githubusercontent.com/40228854/45352306-7ff25d00-b5b8-11e8-89ba-d2385aa1b2c1.JPG)
