### ISSUE TITLE
Numbered Equations styled incorrectly in webview for College Physics

### ISSUE THREAD

**Issue by Adrianltd** [Connexions/cnx-recipes#609]
@oscryan commented on [Thu Sep 06 2018](https://github.com/Connexions/webview/issues/1924)

PDF on the right, staging webview on the left:
<img width="1270" alt="screen shot 2018-09-06 at 2 58 23 pm" src="https://user-images.githubusercontent.com/1895432/45181956-8b730c00-b1e5-11e8-8cb0-1a83cb54471b.png">

---

@openstaxalina commented on [Thu Sep 06 2018](https://github.com/Connexions/webview/issues/1924#issuecomment-419231127)

Link to content in screenshot: https://staging.cnx.org/contents/Ax2o07Ul@14.1:cPzgoAtX@5/21-2-Electromotive-Force-Terminal-Voltage#42247

Note that the number is in the wrong place for all numbered equations in College Physics.  This may be a cnx-recipes issue since we've only logged this for the one title.

<blockquote><div><strong><a href="https://staging.cnx.org/contents/Ax2o07Ul@14.1:cPzgoAtX@5/21-2-Electromotive-Force-Terminal-Voltage#42247">OpenStax CNX</a></strong></div></blockquote>

---

@PiotrKozlowski commented on [Fri Sep 07 2018](https://github.com/Connexions/webview/issues/1924#issuecomment-419356122)

Those numbers looks like `<span class="os-number">21.47</span>` but should look like:
```
<div class="os-equation-number">
   <span class="os-number">21.47</span>
   <span class="os-divider"> </span>
</div>
```
So this is recipes related.

Propably connected to https://github.com/Connexions/cnx-recipes/issues/597

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/Ax2o07Ul@11.33:aNsXe6tc@2/2-6-Problem-Solving-Basics-for-One-Dimensional-Kinematics)

![numbering](https://user-images.githubusercontent.com/40228854/45348039-d7d79680-b5ad-11e8-8fdd-ea8331a138c8.JPG)
