### ISSUE TITLE
Create Astronomy Recipe

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#622]
### Checklist
- [x] Update/create book map
- [x] Update books.txt with new book’s UUID
- [x] Create all notes config entries
- [x] Create all EOC config entries
- [x] Create all EOB config entries
- [x] Create all book specific config entries
- [x] Create all styleguide snippets
- [x] Update books.txt RECIPE_DESC with the new book’s description
- [x] Update manifest.json with the new book entry
- [x] Request a symlink to be created in OER.exports (+ verify it’s working before release)
- [x] Finalize book map to match recipe (include any change that might have been decided while developing the recipe)

**Comment by openstaxalina** [comment]
@Adrianltd could you verify that the bookmap has been updated?  If so, please close this issue.

**Comment by Adrianltd** [comment]
@openstaxalina It's already updated, I have just checked it once again and updated all I could.
