### ISSUE TITLE
Equation numbering is off

### ISSUE THREAD

**Issue by marcjeannott** [Connexions/cnx-recipes#636]
# Scenario
On Staging, the last equation number in chapter 5 is 5.47, with 5.48 and 5.49 found in the answer key. This appears correct. In the PDF, the last equation number in chapter 5 is 5.47, but the answer key numbers are 5.57 and 5.58 respectively. I'm currently unable to locate any other equations related to chapter 5, so I'm unsure why this is jumping all those numbers. The text wrapping issue is noted and another issue was opened for it.  This issue seems similar to https://app.zenhub.com/workspace/o/connexions/content-managers/issues/243

# Reproducibility Details

- **Impact area**: Staging?
- **User**: Marc?
- **URL / Location**: https://staging.cnx.org/contents/jQSmhtXo@19.1:WwXAbgy9@19.1/Answer-Key
- **How many times were you able to reproduce the issue?** ?

## Steps to reproduce:

- Step 1
Navigate to url location
- Step 2
Find chapter 5 equation number 5.48
- Step 3
Compare to the PDF
## Screenshots
![equation numbers](https://user-images.githubusercontent.com/33228728/45705017-0d482b00-bb3e-11e8-9d23-11e270cea4bb.jpg)

# Environment:

- **Instance**: Staging?
- **OS**: Mac
- **Browser**: Chrome 

# Impact

- **Severity**:  Show stopper?
- **Frequency of occurrence**: Seems to be happening in 25.61 as well
![equationsoff](https://user-images.githubusercontent.com/33228728/45705689-dd9a2280-bb3f-11e8-9cc3-c0679e9e8168.jpg)

**Comment by openstaxalina** [comment]
I believe this is no longer an issue.  I believe that this occurred because we were originally testing on old recipes 👎 

<img width="709" alt="screen shot 2018-09-20 at 5 44 52 pm" src="https://user-images.githubusercontent.com/7863733/45850760-f69c0280-bcfc-11e8-916f-a2966101f2a0.png">

Closing this issue.
