### ISSUE TITLE
Different order of end of chapter material from webview to PDF

### ISSUE THREAD

**Issue by marcjeannott** [Connexions/cnx-recipes#637]
# Scenario

In AP Bio PDF the end of chapter material goes 1) Chapter Summary, 2) Review Questions 3) Critical Thinking Questions however, the webview has 1) Chapter Summary 2) Critical Thinking Questions 3) Review Questions. This is found throughout the entire book.

# Reproducibility Details

- **Impact area**: Staging?
- **User**: Marc?
- **URL / Location**: https://staging.cnx.org/contents/bDIuMp-w@12.1:oTCYejCa@12.1/Critical-Thinking-Questions
- **How many times were you able to reproduce the issue?** It's in the entire book

## Steps to reproduce:

- Step 1 Open book
- Step 2 In the TOC you'll see the order is wrong
- Step 3 Profit

## Screenshots

![wrong ordering.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/95595fc5-62a7-4659-91e9-8ff9f7badd20)

# Environment: Staging

- **Instance**: ?
- **OS**: Mac
- **Browser**: Chrome 

# Impact

- **Severity**: ?
- **Frequency of occurrence**: Throughout the book

**Comment by openstaxalina** [comment]
The order should be: 1) Chapter Summary, 2) Review Questions 3) Critical Thinking Questions.  Moving this into the next release!

**Comment by wilkus27** [comment]
Verified on katalyst01. In every chapter modules display in correct order.

![order](https://user-images.githubusercontent.com/40228854/45891790-c15be700-bdc6-11e8-8677-187233d1a6e6.JPG)

**Comment by openstaxalina** [comment]
Verified on staging.cnx.org after the rev today (tested 5 random chapters):
![screen shot 2018-09-21 at 3 03 08 pm](https://user-images.githubusercontent.com/7863733/45903486-85695780-bdaf-11e8-8fbb-51bb02788430.png)
