### ISSUE TITLE
Suppress Answer Key in Biology 2e, Concepts of Biology

### ISSUE THREAD

**Issue by oscryan** [Connexions/cnx-recipes#638]
# Scenario

Different answers are collated in staging pdf and on staging webview (staging pdf matches prd pdf).

# Reproducibility Details

- **Impact area**: staging.cnx.org
- **User**: all
- **URL / Location**: https://staging.cnx.org/contents/s8Hh0oOc@16.1:O6nBsAJu@16.1/Answer-Key
- **How many times were you able to reproduce the issue?**  1

## Steps to reproduce:

- Rebake/enqueue collection
- compare pdf to baked webview

## Screenshots

<img width="1379" alt="screen shot 2018-09-20 at 4 02 13 pm" src="https://user-images.githubusercontent.com/1895432/45846859-a7e76c00-bcee-11e8-809f-ddb195ddfd05.png">

# Environment:

- **Instance**: staging.cnx.org
- **OS**: 10.13.6
- **Browser**: firefox

# Impact

- **Severity**: 
- **Frequency of occurrence**:

**Comment by openstaxalina** [comment]
The Answer Key should contain every-other-answer, beginning with the first question in each section.  The sections are:

Art Connection Questions
Review Questions
Critical Thinking Questions

For example, if Art Connections are questions 1-3, Review Questions are questions 4-20, and Critical Thinking Questions are 21-30, the Answer Key would include answers to questions 1, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 21, 23, 25, 27, 29.

**Comment by openstaxalina** [comment]
I am moving this issue into the next release.  We will discuss with the Katalyst team when we get the chance!

**Comment by Bkblodget** [comment]
https://github.com/Connexions/oer.exports/issues/1637 I believe Kerwin's last comment in this issue captures the behavior we are seeing here

**Comment by lwtchu** [comment]
Confirmed this affects Biology 2e also

**Comment by helenemccarron** [comment]
I established that the root of this issue is the discrepancy between the PDF removing half of the answers ignoring odd and even while the recipe remove strictly only odd solutions. @openstaxalina was the decision to remove the answers from the content finalized or should we try to find a hack in recipes to make this work?

**Comment by openstaxalina** [comment]
@helenemccarron we haven't been able to finalize a decision yet.  We will park at Books scrum tomorrow.

**Comment by openstaxalina** [comment]
(If this requires coding, I understand that this will move to the next release.)

**Comment by openstaxalina** [comment]
**Decision:** Suppress Answer Key in the Assignable Webview version of _Biology 2e_ and _Concepts of Biology_.  These solutions should be stripped out of the files during baking.

**Comment by openstaxalina** [comment]
@helenemccarron please note the decision on this.  We should try to get this into the current sprint if possible; maybe an item for discussion on Monday's call?  cc @brittweinstein @paulinaszczucinska @PatBoj @Adrianltd

**Comment by brittweinstein** [comment]
Go into Biology recipe, make sure there is no answer key collation. Make sure all answers for answer key are trashed at end of recipe. Per @helenemccarron this is already hidden in AP Biology, but not the other Bios.

**Comment by PatBoj** [comment]
Ready for testing.

**Comment by wilkus27** [comment]
**Concepts of Biology** - veryfied on katalyst01

![answer_key](https://user-images.githubusercontent.com/40228854/48257814-e27aa480-e413-11e8-98b7-cc2f3626e5cd.JPG)

**Comment by uskka** [comment]
Biology 2e - veryfied on katalyst01.


![screenshot-katalyst01 cnx org-2018 11 09-12-53-51](https://user-images.githubusercontent.com/40228918/48261219-a13bc200-e41e-11e8-9ab9-a37cb4397608.png)
