### ISSUE TITLE
Visual Connection repeats twice

### ISSUE THREAD

**Issue by Adrianltd** [Connexions/cnx-recipes#642]
@marcjeannott commented on [Fri Sep 21 2018](https://github.com/Connexions/webview/issues/1956)

In *AP Biology* the sections called "Visual Connection" appear twice. This is found throughout the book, but here's a link to one of them: https://staging.cnx.org/contents/bDIuMp-w@12.1:wIx28lku@6/11-2-Sexual-Reproduction

![visualconnectionx2](https://user-images.githubusercontent.com/33228728/45886026-98fbca80-bd7d-11e8-892a-1b1855e37dec.jpg)

Currently on production server, it correctly only shows one visual connection. 

---

@openstaxalina commented on [Fri Sep 21 2018](https://github.com/Connexions/webview/issues/1956#issuecomment-423653944)

We will park this on Monday to determine if we could/should resolve this in the content.

---

@PiotrKozlowski commented on [Mon Sep 24 2018](https://github.com/Connexions/webview/issues/1956#issuecomment-423886138)

There are two `<header>` tags so it's probably related to recipes. @Adrianltd, @PatBoj can you confirm?
```
<header>
   <h3 class="os-title" data-type="title" data-label-parent="Visual Connections">
      <span class="os-title-label">Visual Connection</span>
   </h3>
</header>
<header>
   <h3 class="os-title" data-type="title" data-label-parent="Visual Connections">
      <span class="os-title-label">Visual Connection</span>
   </h3>
</header>
```

---

@Adrianltd commented on [Mon Sep 24 2018](https://github.com/Connexions/webview/issues/1956#issuecomment-423890464)

I believe it's the same as here https://github.com/Connexions/content-managers/issues/305.

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:wIx28lku@5/11-2-Sexual-Reproduction), e.g:

![visual](https://user-images.githubusercontent.com/40228854/46008940-67a53680-c0be-11e8-8100-a5bf290e8375.JPG)

I have tested one randomly selected chapter from each unit.
