### ISSUE TITLE
EOC/EOB Section Linking and Numbering Not Correct In Baked PDF TOC

### ISSUE THREAD

**Issue by brittany-johnson** [Connexions/cnx-recipes#650]
# What happened?

EOC/EOB section titles in TOC of Baked PDF link to nothing when clicked and are numbered with the improper page number.

# Reproducibility Details
- Switch to the `styles` branch whcih contains the baked PDF template 
- Run the `sass` command in terminal to ensure that the generated PDF contains the latest style: `sass ./file-path/intro-business.scss ./file-path/styles/output/intro-busienss.scss`
- Run the `prince` command to generate the baked PDF: `prince ./file-path/data/intro-business-baked.xhtml`
- The baked PDF will be generated in the `data` folder 

# Environment:

- **Book(s)**: intro-business
- **URL/Server**: N/A
- **Location (page number, chapter/section)**: Table of Contents
- **Suggested nearby searchable text**: `Key Terms`
- **Browser**: N/A

# Screenshots

![screen shot 2018-09-25 at 3 07 59 pm](https://user-images.githubusercontent.com/24909007/46040085-fcb32a00-c0d4-11e8-9ada-1559461c4419.png)

# Additional notes

N/A

**Comment by brittany-johnson** [comment]
@Stackblocks ready for review! Please let me know if the testing instructions aren't clear

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.
