### ISSUE TITLE
Figure Numbering off

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#654]
@marcjeannott commented on [Mon Sep 24 2018](https://github.com/Connexions/webview/issues/1957)

In AP Bio, Figure 15.7 in the PDF is numbered 15.8 in the baked webview.  https://staging.cnx.org/contents/bDIuMp-w@16.1:MWnotoAf@11/15-2-Prokaryotic-Transcription

![unequalfigurenumbers](https://user-images.githubusercontent.com/33228728/45967489-c9e53500-bff3-11e8-9a84-fe90dd58096f.jpg)

It mysteriously bumps up a number (the last figure number in 15.1 is Figure 15.6) from one section to the next. Both Ryan and I have looked at this, and we can't figure out where this missing figure is coming from. My _best guess_ is that somehow the figure in the "Science Practice Challenge Questions" called Figure 15.18 (so 15.19 in current baked webview) is also being counted as 15.7 in the baked webview. In the unbaked book, this figure would be the only thing in between Figures 15.6 and 15.7. 

May the force be with you. 🙏 

---

@PiotrKozlowski commented on [Thu Oct 04 2018](https://github.com/Connexions/webview/issues/1957#issuecomment-426929901)

This is related to recipies or content. @PatBoj , @Adrianltd can you confirm?

**Comment by PatBoj** [comment]
@openstaxalina The _Teacher Support_ section appears in raw html file and also in file baked by me, but not in the pdf or online view of the book. I suppose that _Teacher Support_ should be visible for teachers only. If it's true, then figures in _Teacher Support_ section shouldn't be numbered or at least numbered independent of other images. Tell me what you think, I've provided screens to clarify what i mean.

### **File baked by me:**
![image](https://user-images.githubusercontent.com/20907906/46530831-549f1d00-c89b-11e8-9b6e-5daf8ebc4568.png)

### **Book from cnx.org:**
![image](https://user-images.githubusercontent.com/20907906/46530843-608adf00-c89b-11e8-9def-869e9f222ff1.png)

**Comment by openstaxalina** [comment]
I agree this is content related.  We are looking at new ways to appropriately review, prioritize, and transfer issues to the content managers.  I recommend that @lwtchu move this issue to the content managers when appropriate.  (Note that this is the last remaining issue that needs to be resolved in order to bake AP Biology.)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #422](https://github.com/Connexions/content-managers/issues/422) via [**ZenHub**](https://www.zenhub.com/)
