### ISSUE TITLE
Extra headers in Exercises section

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#659]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/LnN76Opl@14.4:MYey3fWo@14.4/Exercises) in **Exercises** sections are headers with information with which module exercises are related. But there is no such information in PDF.

![ad_head](https://user-images.githubusercontent.com/40228854/46653164-8965e980-cba5-11e8-805e-0721cad82bb8.JPG)

PDF:

![ad_head_pdf](https://user-images.githubusercontent.com/40228854/46653174-91258e00-cba5-11e8-87d9-41d39565825b.JPG)

**Comment by wilkus27** [comment]
Same problem in section **Collaborative Group Activities**:

![ad_head2](https://user-images.githubusercontent.com/40228854/46665998-be823400-cbc5-11e8-9244-855407bf677f.jpg)

There are no headers in PDF.

**Comment by openstaxalina** [comment]
Module headers should be removed in these two places so that the heading structure matches the PDF.

**Comment by Adrianltd** [comment]
Should be fixed with https://github.com/Connexions/cnx-recipes/pull/653/commits/750744c43944f2cf743218fdedbafdcd88c60dd4

**Comment by wilkus27** [comment]
Verified on katalyst01:

**Exercises**

![head_ex](https://user-images.githubusercontent.com/40228854/46873999-60a95280-ce38-11e8-8e63-51aa5ff461d2.JPG)

**Collaborative Group Activities**

![head_col](https://user-images.githubusercontent.com/40228854/46874021-74ed4f80-ce38-11e8-9e85-15d46a8f0c24.JPG)
