### ISSUE TITLE
Paragraph in Learning Objectives

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#662]
On katalyst01 (https://katalyst01.cnx.org/contents/LnN76Opl@14.4:B8pDv1hY@3/9-3-Impact-Craters) first paragraph is in **Learning Objectives** box:

![text](https://user-images.githubusercontent.com/40228854/46814605-65f39800-cd79-11e8-8f8f-c57745fc86d8.JPG)

PDF:

![text_pdf](https://user-images.githubusercontent.com/40228854/46814617-6e4bd300-cd79-11e8-9cc9-85b7b28f0d27.JPG)

This problem also appears in:
1) https://katalyst01.cnx.org/contents/LnN76Opl@14.4:8RKRuAeb@3/9-4-The-Origin-of-the-Moon
2) https://katalyst01.cnx.org/contents/LnN76Opl@14.4:xP2qaZ5q@7/9-5-Mercury

**Comment by Adrianltd** [comment]
@lwtchu @openstaxalina as we have discussed on Slack, this paragraph is inside the `section` with `learning-objectives` class in `raw` html. So that's `content` issue.
