### ISSUE TITLE
Remove size-scale function where being directly used for font-size

### ISSUE THREAD

**Issue by brittany-johnson** [Connexions/cnx-recipes#664]
# What happened?

While prototyping `baked-pdf` styles the function `size-scale` was used for calculating the values of properties like `font-size`, `margin`, etc. The function was used to make a mixin specifically for titles throughout the book, and now all places where `.size-scale` is being used as the value of `font-size` need to be replaced with one of the title mixins found in `/framework/mixins/_titles.scss`

# Reproducibility Details
N/A

# Environment:
To test, verify the font size of different types of text in the **baked-pdf**

# Screenshots

N/A

# Additional notes

N/A

**Comment by helenemccarron** [comment]
Additionally, let's make sure that the old `titles-h2-style-icon()` deprecated mixins are replaced with `titlte()`

**Comment by openstaxalina** [comment]
Closing; this is not high priority and will be finalized as part of Baked PDF iterations.
