### ISSUE TITLE
Table with gray caption

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#668]
1. On katalyst01 (https://katalyst01.cnx.org/contents/LnN76Opl@14.4:kW2s2fjA@14.4/Exercises) There is a table with gray caption:

![caption](https://user-images.githubusercontent.com/40228854/46855814-05aa3800-ce05-11e8-9340-209738eccfe5.JPG)

It might be related with https://github.com/Connexions/content-managers/issues/267

2. I am not sure why this table is called **Table A**. Tables in other books are named by letters just in Appendix sections. Tables from the middle of the chapters always are numbered one by one even they are in the sections from End of Chapter, like **Exercises**. @openstaxalina is it intentional here? 

PDF:
![caption_pdf](https://user-images.githubusercontent.com/40228854/46858098-d0a0e400-ce0a-11e8-9c61-169109329e0f.JPG)

**Comment by openstaxalina** [comment]
Since we are achieving a similar style to the PDF in both cases, I propose no change here.  @lwtchu could you review before the Thursday call, in case there is something I am missing?

**Comment by lwtchu** [comment]
Agree with Alina. No change here.
