### ISSUE TITLE
Turn on feature flags for University Physics

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#672]
# What happened?
_University Physics_ was released in Assignable Webview before we came up with feature flag functionality.  We didn't want to add to the test load for Assignable Webview for new books by turning on the flags for _University Physics_.  However, we eventually do need to turn on and test feature flags for this title.

# Reproducibility Details

- **Does it also happen in an incognito window?**: N/A
- **Does this happen in one place, a few places, or everywhere?**: everywhere for _University Physics_

# Environment:

- **Book(s)**: University Physics
- **URL/Server**: all
- **Location (page number, chapter/section)**: n/a
- **Suggested nearby searchable text**: n/a
- **Browser**: n/a

# Screenshots
N/A

# Additional notes
N/A

**Comment by Stackblocks** [comment]
Nothing unexpected discovered in review of flags-enabled U. Physics
