### ISSUE TITLE
Accounting - Red text absent in webview

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#674]
content03
GLOBAL

Red text absent (some company names are in red for pedagogical reasons).  This does appear in the PDF output.

PDF
![redtextpdf](https://user-images.githubusercontent.com/19212926/46978847-f1349c80-d09d-11e8-8953-a2b4e6eafa66.png)

Webview
![redtextwebview](https://user-images.githubusercontent.com/19212926/46978859-f691e700-d09d-11e8-9e16-d6bfd33f8ac0.png)

**Comment by openstaxalina** [comment]
Need to assess with @helenemccarron and @brittany-johnson whether it's possible to create colored text in webview.  I haven't seen this functionality before.

cc @lwtchu

**Comment by openstaxalina** [comment]
More pedagogical information: Real company names are in red; this is a market convention.  

OpenStax to advise whether red text is available and provide other suggestions if not.

**Comment by openstaxalina** [comment]
Per @helenemccarron, this is possible!  This is targeted for the 11/19 release.  cc @mwest-WWprod

**Comment by brittweinstein** [comment]
@lwtchu to specify if it is bolded and hex value.

**Comment by lwtchu** [comment]
Hex: ##CC0000
SHOULD NOT BE BOLD

**Comment by brittany-johnson** [comment]
Issue moved to [Connexions/webview #2025](https://github.com/Connexions/webview/issues/2025) via [**ZenHub**](https://www.zenhub.com/)
