### ISSUE TITLE
Accounting - Art oversized in webview

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#675]
content04
GLOBAL

As with [#3696](https://github.com/Connexions/oer.exports/issues/3696), art in webview is oversized. Art is correct within the PDF output.

![artoversizedwebview](https://user-images.githubusercontent.com/19212926/46979630-13c7b500-d0a0-11e8-9452-de739e8f3432.png)

We will proceed with the assumption that figures can be treated with the 'scaled down' class as with other books.

**Comment by openstaxalina** [comment]
@mwest-WWprod I believe the scaled-down class will need to be added to oversized art.  

Meanwhile, @helenemccarron or @brittany-johnson will need to ensure this class is enabled in the Accounting recipe.

cc @lwtchu

**Comment by lwtchu** [comment]
The image in the screenshot appears to not have the scaled down class. Let Matt know via email.
