### ISSUE TITLE
Accounting - Padding increase above images

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#678]
content03
GLOBAL

Padding above **images** is too small (sufficient above figures).  Please increase slightly.

![imagepadding_webview](https://user-images.githubusercontent.com/19212926/46980975-5c816d00-d0a4-11e8-864e-2f77b23c7f82.png)

**Comment by openstaxalina** [comment]
Need @lwtchu to review/specify a value for padding increase.

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/webview #2001](https://github.com/Connexions/webview/issues/2001) via [**ZenHub**](https://www.zenhub.com/)
