### ISSUE TITLE
Accounting - Leading in webview lists

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#679]
content03
GLOBAL

Lists in webview have inconsistent leading between items.

![listspacing_webview](https://user-images.githubusercontent.com/19212926/46982618-f77d4580-d0aa-11e8-9fb6-116bdf5a5cf6.png)

**Comment by openstaxalina** [comment]
@oscryan would you mind reviewing the content in this case?  I have never seen this kind of styling issue with a list.

If content is correct, please post a screenshot of the markup with a link, and remove your assignment.

cc @lwtchu

**Comment by oscryan** [comment]
The content is treated differently in each list item. The first item has the text inside only the item tag; the second item has two paragraph tags nested in the list tag. The third has no nesting, like the first. This seems to have caused the item number to center in the third case, but I don't know why it's different from the first.

**Comment by oscryan** [comment]
https://legacy-content03.cnx.org/content/m10005/latest
<img width="1115" alt="screen shot 2018-10-16 at 11 41 50 am" src="https://user-images.githubusercontent.com/1895432/47032674-8edcaa00-d138-11e8-8f76-093d2d14efa0.png">

**Comment by openstaxalina** [comment]
I seems that paras were used only for the list item that has more than one paragraph.

@oscryan is this semantically correct CNXML?  Unless you advise CNXML changes, I'll ask developers to review this.

**Comment by oscryan** [comment]
It's not consistent, but it's not incorrect. It might be best if we keep the styling on list items from changing due only to what's contained in them.

**Comment by openstaxalina** [comment]
Thank you!  I will ask the devs to look into this next sprint.

**Comment by brittany-johnson** [comment]
Issue moved to [Connexions/webview #2031](https://github.com/Connexions/webview/issues/2031) via [**ZenHub**](https://www.zenhub.com/)
