### ISSUE TITLE
Accounting - Addition of hanging indent in webview footnotes

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#680]
content03
GLOBAL

Footnote content in webview can be confusing without hanging indents. Please add if possible.

![footnoteindent_webview](https://user-images.githubusercontent.com/19212926/46982686-44611c00-d0ab-11e8-9325-3e390fb7af88.png)

**Comment by openstaxalina** [comment]
Agree.  
Description of hanging indents: https://guides.rasmussen.edu/c.php?g=225376&p=5846714

**Comment by brittany-johnson** [comment]
Issue moved to [Connexions/webview #2027](https://github.com/Connexions/webview/issues/2027) via [**ZenHub**](https://www.zenhub.com/)
