### ISSUE TITLE
Accounting - Module titles in webview assessments

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#681]
content03
GLOBAL

Module titles should not be listed in assessments (currently appear in Questions, Exercise Sets, Problem Sets, do not appear in Multiple Choice or Thought Provokers).

![assessment module headers_webview](https://user-images.githubusercontent.com/19212926/46983491-c272f200-d0ae-11e8-9c5c-a07f0ab2050f.png)

**Comment by openstaxalina** [comment]
Agree; this should be feasible.

**Comment by brittany-johnson** [comment]
Obviously not styled lol, but the EOC should now be structually correct. Module titles have been removed where necessary @Stackblocks 
![screen shot 2018-11-05 at 3 29 34 pm](https://user-images.githubusercontent.com/24909007/48027979-e8207380-e10f-11e8-9c6d-6c3b0dc23583.png)
![screen shot 2018-11-05 at 3 29 43 pm](https://user-images.githubusercontent.com/24909007/48027980-e8207380-e10f-11e8-98ed-6188982b81aa.png)
![screen shot 2018-11-05 at 3 29 54 pm](https://user-images.githubusercontent.com/24909007/48027981-e8207380-e10f-11e8-96e2-d4a9b3341f11.png)
![screen shot 2018-11-05 at 3 30 04 pm](https://user-images.githubusercontent.com/24909007/48027982-e8207380-e10f-11e8-8ae1-cbc697aa0fa6.png)
![screen shot 2018-11-05 at 3 30 15 pm](https://user-images.githubusercontent.com/24909007/48027983-e8207380-e10f-11e8-8ad8-391dfedf96a6.png)
![screen shot 2018-11-05 at 3 30 24 pm](https://user-images.githubusercontent.com/24909007/48027984-e8207380-e10f-11e8-920b-0d48d64db45d.png)
![screen shot 2018-11-05 at 3 30 35 pm](https://user-images.githubusercontent.com/24909007/48027986-e8207380-e10f-11e8-9154-d8b923689101.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3bf4b45d-4be8-413f-b95b-d9efc0bcf310)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d4beb4d4-7d13-4bd9-bcdd-cdc6a59aa792)
