### ISSUE TITLE
Support title and caption for a figure in the preface

### ISSUE THREAD

**Issue by lwtchu** [Connexions/cnx-recipes#682]
# What happened?

Currently the title is not supported in the preface for figures. Please see #670 for more information.

# Reproducibility Details

- **Does it also happen in an incognito window?**:  Sure
- **Does this happen in one place, a few places, or everywhere?**: Preface only

# Environment:

- **Book(s)**: Any book with title and caption for a figure
- **URL/Server**:  https://katalyst01.cnx.org/contents/b795b4f7-3318-4419-a338-8f5eeb0874ee@9
- **Location (page number, chapter/section)**: preface
- **Suggested nearby searchable text**: look for a figure in the preface
- **Browser**:

# Screenshots

# Additional notes

**Comment by openstaxalina** [comment]
Closing; this was already corrected with #670.
