### ISSUE TITLE
Intro  Business cannot be baked

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#687]
# What happened?
The baking process for Intro Business fails due to a recipe error. 

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
yes
- **Does this happen in one place, a few places, or everywhere?**:
everywhere

# Environment:

- **Book(s)**: any collection using the intro-business recipe
- **URL/Server**:  all servers (was found on staging
- **Location (page number, chapter/section)**: all book
- **Suggested nearby searchable text**: n/a
- **Browser**: all

# Screenshots

n/a

# Additional notes

**Comment by helenemccarron** [comment]
Addressed in #686, which reverses PR #657  - to test, the book should bake properly. No other change should be observed.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/59568cfd-aef9-4d67-bd88-794b6b629519)
