### ISSUE TITLE
Appendices in Astronomy

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#689]
On katalyst01 (e.g https://katalyst01.cnx.org/contents/LnN76Opl@14.4:_eJEiQMX@6/Units-Used-in-Science) modules from appendices should be numbered by letters and tables inside should be named in this way: **Table D1**, **Table D2** etc.

PDF:

![append_pdf](https://user-images.githubusercontent.com/40228854/47287124-7580a580-d5f1-11e8-9ece-b77deee6600c.JPG)

Webview:

![append](https://user-images.githubusercontent.com/40228854/47287132-7fa2a400-d5f1-11e8-9a8c-fb573edb4fac.JPG)

**Comment by lwtchu** [comment]
Probably missing `appendix` class. We can treat this as a high priority, easy fix.

**Comment by Adrianltd** [comment]
@lwtchu will this be changed also on katalyst01?

**Comment by lwtchu** [comment]
@Adrianltd this has been fixed on katalyst01
