### ISSUE TITLE
Examples in Appendix

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#690]
In Chemistry textbook **Examples** should be named by letter and number like **Example B1**
e.g. katalyst01 (https://katalyst01.cnx.org/contents/havxkyvS@12.1:njDsQlIO@8/B-Essential-Mathematics)

webview

![example](https://user-images.githubusercontent.com/40228854/47301312-e38f9180-d61e-11e8-8c53-ba224630ffee.JPG)

PDF

![example_pdf](https://user-images.githubusercontent.com/40228854/47301328-ed18f980-d61e-11e8-94d4-9fc48de590c1.JPG)

**Comment by openstaxalina** [comment]
@Adrianltd I moved this into the current sprint, but we can slide to the next sprint if you do not have time.  cc @paulinaszczucinska @helenemccarron

**Comment by wilkus27** [comment]
Verified on katalyst01

![example](https://user-images.githubusercontent.com/40228854/48837919-07add200-ed87-11e8-97ab-accd145e829e.JPG)
