### ISSUE TITLE
[dev-math] Numbering exercises continuously through the whole book

### ISSUE THREAD

**Issue by PatBoj** [Connexions/cnx-recipes#699]
There are two "types" of exercises in algebra books (_Prealgebra_, _Elementary Algebra_, _Intermediate Algebra_):
- at the end of every section (not collated),
- at the end of every chapter (collated, clustered by section).

Both of them should be numbering continuously through the book and the counter should be reset every each chapter.

Right now exercises at the end of sections are numbered by counter `exerciseMaybeInContent` in `$Config_ContentExercise_TitleContent` and those at the end of the chapters are numbered by counter exercise in `$Config_exerciseTitleContent`.

**Comment by PatBoj** [comment]
This PR will solve this issue https://github.com/Connexions/cnx-recipes/pull/748.

**Comment by wilkus27** [comment]
Veryfied on katalyst01 (e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.19:oPicsfnd@3.19/Exercises)

End of section 10.4:
![10 4](https://user-images.githubusercontent.com/40228854/50234689-8746b500-03b6-11e9-91ef-41719a986224.JPG)

Begining of section 10.5:
![10 5](https://user-images.githubusercontent.com/40228854/50234703-8e6dc300-03b6-11e9-8e90-c98100c05061.JPG)

End of section 10.5:
![10 5_end](https://user-images.githubusercontent.com/40228854/50234711-9299e080-03b6-11e9-9235-151d23a62c32.JPG)

Begining of Review Exercises:
![rev](https://user-images.githubusercontent.com/40228854/50234721-988fc180-03b6-11e9-8a69-d08278253a68.JPG)

End of Review Exercises and the begining of Practice Test:
![pract](https://user-images.githubusercontent.com/40228854/50234726-9d547580-03b6-11e9-9209-43e9fcb3b486.JPG)

Tested also in **Prealgebra** and **Intermediate Algebra**.
