### ISSUE TITLE
[dev-math] Collate solutions from each section to EOB 

### ISSUE THREAD

**Issue by PatBoj** [Connexions/cnx-recipes#700]
There are two "types" of exercises in algebra books (_Prealgebra_, _Elementary Algebra_, _Intermediate Algebra_):
- at the end of every section (not collated),
- at the end of every chapter (collated, clustered by section).

Solutions from exercises in every section should be collated, but I cannot manage to do that. `$Config_PartType_Solution: (moveTo: $AREA_EOB, );` moves only solutions from collated exercises.

**Comment by PatBoj** [comment]
This issue is solved by https://github.com/Connexions/cnx-recipes/pull/748.

**Comment by wilkus27** [comment]
Veryfied on katalyst01. I have randomly selected a few chapters from all of three Algebra textbooks. There are no more solutions inside the sections. All of them are in Answer Key. 

Numbering of solutions in Answer Key is consistent with PDF.
