### ISSUE TITLE
Numbering by Step #

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#704]
@wilkus27 commented on [Mon Nov 05 2018](https://github.com/Connexions/webview/issues/2038)

In _Elementary Algebra_ in **How To** note and in section **Key Concepts** there are lists which should be numbered by _Step 1, Step 2 etc._

webview (e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.14:Tj87ETCR@4/3-1-Use-a-Problem-Solving-Strategy)

![step_how_to](https://user-images.githubusercontent.com/40228854/48010120-4738b500-e11d-11e8-8b36-dcdb39309c6e.JPG)

PDF:
![step_how_to_pdf](https://user-images.githubusercontent.com/40228854/48010170-5d467580-e11d-11e8-8792-a27b918dd1fe.JPG)

webview (e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.14:7BOr1QuT@3.14/Key-Concepts)

![step_key](https://user-images.githubusercontent.com/40228854/48010210-72230900-e11d-11e8-80f8-aad07db06021.JPG)

PDF:
![step_key_pdf](https://user-images.githubusercontent.com/40228854/48010235-7d763480-e11d-11e8-82d6-e678d41a6a7d.JPG)

---

@openstaxalina commented on [Mon Nov 05 2018](https://github.com/Connexions/webview/issues/2038#issuecomment-436087142)

Hopefully these have the `stepwise` class on them; we should check in sprint planning.

---

@lwtchu commented on [Wed Nov 07 2018](https://github.com/Connexions/webview/issues/2038#issuecomment-436792627)

@openstaxalina they do :)!
![screen shot 2018-11-07 at 3 57 22 pm](https://user-images.githubusercontent.com/11299125/48163637-da045b80-e2a5-11e8-9edf-c50638ec1e16.png)

---

@openstaxalina commented on [Wed Nov 07 2018](https://github.com/Connexions/webview/issues/2038#issuecomment-436806517)

Thanks @lwtchu !
In that case, @PatBoj could you use that class to add the word "Step" before each number?  I think this is what we decided to do with all lists with that class.

cc @helenemccarron

**Comment by openstaxalina** [comment]
Adding labels since this occurs across the DevMath series.  
Also, we noted that Chemistry has stepwise lists in some instances.  @oscryan is verifying whether the class "stepwise" was also used in those cases.

cc @lwtchu

**Comment by PatBoj** [comment]
@openstaxalina Yes, I will extend this fix to be more useful to other books.

**Comment by wilkus27** [comment]
Tested on katalyst01 for **Chemistry**:

![chemistry](https://user-images.githubusercontent.com/40228854/49655466-07762d80-fa3b-11e8-945e-8e7019ec5c44.JPG)

cc @helenemccarron

**Comment by PatBoj** [comment]
@wilkus27 it's ready to test. You can bake math books from this branch https://github.com/Connexions/cnx-recipes/tree/dev-math-recipe.

**Comment by wilkus27** [comment]
Because this issue had to be solved in other way (explained in https://github.com/Connexions/webview/pull/2139#issuecomment-448526250) I need to test Chemistry again. 

**Chemistry** (baked from yummy.yeti branch)

![chem](https://user-images.githubusercontent.com/40228854/50589470-06dc8580-0e87-11e9-9b12-fde9dc6d3e29.JPG)

In all of three dev-math textbooks step lists also display correctly.

**Prealgebra** (baked from dev-math recipe branch)

![pre_how_to](https://user-images.githubusercontent.com/40228854/50589599-9b46e800-0e87-11e9-95c6-8956c98e9c9e.JPG)
