### ISSUE TITLE
Exercises under the number

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#714]
The content of the exercises from end of each sections should be displayed next to the number:

katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:zMLdd__D@7/1-1-Introduction-to-Whole-Numbers)

![ex_cont](https://user-images.githubusercontent.com/40228854/48557378-da74a600-e8e6-11e8-94c5-3dbfa0070c6b.JPG)

PDF:

![ex_cont_pdf](https://user-images.githubusercontent.com/40228854/48557391-e95b5880-e8e6-11e8-8b46-239bb5a9f113.JPG)

**Comment by brittany-johnson** [comment]
Issue moved to [Connexions/webview #2115](https://github.com/Connexions/webview/issues/2115) via [**ZenHub**](https://www.zenhub.com/)
