### ISSUE TITLE
Two Chapter Outline

### ISSUE THREAD

**Issue by Adrianltd** [Connexions/cnx-recipes#720]
@wilkus27 commented on [Thu Nov 08 2018](https://github.com/Connexions/webview/issues/2049)

On katalyst01 (e.g. https://katalyst01.cnx.org/contents/havxkyvS@12.1:uXg0kUa-@5/Introduction) in each _Introduction_ **Chapter Outline** occurs two times. The second one have **class="abstract"**. Probably it should be removed by content.

![abstract](https://user-images.githubusercontent.com/40228854/48202533-78a3c180-e365-11e8-94eb-87e07fe217fb.JPG)

---

@Adrianltd commented on [Tue Nov 13 2018](https://github.com/Connexions/webview/issues/2049#issuecomment-438212922)

@openstaxalina or @lwtchu could you confirm that this can be removed from content?

---

@openstaxalina commented on [Tue Nov 13 2018](https://github.com/Connexions/webview/issues/2049#issuecomment-438320928)

@lwtchu I assume that since this has class="abstract" it must be in the metadata field for "summary".

Would it be feasible to remove this from the metadata?  Is there any reason we should not do this?  

cc @helenemccarron 

---

@lwtchu commented on [Tue Nov 13 2018](https://github.com/Connexions/webview/issues/2049#issuecomment-438322081)

@openstaxalina i think this was a plan for us to remove "later"...maybe that later has come now. We currently don't have a way to edit this with batch so it'll take a while.

---

@openstaxalina commented on [Tue Nov 13 2018](https://github.com/Connexions/webview/issues/2049#issuecomment-438326317)

Thanks @lwtchu; we will discuss on tomorrow's call whether this could be suppressed via the recipe in the meantime.  

---

@openstaxalina commented on [Thu Nov 15 2018](https://github.com/Connexions/webview/issues/2049#issuecomment-439092422)

We will handle this via the recipe.

**Comment by openstaxalina** [comment]
@Adrianltd I moved this into the current sprint since Helene let me know you expect to finish this before code freeze.

**Comment by Adrianltd** [comment]
@Stackblocks this needs to be tested in `accounting, ap-biology, ap-physics, astronomy, biology, business-ethics, chemistry, dev-math, entrepreneurship, physics and u-physics`.
As far as we've discovered with @helenemccarron there's a tiny diff in `physics` in baked file, but it disappears on the webview.

On the left it's after the fix, on the right it's before the fix.
![2018-11-20_10-35-23](https://user-images.githubusercontent.com/40228907/48793017-fd8fc300-ecf5-11e8-9e62-017b6f9c497a.png)
But on the webview `Define radioactivity` didn't appear before the fix.
https://cnx.org/contents/Ax2o07Ul@14.4:pg7t-syq@5/Introduction-to-Radioactivity-and-Nuclear-Physics

Let me know if you can test it or if we should assign Natalia or Stefan to this.

**Comment by Stackblocks** [comment]
I was unable to successfully get tests set up for this, so if y'alls team would please take a look at it we would appreciate it. Thank you.

**Comment by wilkus27** [comment]
Verified on katalyst01

![chapter_outline](https://user-images.githubusercontent.com/40228854/48839345-7db43800-ed8b-11e8-8a56-a0e4ef0091c2.JPG)
