### ISSUE TITLE
Missing Learning Objectives

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#730]
On katalyst01 (e.g https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.4:MLADqXMi@8/10-1-Motivation) there are no headers **Learning Objectives** at the beginning of the sections.

webview:

![lo](https://user-images.githubusercontent.com/40228854/49371536-0de16e00-f6f8-11e8-8017-b65de05fefcd.JPG)

PDF:

![lo_pdf](https://user-images.githubusercontent.com/40228854/49371566-310c1d80-f6f8-11e8-9dfa-cfd28026309e.JPG)

**Comment by openstaxalina** [comment]
@Adrianltd I moved this into the current sprint, but it can be deferred until the next sprint if needed.

**Comment by Adrianltd** [comment]
Should be solved with https://github.com/Connexions/cnx-recipes/pull/710/commits/1c2aa7155ddb1ec1a7404b081e1a351c86bd5723

**Comment by wilkus27** [comment]
Verified on katalyst01

![lo](https://user-images.githubusercontent.com/40228854/49433485-7a20a800-f7b2-11e8-91da-b7d0bf4bdc1b.JPG)
