### ISSUE TITLE
Adjust the name on the Parameters tab: Developmental Mathematics (with recipe)

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#731]
Please change the name of the DevMath recipe to **Developmental Mathematics (with recipe)**.

**Comment by openstaxalina** [comment]
@helenemccarron I put an estimate on this, but feel free to adjust.

**Comment by helenemccarron** [comment]
@Stackblocks I have modified books.txt and the manifest, hopefully, this is enough to reflect the desired changes. I imagine you will have to run the DBmigration first though. The changes are on xiao.xiao.

**Comment by Stackblocks** [comment]
@helenemccarron new styles are showing in the dropdown after master was merged into xiao-xiao, but I'm still seeing Algebra Books even after a dbmigrate run and cache clear.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ea9c30eb-4e96-4e78-ab44-d024042820b5)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/756ff2ec-b92f-415c-bf62-66ceb46cfa12)
