### ISSUE TITLE
[Psychology] Tables

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#739]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.20:iLkaPS1F@8/1-4-Careers-in-Psychology) tables are displayed in different way on webview and in PDF.

PDF:

![table_pdf](https://user-images.githubusercontent.com/40228854/49572235-aa478280-f93b-11e8-8942-04db6de53881.JPG)

webview

![table_webview](https://user-images.githubusercontent.com/40228854/49572261-b29fbd80-f93b-11e8-9ded-be21f0165d29.JPG)

**Comment by Adrianltd** [comment]
Decision: title should be under the table, as a regular caption in every other book.
This commit should fix this issue:
https://github.com/Connexions/cnx-recipes/pull/710/commits/0583027768b3a64b2c5648e361b41179b86ab39a

**Comment by wilkus27** [comment]
Verified on katalyst01.

![table](https://user-images.githubusercontent.com/40228854/49598583-4050cc80-f97f-11e8-9917-e99361f766e0.JPG)
