### ISSUE TITLE
Psychology: Trash the answer key

### ISSUE THREAD

**Issue by Adrianltd** [Connexions/cnx-recipes#741]
@openstaxalina commented on [Thu Dec 06 2018](https://github.com/Connexions/webview/issues/2114)

Since we cannot make the answers in web view match the PDF, we should trash all solutions -- we should not have an answer key.

**Comment by Adrianltd** [comment]
Should be fixed with latest commits.
https://github.com/Connexions/cnx-recipes/pull/710/commits/c6caf6f61bf724525cb9c7b7575536dbd5ef3e81

**Comment by wilkus27** [comment]
Verified on katalyst01. There is no more Answer Key.

![answer_key](https://user-images.githubusercontent.com/40228854/49598142-50b47780-f97e-11e8-8074-01dbc4cd2d5a.JPG)
